// Generated by scripts/build.py — StudyBonk service worker.
// Precaches the app shell; pages are cached on first visit (runtime caching).
const CACHE = "studybonk-20260823152938";
const PRECACHE = ["/", "/learn/", "/flashcards/", "/quiz/", "/focus/", "/ai/", "/dashboard/", "/manifest.webmanifest", "/assets/css/style.css", "/assets/fonts/fonts.css", "/assets/js/storage.js", "/assets/js/components.js", "/assets/js/gamification.js", "/assets/js/nav.js", "/assets/js/theme.js", "/assets/js/theme-boot.js", "/assets/js/study-data.js", "/assets/js/flashcards.js", "/assets/js/quiz.js", "/assets/js/focus.js", "/assets/js/dashboard.js", "/assets/js/ai.js", "/assets/js/bonk-model.js", "/assets/img/mascot.svg", "/assets/img/logo.svg", "/assets/img/favicon.svg", "/assets/img/og-image.png", "/assets/img/creator-avatar.jpg", "/assets/fonts/Baloo2-normal-800.woff2", "/assets/fonts/Nunito-normal-400.woff2", "/assets/fonts/Nunito-normal-700.woff2"];

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => Promise.allSettled(PRECACHE.map((u) => c.add(u))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== "GET" || url.origin !== location.origin) return; // never touch cross-origin (model CDN etc.)
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => {
      const fetching = fetch(e.request).then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(e.request, copy));
        }
        return res;
      });
      return hit ? Promise.resolve(hit) : fetching;
    }).catch(() =>
      caches.match("/").then((shell) => shell || new Response("Offline", { status: 503, headers: { "Content-Type": "text/plain" } }))
    )
  );
});
