"""Creator marketing kit content for the /marketing/ page.

Consumed by scripts/build.py::marketing_page. Everything here is free
for anyone to use — hooks, scripts, captions and POV concepts for
promoting StudyBonk. Socials: TikTok @tuffycoderdev, YouTube @TuffyCoder.
Site: https://studybonk.pages.dev.
"""

MARKETING = {
    "hooks": [
        "Your flashcard app just put Learn mode behind a paywall — here's the one that never will.",
        "I found a study app that asks for no email, shows no ads, and still tracks my streak every single day.",
        "POV: the study app asks for your email before it asks what you're studying.",
        "This study app runs its AI on your own device and charges exactly zero dollars.",
        "You lost a 200-day streak to a subscription pop-up — that literally cannot happen here.",
        "Every study app says free and means free trial — this one means free.",
        "I studied for finals on an app that can't leak my data, because it never collects any.",
        "This study platform is open-source, so you can read the code before you trust it with your GPA.",
        "Stop paying a subscription to memorize things students have memorized for free since forever.",
        "The privacy policy of this study app is one sentence long: we collect nothing.",
    ],
    "shorts": [
        {
            "title": "The Study App That Wants Nothing From You",
            "duration": "PT30S",
            "beats": [
                ("0:00",
                 "Close-up of a phone showing a study app paywall pop-up",
                 "Another study app wants twelve dollars a month to let me memorize vocabulary."),
                ("0:04",
                 "Overdramatic sigh, tab closed, typing studybonk.pages.dev into a new tab",
                 "So I tried the one that asks for literally nothing."),
                ("0:08",
                 "Screen recording: the site loads instantly, no sign-up modal in sight",
                 "No account, no email, no cookie banner. It just loads."),
                ("0:14",
                 "Cursor flips a flashcard; XP counter ticks up with a bonk sound",
                 "Flashcards with spaced repetition, and you earn XP for grinding them."),
                ("0:20",
                 "Streak calendar and daily quest list scroll past",
                 "Daily quests and streaks make it feel like a game instead of homework."),
                ("0:26",
                 "AI chat panel answering a question; the Local badge gets circled",
                 "And the AI tutor runs on your device, so your questions never leave your browser. Study free at studybonk.pages.dev."),
            ],
        },
        {
            "title": "I Turned My Notes Into a Flashcard Deck in Under a Minute",
            "duration": "PT45S",
            "beats": [
                ("0:00",
                 "Messy handwritten notes held up to the camera",
                 "These are my bio notes. Ninety minutes of class, zero desire to make flashcards."),
                ("0:05",
                 "Screen: StudyBonk AI panel with the notes pasted in",
                 "So I pasted them into StudyBonk's AI tutor — free, no account, no API key."),
                ("0:12",
                 "A deck generates; cards flip automatically in fast-forward",
                 "It generated a full deck in seconds: fronts, backs, the whole thing."),
                ("0:20",
                 "Quiz mode auto-builds from the same material",
                 "Then it built a quiz from the same notes, with an explanation for every answer."),
                ("0:28",
                 "Calendar view showing each card's review schedule",
                 "Spaced repetition schedules each card right before I'd forget it. That's the whole trick."),
                ("0:36",
                 "Streak flame icon and a level-up animation",
                 "Streak at forty-one days. I'm not saying it's addictive. I'm saying I haven't missed a day since September."),
                ("0:42",
                 "End card with the URL over the mascot",
                 "studybonk.pages.dev — free forever, private by design. Go bonk your brain into shape."),
            ],
        },
        {
            "title": "What's the Catch? I Read the Code.",
            "duration": "PT45S",
            "beats": [
                ("0:00",
                 "Suspicious squint straight into the camera",
                 "A study app that's completely free, with no ads and no account? There's always a catch. So I went looking."),
                ("0:06",
                 "The GitHub repository scrolling on screen",
                 "StudyBonk is open-source, so the entire codebase is public on GitHub."),
                ("0:13",
                 "Searching the repo for analytics, results come back empty",
                 "I searched the code for analytics. Nothing. No trackers, no ad networks, no data brokers."),
                ("0:20",
                 "Browser DevTools open, cookies tab showing zero entries",
                 "Opened DevTools: zero cookies. Not 'accept all.' Zero."),
                ("0:27",
                 "The localStorage panel highlighted: decks, XP, settings",
                 "Everything saves to localStorage — your browser, your device. It never gets uploaded, because there's no server to upload to."),
                ("0:34",
                 "AI chat with a 'runs locally' callout",
                 "Even the AI tutor runs in your browser. Your 2 a.m. questions stay between you and your laptop."),
                ("0:40",
                 "Shrug at the camera",
                 "So the catch is... there isn't one. It's just free, and the receipts are public."),
                ("0:44",
                 "End card with the URL and mascot",
                 "studybonk.pages.dev — verify it yourself, then go keep your streak alive."),
            ],
        },
    ],
    "captions": [
        "No account. No ads. No paywall. Just flashcards, XP and a 2 a.m.-friendly AI tutor. Study free at studybonk.pages.dev #StudyTok #StudyApp #FreeTools #StudyHacks",
        "POV: your streak hit 40 days and the app never once asked for your email. Follow @tuffycoderdev for the build. #StudyTok #Streak #StudentLife #StudyMotivation",
        "Built a whole study platform with no accounts and no tracking — and the AI runs in your browser. Full build videos on YouTube @TuffyCoder. #StudyTips #SideProject #Coding #EdTech",
        "Turned my bio notes into a flashcard deck in under a minute. Free, private, no sign-up: studybonk.pages.dev #Shorts #StudyHacks #Flashcards #FinalsWeek",
        "The study app equivalent of a library card: free, quiet, and it never asks about you. Bonus: XP and streaks so you actually show up. #StudyGram #StudyMotivation #FreeApp #StudyWithMe",
        "Zero cookies. Zero trackers. Zero excuses. Bonk your brain into shape at studybonk.pages.dev #StudyGram #PrivacyMatters #StudentLife #FocusTimer",
        "A study app with a one-sentence privacy policy: we collect nothing. It's open-source, so you can check yourself. studybonk.pages.dev #BuildInPublic #EdTech #Privacy #OpenSource",
        "Streaks, quests, flashcards, quizzes, a focus timer and an AI that never leaves your laptop — all free, all private. #StudyTok #StudyWithMe #FocusTimer #Gamified",
        "I read the source code of a study app to find the catch. There wasn't one. github.com/TuffyCoder/StudyBonk #OpenSource #EdTech #Privacy #StudentLife",
        "Homework: read chapter 7. Me: paste chapter 7 into a free local AI that makes flashcards and quizzes from it. studybonk.pages.dev #StudyTok #AITools #StudyHacks #ExamSeason",
    ],
    "pov_ideas": [
        "POV: it's 1 a.m., you ask the AI tutor one more question, and you realize the answer never left your laptop.",
        "POV: you hit a 30-day streak and no app ever asked for your email to celebrate with you.",
        "POV: the paywall appears on your old study app — but you're already three daily quests deep in the free one.",
        "POV: you're the school laptop holding zero cookies and a full set of flashcards in local storage, feeling superior.",
        "POV: your flashcard app becomes a video game — XP bars, level-ups and a mascot named Bonk.",
        "POV: you paste an entire semester of notes and watch a deck generate itself while you sip coffee.",
        "POV: the teacher announces a review game, but you already bonked the topic into long-term memory last week.",
        "POV: exam morning, and your entire study history is a streak calendar instead of a list of subscription receipts.",
        "POV: you open DevTools to hunt for trackers on a study site, find absolutely nothing, and feel weirdly emotional about it.",
        "POV: your future self thanks you for twenty focused minutes a day, every day, all stored privately on your own device.",
    ],
    "cta_line": (
        "Study free right now at https://studybonk.pages.dev — no account, "
        "no ads, no catch. Follow the build on TikTok @tuffycoderdev and "
        "YouTube @TuffyCoder."
    ),
}
