"""StudyBonk global site configuration.

Single source of truth for brand, navigation, socials, tech badges,
security & privacy compliance statements, creator info, and shared
marketing copy. Consumed by scripts/build.py.
"""

SITE = {
    "name": "StudyBonk",
    "url": "https://studybonk.vercel.app",
    "tagline": "Bonk your brain into shape.",
    "description": (
        "StudyBonk is a free, private, gamified study platform. Flashcards, "
        "quizzes, focus timer, XP and streaks, plus a local AI tutor that "
        "runs entirely in your browser. No sign-up, no ads, no tracking."
    ),
    "locale": "en",
    "theme_color": "#4A90E2",
    "theme_color_dark": "#1A1A1A",
    "keywords": [
        "free study app",
        "flashcards",
        "study tool",
        "learn fast",
        "student help",
        "study online",
        "study motivation",
        "privacy study app",
    ],
}

# Displayed in the top navbar (desktop) and the mobile drawer.
NAV = [
    {"label": "Learn", "href": "/learn/", "children": "pillars"},
    {"label": "Flashcards", "href": "/flashcards/"},
    {"label": "Quiz", "href": "/quiz/"},
    {"label": "Focus", "href": "/focus/"},
    {"label": "Bonk AI", "href": "/ai/", "badge": "Local"},
    {"label": "Dashboard", "href": "/dashboard/"},
]

FOOTER_COLUMNS = [
    {
        "title": "Study",
        "links": [
            ("Topic Hub", "/learn/"),
            ("Free Flashcards", "/flashcards/"),
            ("Practice Quizzes", "/quiz/"),
            ("Focus Timer", "/focus/"),
            ("Study Dashboard", "/dashboard/"),
        ],
    },
    {
        "title": "Bonk AI",
        "links": [
            ("AI Study Tutor", "/ai/"),
            ("How Bonk AI Works", "/ai/#how-it-works"),
            ("AI Privacy", "/privacy/"),
        ],
    },
    {
        "title": "Trust",
        "links": [
            ("Why Trust StudyBonk", "/trust/"),
            ("Security", "/security/"),
            ("Creator", "/about/"),
            ("FAQ", "/faq/"),
            ("Creator Marketing Kit", "/marketing/"),
        ],
    },
    {
        "title": "Legal",
        "links": [
            ("Terms of Use", "/terms/"),
            ("Privacy Policy", "/privacy/"),
            ("Cookie-Free Notice", "/cookies/"),
            ("Open-Source License", "/license/"),
        ],
    },
]

SOCIALS = [
    {"name": "GitHub", "url": "https://github.com/TuffyCoder", "icon": "github"},
    {"name": "YouTube", "url": "https://www.youtube.com/@TuffyCoder", "icon": "youtube"},
    {"name": "TikTok", "url": "https://tiktok.com/@tuffycoderdev", "icon": "tiktok"},
    {"name": "Reddit", "url": "https://reddit.com/user/TuffyCoder", "icon": "reddit"},
]

TECH_BADGES = [
    ("Built with Python", "The whole site is generated by a Python build script."),
    ("Powered by HTML & CSS", "Semantic HTML and a hand-crafted design system."),
    ("Enhanced with JavaScript", "Vanilla JS — zero frameworks, zero trackers."),
    ("Hosted on Vercel", "Served safely from Vercel's global edge network."),
    ("Open-source on GitHub", "Every line is public and auditable."),
    ("Local AI — No API", "The AI tutor runs 100% in your browser."),
]

# Every page renders these guarantees in the trust strip / footer details.
COMPLIANCE = [
    "Ad-free, tracker-free, cookie-free platform",
    "No external analytics",
    "No third-party scripts",
    "No data collection",
    "No user accounts",
    "All progress saved locally in your browser",
    "Open-source transparency on GitHub",
    "Responsible disclosure / bug bounty invitation",
    "Secure-by-design architecture",
    "Zero data retention policy",
    "No hidden APIs",
    "No server-side storage",
    "Client-side encryption for sensitive data",
    "Hosted safely on Vercel's global edge network",
]

CREATOR = {
    "name": "TuffyCoder",
    "avatar": "/assets/img/creator-avatar.jpg",
    "avatar_size": 96,
    "channel": "https://www.youtube.com/@TuffyCoder",
    "credentials": [
        "Created by TuffyCoder",
        "Ethical developer",
        "Privacy-focused builder",
        "Open-source contributor",
    ],
    "bio": (
        "TuffyCoder is a solo developer who builds free, ethical, "
        "privacy-first tools for students. StudyBonk was created out of a "
        "simple frustration: every study app wants an account, an email, or "
        "your attention for ads. So StudyBonk does the opposite — no "
        "accounts, no ads, no tracking, and an AI tutor that never leaves "
        "your device. Everything is open-source so anyone can verify it."
    ),
    "signature": "Stay curious, stay bonky. — TuffyCoder 🦊",
}

# E-E-A-T block: "Why you can trust StudyBonk"
TRUST_REASONS = [
    {
        "icon": "🔒",
        "title": "Zero data collection",
        "body": (
            "StudyBonk has no accounts, no analytics, no cookies and no "
            "server-side storage. Your notes, decks and streaks live only "
            "in your browser's local storage on your own device."
        ),
    },
    {
        "icon": "📖",
        "title": "Open-source transparency",
        "body": (
            "The entire platform is open-source on GitHub. You can read "
            "every line of code — including this page — before you trust "
            "it with a single minute of study time."
        ),
    },
    {
        "icon": "🧑‍💻",
        "title": "A named, accountable author",
        "body": (
            "Every page is written and maintained by TuffyCoder, an "
            "ethical developer who publishes under a real identity with "
            "public social channels and a responsible disclosure policy."
        ),
    },
    {
        "icon": "🧠",
        "title": "Local AI, verified behavior",
        "body": (
            "The StudyBonk AI tutor runs a tiny quantized model inside "
            "your browser. No prompts are ever uploaded, and it works "
            "offline after the first load."
        ),
    },
    {
        "icon": "🛡️",
        "title": "Secure by design",
        "body": (
            "Strict security headers, no third-party scripts, a strict "
            "Content-Security-Policy, and zero hidden APIs. If you find a "
            "flaw, there's a public bug bounty invitation."
        ),
    },
    {
        "icon": "💛",
        "title": "Free forever, no catches",
        "body": (
            "No ads, no paywalls, no premium tier, no data selling. The "
            "price of StudyBonk is and always will be zero."
        ),
    },
]

# Landing-page feature grid.
FEATURES = [
    {
        "icon": "🃏",
        "title": "Smart Flashcards",
        "body": (
            "Flip, learn, repeat. Built-in decks for every topic plus "
            "spaced repetition that schedules cards you're about to forget."
        ),
        "href": "/flashcards/",
    },
    {
        "icon": "🎯",
        "title": "Instant Quizzes",
        "body": (
            "Thousands of practice questions with instant feedback and "
            "explanations, not just a score at the end."
        ),
        "href": "/quiz/",
    },
    {
        "icon": "⏱️",
        "title": "Focus Timer",
        "body": (
            "A pomodoro timer with a mascot that celebrates every session "
            "you finish. Getting started is the hardest bonk."
        ),
        "href": "/focus/",
    },
    {
        "icon": "🤖",
        "title": "Local AI Tutor",
        "body": (
            "A tiny-but-smart AI that runs in your browser — flashcard "
            "generation, quiz building, homework explanations. No API, "
            "no account, no data leaving your device."
        ),
        "href": "/ai/",
    },
    {
        "icon": "🔥",
        "title": "XP, Streaks & Quests",
        "body": (
            "Duolingo-style motivation: earn XP, keep streaks alive, finish "
            "daily quests and level up from Bonk Novice to Bonk Legend."
        ),
        "href": "/dashboard/",
    },
    {
        "icon": "🔒",
        "title": "Radical Privacy",
        "body": (
            "No sign-up, no cookies, no trackers, no data collection. "
            "Everything is saved locally in your browser — always."
        ),
        "href": "/trust/",
    },
]

# Illustrative testimonials — honestly labeled on the page as design-phase
# personas, never presented as real users.
TESTIMONIALS = [
    {
        "name": "Maya",
        "role": "High-school junior (beta persona)",
        "quote": (
            "The streak system actually got me to study 20 minutes a day. "
            "And I love that it never asks for my email."
        ),
        "emoji": "📚",
    },
    {
        "name": "Devon",
        "role": "First-year college student (beta persona)",
        "quote": (
            "Generated flashcards from my notes in seconds, then quizzed me "
            "on them. Feels illegal for something free."
        ),
        "emoji": "🚀",
    },
    {
        "name": "Aisha",
        "role": "SAT retaker (beta persona)",
        "quote": (
            "Quests + XP made practice feel like a game instead of a chore. "
            "My mock score went up 90 points in three weeks."
        ),
        "emoji": "🎯",
    },
    {
        "name": "Leo",
        "role": "Privacy-conscious parent (beta persona)",
        "quote": (
            "No ads, no accounts, no tracking — it's the only study tool I "
            "let my kids use without supervision."
        ),
        "emoji": "🛡️",
    },
]

# Comparison cards on the landing page ("free vs free").
COMPARISON_CARDS = [
    {
        "name": "StudyBonk",
        "tag": "100% free · 100% private",
        "highlight": True,
        "price": "Free forever",
        "features": [
            ("Flashcards + spaced repetition", True),
            ("Quizzes with explanations", True),
            ("Gamification (XP, streaks, quests)", True),
            ("Local AI tutor, no API", True),
            ("No account needed", True),
            ("No ads or trackers, ever", True),
            ("Open-source code", True),
        ],
        "cta": ("Start studying", "/learn/"),
    },
    {
        "name": "Typical study app",
        "tag": "freemium · ad-supported",
        "highlight": False,
        "price": "\"Free\"*",
        "features": [
            ("Flashcards + spaced repetition", "Limited on free plan"),
            ("Quizzes with explanations", "Premium feature"),
            ("Gamification (XP, streaks, quests)", "Partially paywalled"),
            ("Local AI tutor, no API", False),
            ("No account needed", False),
            ("No ads or trackers, ever", False),
            ("Open-source code", False),
        ],
        "cta": None,
    },
]

REMINDERS = [
    ("🎟️", "No sign-up required"),
    ("💾", "Everything saved in your browser"),
    ("🌙", "Light & dark mode"),
    ("🚫", "No ads · no tracking · no paywalls"),
]

PILLAR_ORDER = ["math", "biology", "chemistry", "physics", "history", "sat", "skills"]
