"""Biology pillar: 1 pillar page + 6 cluster pages.

Schema (must match exactly — see docs/CONTENT.md and topic_math.py):
PILLAR = {slug, title, emoji, meta_title<=62, meta_description<=160, h1,
tagline, summary, keywords[], longtail[12+], intro[paras], bullets[],
faqs[(q,a)x5], paa[(q,a)x5], clusters[{slug, title, h1, meta_title,
meta_description, summary, keywords[], longtail[10+],
sections[{h2, paras[], bullets[], example?{title, body}}],
key_concepts[(term,def)x8], study_tips[x5],
practice[{q, choices[4], answer(idx), explain}]x4,
flashcards[(front,back)]x10, faqs[(q,a)x4], paa[(q,a)x4]}]}
"""

PILLAR = {
    "slug": "biology",
    "title": "Biology",
    "emoji": "🧬",
    "meta_title": "Free Biology Study Hub — Cells, DNA & More | StudyBonk",
    "meta_description": "Free biology study guides, flashcards and quizzes: cells, DNA, genetics, body systems and ecosystems. No sign-up, gamified, 100% private.",
    "h1": "Free Biology Study Hub: Cells, DNA, Genetics & More",
    "tagline": "From cells to ecosystems — free guides, decks and quizzes that make biology finally click.",
    "summary": "Free biology guides, flashcard decks and practice quizzes for cells, DNA, genetics, body systems and ecosystems.",
    "keywords": [
        "biology help",
        "learn biology online free",
        "biology flashcards",
        "cell biology basics",
        "dna and genetics help",
        "photosynthesis explained",
        "body systems study guide",
        "ecosystems and food webs",
        "mitosis vs meiosis",
        "free biology quiz",
    ],
    "longtail": [
        "how to study biology effectively for exams",
        "what is the difference between mitosis and meiosis",
        "how does photosynthesis work step by step",
        "how to do punnett squares for beginners",
        "what are the parts of a cell and their functions",
        "prokaryotic vs eukaryotic cells difference",
        "what are the 11 human body systems",
        "how does energy flow through an ecosystem",
        "what is the 10 percent rule in ecology",
        "how to memorize biology terms fast",
        "why do I fail biology tests even when I study",
        "best free website to learn biology without signing up",
        "is biology harder than chemistry",
    ],
    "intro": [
        "Biology is the study of life, and life turns out to be a set of systems you can actually understand — cells with jobs, DNA with a code, ecosystems with rules. The problem is that bio throws a mountain of vocabulary at you at once, and memorizing words without meaning them is exactly why it feels overwhelming. StudyBonk splits the difference: short lessons that explain the why, flashcard decks that drill the vocab, and quizzes that explain every answer.",
        "Every page below is 100% free, works without an account, and saves your progress right in your browser. Earn XP, keep your streak alive, and turn the unit you dread into the one you're quietly best at.",
    ],
    "bullets": [
        "Master cell basics: organelles, prokaryotes vs eukaryotes",
        "Finally understand photosynthesis, both stages",
        "Break DNA down into genes, traits and Punnett squares",
        "Tour all the major human body systems in one place",
        "Trace energy through food chains, webs and biomes",
        "Tell mitosis and meiosis apart on any test",
    ],
    "faqs": [
        ("Is StudyBonk good for high school biology?",
         "Yes. StudyBonk covers the units that make up nearly every standard biology course — cells, genetics, body systems, ecology and cell division — with short lessons, flashcard decks and quizzes that explain every answer. It's free, requires no account, and works offline after the first load."),
        ("What's the best way to memorize biology vocabulary?",
         "Active recall in both directions: given 'mitochondrion,' say the job; given 'the cell's power plant,' name the organelle. StudyBonk's flashcards with spaced repetition handle the scheduling — 10-15 minutes a day beats hours of re-reading your notes."),
        ("How much should I study biology per day?",
         "About 20-30 focused minutes daily. Biology is vocabulary-dense, and spaced repetition is how language-like subjects stick. Keep your streak alive with a short session even on busy days — consistency is the whole game."),
        ("Can I use StudyBonk biology offline?",
         "Yes. After your first visit, the app is cached by your browser and works offline, including flashcards, quizzes and the AI tutor. Your XP, streaks and progress are stored locally on your device."),
        ("Is StudyBonk really free with no account?",
         "Really free, really no account. No ads, no paywalls, no email capture, no tracking. Everything saves in your browser's local storage, and the code is open-source on GitHub so you can verify all of this yourself."),
    ],
    "paa": [
        ("What is biology in simple words?",
         "The study of life — how living things are built, how they work, and how they interact with each other and their environment."),
        ("What order should I learn biology topics in?",
         "Cells first (they're the unit everything else builds from), then energy processes like photosynthesis, then genetics and cell division, then body systems, then ecosystems. Each rung makes the next one easier."),
        ("Why does biology feel like so much memorization?",
         "Because it introduces more new words than any other science. Attach each term to a job or a picture instead of a definition, and drill with flashcards — the load drops fast once the concepts connect."),
        ("How do I study for a biology test?",
         "Quiz yourself instead of re-reading: flashcards for vocabulary, practice questions for applying it, and drawing diagrams (a cell, a Punnett square, a food web) from blank paper. If you can reproduce a diagram from memory, you're test-ready."),
        ("Is biology harder than chemistry?",
         "Biology is more memorization-heavy; chemistry is more math-heavy. Students who like stories and big pictures usually find biology friendlier — and either science gets easier fast once the core vocabulary clicks."),
    ],
    "clusters": [
        {
            "slug": "cell-basics",
            "title": "Cell Basics",
            "h1": "Cell Basics Made Simple: Organelles, Prokaryotes & Eukaryotes",
            "meta_title": "Cell Basics: Organelles Explained Simply | StudyBonk",
            "meta_description": "Learn cells free: every organelle's job, prokaryotes vs eukaryotes, plant vs animal cells — with flashcards, a quiz and worked examples. No sign-up.",
            "summary": "Cells, organelles and the prokaryote vs eukaryote split — explained like a friend, not a textbook.",
            "keywords": [
                "cell biology basics",
                "cell organelles and functions",
                "prokaryotic vs eukaryotic cells",
                "plant vs animal cells",
                "cell structure help",
                "free biology practice",
            ],
            "longtail": [
                "what are the parts of a cell and their functions",
                "difference between prokaryotic and eukaryotic cells",
                "plant cells vs animal cells differences list",
                "what does the mitochondria do in a cell",
                "where is dna found in a cell",
                "what organelles do prokaryotes have",
                "how to memorize cell organelles easily",
                "what is the function of the cell membrane",
                "is a bacterium prokaryotic or eukaryotic",
                "which organelle is the powerhouse of the cell",
            ],
            "sections": [
                {
                    "h2": "What a cell is (and why it matters)",
                    "paras": [
                        "A cell is the smallest thing that is alive — the basic unit of every organism on Earth. You are made of roughly 30 trillion of them. Anything smaller than a cell, like a virus or a protein, is not alive on its own, which is why the cell is biology's fundamental unit.",
                        "Every cell does the same core jobs: take in nutrients and energy, get rid of waste, respond to its environment, and grow or divide. Whether it's a bacterium or a brain cell, that to-do list never changes. Learn those jobs once and every organelle makes sense as a department that handles one task.",
                    ],
                    "bullets": [
                        "Cell: the smallest unit of life — every organism is made of them",
                        "Every cell takes in energy, removes waste, responds, grows and divides",
                        "Unicellular organisms (like bacteria) are one cell; multicellular ones like you are many",
                        "Anything smaller than a cell is not alive on its own",
                    ],
                },
                {
                    "h2": "The organelle tour: what each part does",
                    "paras": [
                        "Organelles are tiny organs inside a cell, each with a specific job. The nucleus stores DNA and runs the show. Mitochondria break down food to make ATP energy. Ribosomes build proteins, and the endoplasmic reticulum ships those proteins around like an internal highway.",
                        "Plant cells add two big extras: chloroplasts, which do photosynthesis, and a stiff cell wall outside the membrane. Vacuoles store water — huge in plants, which is why a thirsty plant droops — and lysosomes are the recycling crew that breaks down worn-out parts. Match each organelle to a one-word job, like factory or power plant, and the list memorizes itself.",
                    ],
                    "bullets": [
                        "Nucleus: control center — stores DNA",
                        "Mitochondria: power plants — make ATP energy",
                        "Ribosomes: factories — build proteins",
                        "Chloroplasts (plants only): capture sunlight for photosynthesis",
                        "Vacuole: storage tank — water, food and waste",
                    ],
                    "example": {
                        "title": "Worked example: which organelle would a muscle cell need lots of?",
                        "body": "Muscle cells burn huge amounts of energy contracting, so they are packed with mitochondria — the ATP factories. That's the pattern for organelle questions: ask what the cell does most, then pick the organelle that supports that job.",
                    },
                },
                {
                    "h2": "Prokaryotic vs eukaryotic: the one big split",
                    "paras": [
                        "Cells come in two architectural styles. Prokaryotic cells (bacteria and archaea) are small and simple, with no nucleus — their DNA floats free in the cytoplasm. Eukaryotic cells (animals, plants, fungi, protists) are larger, keep their DNA inside a membrane-bound nucleus, and have organelles doing specialized jobs.",
                        "Here's the memory hook: 'pro' sounds like primitive, 'eu' like 'you.' Every organism you can see without a microscope is eukaryotic. Both types have DNA, ribosomes, cytoplasm and a cell membrane — the real difference is the nucleus and the organelle crew.",
                    ],
                    "bullets": [
                        "Prokaryotes: no nucleus, no membrane-bound organelles, always single cells",
                        "Eukaryotes: nucleus plus organelles; single-celled or whole organisms",
                        "Both have: DNA, ribosomes, cytoplasm and a cell membrane",
                        "Bacteria are prokaryotes; plants, animals, fungi and protists are eukaryotes",
                    ],
                },
                {
                    "h2": "How to study cells without drowning in vocab",
                    "paras": [
                        "Cell biology feels like a foreign language course because it is one — dozens of new words per chapter. The fix is learning each term attached to its job instead of its spelling. Cover the right side of your notes and recite the function; then cover the function and name the organelle. Both directions, ten minutes a day.",
                        "Sketch a cell from memory twice a week and label everything you can. Compare your sketch to a textbook diagram and study only what you missed. Drawing forces your brain to store the structure, not just the word — and labeled diagrams are exactly what tests use anyway.",
                    ],
                    "bullets": [
                        "Study terms as jobs (power plant, factory, gatekeeper), not spellings",
                        "Quiz both directions: name to job, and job to name",
                        "Sketch and label a cell from memory twice a week",
                        "Run the flashcard deck below daily until recall is instant",
                    ],
                },
            ],
            "key_concepts": [
                ("Cell", "The smallest unit of life; all living things are made of one or more cells."),
                ("Organelle", "A specialized structure inside a cell that performs one job, like a tiny organ."),
                ("Nucleus", "The control center of eukaryotic cells; stores DNA and directs activity."),
                ("Mitochondrion", "The organelle that converts food energy into ATP — the cell's power plant."),
                ("Ribosome", "The structure that builds proteins following DNA instructions."),
                ("Cell membrane", "The flexible outer boundary that controls what enters and leaves the cell."),
                ("Chloroplast", "The plant organelle that captures sunlight for photosynthesis."),
                ("Prokaryote", "A cell without a nucleus; bacteria are the classic examples."),
            ],
            "study_tips": [
                "Learn organelles as departments in a factory — the analogy sticks better than definitions.",
                "Draw and label a cell from memory, then check against a diagram; the gaps jump out.",
                "Use flashcards in both directions so you can name a part from its job and vice versa.",
                "For any organelle question, ask what the cell needs most and pick the matching organelle.",
                "Say comparisons out loud: 'prokaryote = no nucleus, like bacteria' until it's automatic.",
            ],
            "practice": [
                {
                    "q": "Which organelle stores DNA and controls the cell's activities?",
                    "choices": ["Ribosome", "Nucleus", "Mitochondrion", "Vacuole"],
                    "answer": 1,
                    "explain": "The nucleus is the control center: it stores DNA and directs everything the cell does. Mitochondria handle energy and ribosomes build proteins, but neither stores DNA (in eukaryotes).",
                },
                {
                    "q": "A cell is surrounded by liquid. Which structure decides what enters and leaves?",
                    "choices": ["Cell wall", "Nucleus", "Vacuole", "Cell membrane"],
                    "answer": 3,
                    "explain": "The cell membrane is the gatekeeper — a flexible boundary that controls what gets in and out. The cell wall is a rigid extra layer for support, found in plants but not animals.",
                },
                {
                    "q": "Which pair correctly matches an organism to its cell type?",
                    "choices": ["Bacteria — prokaryote", "Bacteria — eukaryote", "Human — prokaryote", "Mushroom — prokaryote"],
                    "answer": 0,
                    "explain": "Bacteria are prokaryotes: no nucleus, DNA floating in the cytoplasm. Humans and mushrooms (a fungus) are eukaryotes — anything big enough to see without a microscope is.",
                },
                {
                    "q": "A plant is kept in complete darkness for a week. Which organelle is directly out of work?",
                    "choices": ["Mitochondrion", "Nucleus", "Chloroplast", "Ribosome"],
                    "answer": 2,
                    "explain": "Chloroplasts need light to do photosynthesis, so in darkness they sit idle. Mitochondria keep working by burning stored food — which is how the plant survives the week at all.",
                },
            ],
            "flashcards": [
                ("What is a cell?", "The smallest unit of life."),
                ("What is an organelle?", "A specialized structure inside a cell with a specific job."),
                ("Job of the nucleus?", "Stores DNA and controls the cell's activities."),
                ("Job of mitochondria?", "Make ATP energy from food — the cell's power plant."),
                ("Job of ribosomes?", "Build proteins."),
                ("Job of the cell membrane?", "Controls what enters and leaves the cell."),
                ("Where is DNA in a prokaryote?", "Free in the cytoplasm — there is no nucleus."),
                ("Two structures plant cells have that animal cells don't", "Chloroplasts and a cell wall."),
                ("Prokaryote vs eukaryote in one line", "Prokaryote = no nucleus; eukaryote = nucleus plus organelles."),
                ("Job of the vacuole?", "Stores water, food and waste (huge in plant cells)."),
            ],
            "faqs": [
                ("What is the difference between plant and animal cells?",
                 "Plant cells have chloroplasts, a large central vacuole and a stiff cell wall; animal cells have none of those but often have lysosomes and centrioles. Both have a nucleus, mitochondria, ribosomes and a cell membrane — most of the cell is shared."),
                ("Do prokaryotes have any organelles?",
                 "They have ribosomes, which are technically organelles without membranes, but no membrane-bound organelles — no nucleus, no mitochondria, no chloroplasts. That's the meaning of 'simple' in a simple cell."),
                ("Why do muscle cells have so many mitochondria?",
                 "Because contracting burns enormous amounts of ATP. Cells build more of the organelle their job depends on — that single idea answers most 'which cell has the most X' questions."),
                ("What is the fastest way to learn organelles?",
                 "Learn each one as a role in a factory (nucleus = boss, ribosome = assembly line, membrane = security gate) and quiz yourself with flashcards both directions, 10 minutes a day for a week."),
            ],
            "paa": [
                ("What are the main parts of a cell?", "Membrane (gatekeeper), cytoplasm (filling), nucleus (DNA boss), mitochondria (energy), ribosomes (protein factories) — plus chloroplasts and a cell wall in plants."),
                ("Is bacteria prokaryotic or eukaryotic?", "Prokaryotic — bacteria have no nucleus and no membrane-bound organelles. So are archaea; everything else alive that you'd study in school is eukaryotic."),
                ("What does the mitochondria do?", "It converts energy from food into ATP, the molecule cells actually spend. That's why it's nicknamed the powerhouse — and why energy-hungry cells are full of them."),
                ("Do all cells have a cell membrane?", "Yes — every cell, prokaryote or eukaryote, is wrapped in a cell membrane. Cell walls are the optional extra: plants, fungi and bacteria have them, animals don't."),
            ],
        },
        {
            "slug": "photosynthesis",
            "title": "Photosynthesis",
            "h1": "Photosynthesis Explained: Light Reactions & the Calvin Cycle",
            "meta_title": "Photosynthesis Made Easy — Free Guide | StudyBonk",
            "meta_description": "Photosynthesis explained simply: the equation, light-dependent reactions and the Calvin cycle. Free flashcards, worked examples and a quiz. No sign-up.",
            "summary": "The equation, the two stages and where every atom goes — photosynthesis without the fog.",
            "keywords": [
                "photosynthesis explained",
                "light dependent reactions",
                "calvin cycle",
                "photosynthesis equation",
                "chloroplast and chlorophyll",
                "free biology quiz",
            ],
            "longtail": [
                "how does photosynthesis work step by step",
                "what are the products of photosynthesis",
                "light dependent vs light independent reactions",
                "what happens in the calvin cycle",
                "where does photosynthesis take place in a plant",
                "where does the oxygen in photosynthesis come from",
                "what is the difference between chlorophyll and chloroplast",
                "what would happen if a plant was kept in the dark",
                "photosynthesis inputs and outputs list",
                "how is photosynthesis different from cellular respiration",
            ],
            "sections": [
                {
                    "h2": "The big idea: food from sunlight",
                    "paras": [
                        "Photosynthesis is how plants, algae and some bacteria make their own food using sunlight, water and carbon dioxide. The output is glucose, a sugar that stores energy in its chemical bonds, plus oxygen as a byproduct. Nearly every food chain on Earth starts with this one reaction.",
                        "The summary equation is worth memorizing: 6CO2 + 6H2O + light energy → C6H12O6 + 6O2. Read it as a story: six carbon dioxides plus six waters, powered by light, become one glucose and six oxygens. And notice where the oxygen comes from — the water, not the carbon dioxide. That detail shows up on tests constantly.",
                    ],
                    "bullets": [
                        "Inputs: carbon dioxide, water, sunlight",
                        "Outputs: glucose (stored energy) and oxygen",
                        "Location: chloroplasts, powered by the green pigment chlorophyll",
                        "Equation: 6CO2 + 6H2O + light → C6H12O6 + 6O2",
                        "The released oxygen comes from splitting water, not from CO2",
                    ],
                },
                {
                    "h2": "Stage 1: The light-dependent reactions",
                    "paras": [
                        "Inside every chloroplast are stacks of green discs called thylakoids, and that's where stage one happens. Chlorophyll absorbs sunlight, and that captured energy is used to split water molecules — releasing oxygen — and to charge two energy carriers, ATP and NADPH. Think of this stage as charging batteries in full sun.",
                        "The name tells you the rule: light-dependent reactions need light to run. At night they shut down. Their whole purpose is converting light energy into chemical energy that stage two can spend to build sugar.",
                    ],
                    "bullets": [
                        "Location: thylakoid membranes inside the chloroplast",
                        "Light hits chlorophyll; water is split, releasing oxygen",
                        "Products: ATP and NADPH — charged energy carriers",
                        "Need light to run — they stop in darkness",
                    ],
                    "example": {
                        "title": "Worked example: a plant moved into a dark closet",
                        "body": "Light-dependent reactions shut down within minutes: no light means no water splitting, so oxygen release stops and ATP/NADPH production stops. The plant survives on stored glucose — so the right answer to 'what happens?' is 'the light reactions stop,' not 'the plant dies instantly.'",
                    },
                },
                {
                    "h2": "Stage 2: The Calvin cycle (no light required)",
                    "paras": [
                        "The Calvin cycle happens in the stroma, the fluid surrounding the thylakoids. It takes the ATP and NADPH from stage one plus carbon dioxide from the air and assembles glucose piece by piece. This is the building phase of photosynthesis — the plant's food factory floor.",
                        "It's called light-independent, not light-negative, which trips students up. The Calvin cycle doesn't use light directly, so it can briefly run in the dark — but only until the ATP and NADPH batteries run out, usually within minutes. The two stages work as a team: one charges the batteries, the other spends them.",
                    ],
                    "bullets": [
                        "Location: the stroma (the fluid) of the chloroplast",
                        "Inputs: CO2 from the air plus ATP and NADPH from stage 1",
                        "Output: glucose, built one carbon at a time",
                        "Doesn't use light directly — runs on stored energy carriers",
                    ],
                },
                {
                    "h2": "Why photosynthesis matters to you",
                    "paras": [
                        "Every calorie you have ever eaten traces back to photosynthesis — plants made the food, or fed the animal you ate. The oxygen in every breath you take is its byproduct. And by pulling CO2 out of the air, photosynthesis drives the planet's carbon cycle and sets the baseline for Earth's climate.",
                        "For exams, anchor yourself to the equation and the two stages. If a question mentions light, think thylakoids, water splitting and ATP. If it mentions building sugar or using CO2, think stroma and the Calvin cycle. Almost every photosynthesis question is really asking which stage does the job.",
                    ],
                    "bullets": [
                        "Nearly all food chains begin with photosynthetic producers",
                        "The oxygen you breathe is a photosynthetic byproduct",
                        "Producers pull CO2 from the air, powering the carbon cycle",
                        "Exam shortcut: light questions = thylakoids; sugar questions = stroma",
                    ],
                },
            ],
            "key_concepts": [
                ("Photosynthesis", "The process plants use to convert sunlight, water and CO2 into glucose and oxygen."),
                ("Chlorophyll", "The green pigment in chloroplasts that absorbs light energy."),
                ("Chloroplast", "The plant organelle where photosynthesis happens."),
                ("Thylakoid", "Stacked membrane discs inside a chloroplast; site of the light-dependent reactions."),
                ("Stroma", "The fluid around the thylakoids; site of the Calvin cycle."),
                ("Light-dependent reactions", "Stage 1: light splits water, releasing O2 and producing ATP and NADPH."),
                ("Calvin cycle", "Stage 2: uses ATP, NADPH and CO2 to build glucose in the stroma."),
                ("Glucose", "The sugar produced by photosynthesis; stores energy in its chemical bonds."),
            ],
            "study_tips": [
                "Memorize the equation as a story of inputs becoming outputs — not as random symbols.",
                "Map every stage to a location: light = thylakoids, Calvin cycle = stroma. Location answers half of test questions.",
                "Anchor the tricky fact: the oxygen comes from water. Recite it until it's automatic.",
                "Draw the chloroplast from memory and label thylakoids vs stroma — the two stages become rooms in a house.",
                "Run the flashcard deck daily for a week; photosynthesis is pure vocabulary-plus-mapping.",
            ],
            "practice": [
                {
                    "q": "Which gas do plants take in from the air for photosynthesis?",
                    "choices": ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"],
                    "answer": 1,
                    "explain": "CO2 is an input — it enters through leaf pores called stomata and gets built into glucose during the Calvin cycle. Oxygen is an output, not an input.",
                },
                {
                    "q": "Where do the light-dependent reactions take place?",
                    "choices": ["In the stroma", "In the mitochondria", "In the thylakoid membranes", "In the nucleus"],
                    "answer": 2,
                    "explain": "Light reactions happen in the thylakoid membranes — the green stacks inside chloroplasts. The stroma is the fluid around them, home of the Calvin cycle.",
                },
                {
                    "q": "What two energy carriers does stage 1 deliver to the Calvin cycle?",
                    "choices": ["ATP and NADPH", "Glucose and oxygen", "DNA and RNA", "CO2 and water"],
                    "answer": 0,
                    "explain": "ATP and NADPH are the charged batteries made by the light reactions. The Calvin cycle spends them to build glucose from CO2 — which is why the stages are a team.",
                },
                {
                    "q": "The oxygen released during photosynthesis comes from:",
                    "choices": ["Splitting carbon dioxide", "The soil", "Chlorophyll breaking down", "Splitting water"],
                    "answer": 3,
                    "explain": "In the light reactions, water molecules are split to free electrons and hydrogen — and oxygen is the leftover, released as gas. Carbon dioxide keeps its oxygen; it ends up in the glucose.",
                },
            ],
            "flashcards": [
                ("Photosynthesis equation", "6CO2 + 6H2O + light → C6H12O6 + 6O2"),
                ("Inputs of photosynthesis", "Carbon dioxide, water and sunlight."),
                ("Outputs of photosynthesis", "Glucose and oxygen."),
                ("Where photosynthesis happens", "In chloroplasts (specifically thylakoids + stroma)."),
                ("Job of chlorophyll", "Absorb light energy — it's the green pigment."),
                ("Thylakoid vs stroma", "Thylakoids = light-dependent reactions; stroma = Calvin cycle."),
                ("What stage 1 produces", "ATP, NADPH and oxygen (from splitting water)."),
                ("What the Calvin cycle produces", "Glucose, using CO2 plus ATP and NADPH."),
                ("Where the released oxygen comes from", "Splitting water molecules — not CO2."),
                ("Light-independent means", "Doesn't use light directly — but needs stage 1's ATP and NADPH, so it stalls in prolonged dark."),
            ],
            "faqs": [
                ("What is the difference between the light-dependent reactions and the Calvin cycle?",
                 "The light reactions (in the thylakoids) capture light energy, split water to release oxygen and charge ATP and NADPH. The Calvin cycle (in the stroma) spends that ATP and NADPH to build glucose from CO2. One charges the batteries; the other spends them."),
                ("Can the Calvin cycle happen in the dark?",
                 "Briefly, yes — it doesn't use light directly. But it depends on ATP and NADPH from the light reactions, which run out within minutes in darkness. That's why plants can't grow without light even though the sugar-building stage is 'light-independent.'"),
                ("Why are plants green?",
                 "Chlorophyll absorbs red and blue light strongly but reflects green, and reflected light is what reaches your eyes. The plant isn't using the green light — it's bouncing it back at you."),
                ("How is photosynthesis different from respiration?",
                 "Photosynthesis builds sugar from CO2 and water using light energy, releasing oxygen. Cellular respiration burns sugar with oxygen to release energy, producing CO2 and water. They're chemical opposites — and plants run both."),
            ],
            "paa": [
                ("What are the products of photosynthesis?", "Glucose and oxygen: glucose stores the captured energy, oxygen is released as a byproduct of splitting water."),
                ("Where does photosynthesis occur?", "In chloroplasts — light reactions in the thylakoid membranes, the Calvin cycle in the surrounding stroma."),
                ("What gas do plants release during photosynthesis?", "Oxygen, produced when light-dependent reactions split water molecules."),
                ("Do plants breathe oxygen?", "Yes — plants run cellular respiration too, burning their own glucose with oxygen around the clock. They simply make more oxygen than they consume."),
            ],
        },
        {
            "slug": "dna-and-genetics",
            "title": "DNA & Genetics",
            "h1": "DNA & Genetics Explained: Genes, Traits & Punnett Squares",
            "meta_title": "DNA and Genetics Made Simple — Free | StudyBonk",
            "meta_description": "Learn DNA and genetics free: the double helix, genes vs traits, dominant vs recessive and Punnett squares step by step. Flashcards, quiz, no sign-up.",
            "summary": "DNA's structure, how genes become traits, and Punnett squares you can actually do — explained simply.",
            "keywords": [
                "dna and genetics basics",
                "punnett square practice",
                "dominant and recessive traits",
                "dna structure explained",
                "genotype vs phenotype",
                "free genetics quiz",
            ],
            "longtail": [
                "what is dna and what does it do",
                "how to do a punnett square step by step",
                "difference between genotype and phenotype",
                "what is the difference between a gene and an allele",
                "dominant vs recessive alleles explained",
                "can two brown eyed parents have a blue eyed child",
                "what are the base pairs of dna",
                "how does dna determine traits",
                "homozygous vs heterozygous difference",
                "what does it mean to be a genetic carrier",
            ],
            "sections": [
                {
                    "h2": "What DNA is and how it's shaped",
                    "paras": [
                        "DNA is the instruction manual for building and running a living thing, written in a code just four letters long: A, T, G and C. Those letters are chemical bases, and they pair under a strict rule — A always pairs with T, G always pairs with C. That pairing rule is what lets DNA copy itself accurately.",
                        "Structurally, DNA is a double helix: two strands twisted like a ladder, where the rails are sugar-phosphate backbones and every rung is a base pair. A gene is a stretch of that ladder spelling instructions for one protein, and proteins do the work that creates traits — from eye color to whether you can taste certain bitter foods.",
                    ],
                    "bullets": [
                        "Four bases: A, T, G, C — A pairs with T, G pairs with C",
                        "Double helix: two twisted strands, base pairs as the rungs",
                        "Gene: a stretch of DNA with instructions for one protein",
                        "Proteins carry out the instructions — they create the traits you see",
                    ],
                },
                {
                    "h2": "From genotype to phenotype",
                    "paras": [
                        "Your genotype is the alleles you actually carry; your phenotype is what shows up on the outside — brown eyes, dimples, attached earlobes. You carry two copies of most genes, one from each parent, and each copy is called an allele. The combination of alleles is what a Punnett square tracks.",
                        "Alleles can be dominant or recessive. A dominant allele, written as a capital like T for tall, shows its effect even with only one copy. A recessive allele, lowercase t, only shows when both copies are recessive. That's why carriers of a recessive condition often show no sign of it — one healthy dominant allele is enough to mask it.",
                    ],
                    "bullets": [
                        "Genotype = the alleles you carry (Tt); phenotype = what you show (tall)",
                        "Homozygous = two matching alleles (TT or tt); heterozygous = one of each (Tt)",
                        "Dominant allele: shows its effect with just one copy",
                        "Recessive allele: only visible with two copies",
                    ],
                    "example": {
                        "title": "Worked example: reading 'Tt'",
                        "body": "Tt means heterozygous: one dominant tall allele, one recessive short one. The phenotype is tall, because T dominates. Genotype = Tt, phenotype = tall. Writing both words out every single time builds the exact habit tests look for.",
                    },
                },
                {
                    "h2": "Punnett squares: predicting offspring odds",
                    "paras": [
                        "A Punnett square is just a grid that shuffles two parents' alleles to show every possible child. Each parent randomly gives one allele per gene. Put one parent's two alleles across the top and the other's down the side, then fill in the four boxes — each box is an equally likely offspring genotype.",
                        "The classic cross is Tt x Tt. The four boxes come out TT, Tt, Tt and tt — so 3 out of 4 (75%) show the dominant trait and 1 out of 4 (25%) shows the recessive. Remember: Punnett squares show probability, not promises. Two Tt parents can absolutely have two tall kids in a row.",
                    ],
                    "bullets": [
                        "Each box = one equally likely offspring genotype",
                        "Tt x Tt gives a 3:1 phenotype ratio (75% dominant, 25% recessive)",
                        "Tt x tt gives 50/50 — half show the dominant trait, half the recessive",
                        "Ratios are probabilities, not guarantees about real children",
                    ],
                    "example": {
                        "title": "Worked example: cross Bb x bb (B = brown eyes)",
                        "body": "Parent 1 can give B or b; parent 2 can only give b. Boxes: Bb, Bb, bb, bb. Genotype ratio: 50% Bb, 50% bb. Phenotype: 50% brown eyes, 50% blue. Quick check — count how many boxes contain at least one capital B, and that count over four is your dominant fraction.",
                    },
                },
                {
                    "h2": "Beyond dominant and recessive",
                    "paras": [
                        "Not every gene follows the simple dominant-recessive script. In incomplete dominance, the two alleles blend — a red flower crossed with a white one gives pink. In codominance, both alleles show fully, like a roan cow with both red and white hairs, or human AB blood type.",
                        "Most real human traits — height, skin color, and many disease risks — are polygenic, meaning many genes contribute small effects, which is why people come in continuous ranges rather than two types. For class, master the simple Punnett square first; every fancier variation uses the exact same grid mechanics.",
                    ],
                    "bullets": [
                        "Incomplete dominance: alleles blend (red + white = pink)",
                        "Codominance: both alleles show fully (AB blood type)",
                        "Polygenic traits: many genes add up (height, skin color)",
                        "All the variations still use the same Punnett square grid",
                    ],
                },
            ],
            "key_concepts": [
                ("DNA", "The molecule that stores hereditary information, shaped as a double helix."),
                ("Gene", "A segment of DNA with instructions for one protein."),
                ("Allele", "One version of a gene; you inherit two per gene, one from each parent."),
                ("Dominant allele", "An allele that shows its effect even when only one copy is present (Tt = tall)."),
                ("Recessive allele", "An allele that only shows its effect when both copies match (tt = short)."),
                ("Genotype", "The allele combination an organism carries, like TT, Tt or tt."),
                ("Phenotype", "The observable trait that actually shows, like tall or blue eyes."),
                ("Punnett square", "A grid showing all possible offspring genotypes from two parents' alleles."),
            ],
            "study_tips": [
                "Memorize base pairing as two pairs: A-T and G-C. Quiz it in both directions.",
                "Always write genotype AND phenotype for every answer — most lost points come from mixing them up.",
                "Draw every Punnett square, even when you could do it in your head; the grid prevents careless errors.",
                "Attach vocabulary to one running example (like Tt tall peas) and reuse it all year.",
                "Say the ratio out loud when you finish a square: 'three dominant, one recessive' — patterns stick when spoken.",
            ],
            "practice": [
                {
                    "q": "In DNA, adenine (A) always pairs with:",
                    "choices": ["G", "C", "T", "A"],
                    "answer": 2,
                    "explain": "A pairs with T and G pairs with C — always. This complementary pairing is what lets DNA copy itself so accurately.",
                },
                {
                    "q": "Two parents are both heterozygous (Tt). What fraction of offspring is predicted to show the recessive trait?",
                    "choices": ["0%", "25%", "50%", "75%"],
                    "answer": 1,
                    "explain": "Tt x Tt gives TT, Tt, Tt, tt. Only the single tt box shows the recessive trait: 1 out of 4 = 25%. Three of four boxes (75%) show the dominant trait.",
                },
                {
                    "q": "A person's genotype is Bb, where B (brown eyes) is dominant. Their phenotype is:",
                    "choices": ["Brown eyes", "Blue eyes", "One brown and one blue eye", "Impossible to know"],
                    "answer": 0,
                    "explain": "One dominant B allele is enough to show the trait, so Bb = brown eyes. Only bb would give blue eyes in this simple model.",
                },
                {
                    "q": "Which cross produces a predicted 50/50 split of dominant to recessive phenotypes?",
                    "choices": ["TT x TT", "Tt x Tt", "tt x tt", "Tt x tt"],
                    "answer": 3,
                    "explain": "Tt x tt gives Tt, Tt, tt, tt — exactly half show the dominant trait, half the recessive. The heterozygous x recessive cross is the 50/50 one.",
                },
            ],
            "flashcards": [
                ("DNA base pairing rule", "A pairs with T; G pairs with C."),
                ("Shape of DNA", "A double helix — two twisted strands with base pairs as rungs."),
                ("What is a gene?", "A stretch of DNA with instructions for one protein."),
                ("What is an allele?", "One version of a gene — you get two per gene, one from each parent."),
                ("Genotype vs phenotype", "Genotype = alleles you carry (Tt); phenotype = the trait you show (tall)."),
                ("Homozygous vs heterozygous", "Homozygous = matching alleles (TT or tt); heterozygous = one of each (Tt)."),
                ("When does a recessive trait appear?", "Only when both alleles are recessive (tt)."),
                ("Tt x Tt phenotype ratio", "3:1 — 75% dominant, 25% recessive."),
                ("What does a Punnett square show?", "All possible offspring genotypes and their probabilities — not guarantees."),
                ("What is a carrier?", "A heterozygote who carries a recessive allele but doesn't show the trait."),
            ],
            "faqs": [
                ("What's the difference between DNA, a gene and a chromosome?",
                 "DNA is the whole instruction molecule; a gene is one recipe within it; a chromosome is a long, coiled package of DNA. Library analogy: chromosome = book, gene = one recipe in the book, DNA = the language it's written in."),
                ("Can two brown-eyed parents have a blue-eyed child?",
                 "Yes, if both parents are carriers (Bb). A Bb x Bb cross gives a 25% chance of bb — blue eyes. Eye color is actually more complex than one gene, but the simple model still explains how recessive traits skip generations."),
                ("Why do I look like a mix of my parents but not exactly like either?",
                 "You got half your alleles from each parent, shuffled randomly — and dominant alleles can mask recessive ones. Meiosis also shuffles and recombines DNA, so every child (except identical twins) gets a unique combination."),
                ("What does it mean to be a carrier?",
                 "You carry one copy of a recessive allele without showing any effect, because your other allele is dominant. Carriers matter in genetics because two carriers can each pass the recessive allele to a child, who then shows the trait."),
            ],
            "paa": [
                ("What is DNA in simple words?", "A twisted ladder-shaped molecule that stores the instructions for building and running a living thing, written in a four-letter code."),
                ("How do you set up a Punnett square?", "Write one parent's two alleles across the top, the other parent's down the side, and fill each box with the column + row letters. Each of the four boxes is an equally likely offspring."),
                ("What is the difference between genotype and phenotype?", "Genotype is the alleles you carry (like Tt); phenotype is the trait that shows (like tall). Same organism, two different levels of description."),
                ("What is an example of a recessive human trait?", "Blue eyes, attached earlobes and the ability to roll your tongue's opposite — these show up only when both alleles are recessive in the simple models taught in school."),
            ],
        },
        {
            "slug": "human-body-systems",
            "title": "Human Body Systems",
            "h1": "Human Body Systems Explained: The Full Tour, Simply",
            "meta_title": "Human Body Systems Explained — Free Guide | StudyBonk",
            "meta_description": "All the human body systems with one-line jobs, organ matches and how they work together. Free flashcards and quiz, gamified, private, no sign-up.",
            "summary": "Every major body system with its one-line job — plus how they team up to keep you alive.",
            "keywords": [
                "human body systems",
                "body systems and functions",
                "circulatory system basics",
                "nervous system overview",
                "homeostasis explained",
                "free anatomy quiz",
            ],
            "longtail": [
                "what are the 11 human body systems",
                "body systems and their main functions list",
                "how do body systems work together",
                "what is homeostasis in simple terms",
                "which organs belong to which body system",
                "difference between nervous and endocrine system",
                "what body system do the kidneys belong to",
                "how are cells tissues organs and systems related",
                "what happens to body systems during exercise",
                "easiest way to memorize the body systems",
            ],
            "sections": [
                {
                    "h2": "How the body is organized",
                    "paras": [
                        "Biology organizes your body like a company: cells are the workers, tissues are teams of similar workers, organs are departments (a heart, a stomach), and organ systems are whole divisions. Eleven systems run the operation together, and not one of them could keep you alive alone.",
                        "The unifying job of all eleven is homeostasis — keeping conditions inside you stable: temperature near 98.6 degrees, steady blood sugar, balanced water and salts. Whenever you notice the body doing something odd like sweating, shivering or feeling thirsty, ask which internal condition it's trying to stabilize. That one question explains half of physiology.",
                    ],
                    "bullets": [
                        "Levels: cell → tissue → organ → organ system → organism",
                        "11 organ systems, each with a specialty, all interdependent",
                        "Homeostasis: keeping internal conditions stable — the body's master goal",
                        "Every odd body reaction (sweat, thirst, shiver) serves homeostasis",
                    ],
                },
                {
                    "h2": "The systems and their one-line jobs",
                    "paras": [
                        "Most biology tests ask you to match a system to its function, so memorize the one-liners. Circulatory: pumps blood to deliver oxygen and nutrients. Respiratory: brings in oxygen, removes carbon dioxide. Digestive: breaks food into molecules your cells can absorb. Nervous and endocrine: the body's fast (electrical) and slow (hormone) messaging systems.",
                        "The rest of the crew: skeletal for structure and blood-cell production, muscular for movement, integumentary (skin) as your barrier, immune/lymphatic for defense, excretory for filtering blood and balancing water, and reproductive for making the next generation. Group them by theme — transport, control, support, defense — and eleven systems shrink to four mental buckets.",
                    ],
                    "bullets": [
                        "Circulatory: transports oxygen, nutrients and waste via blood",
                        "Respiratory: gas exchange — O2 in, CO2 out",
                        "Digestive: breaks food into absorbable molecules",
                        "Nervous: rapid electrical signals; endocrine: slower hormone signals",
                        "Excretory: filters blood and balances water and salts",
                    ],
                },
                {
                    "h2": "Systems working together: trace the journey",
                    "paras": [
                        "The body's systems never work alone — every act is a collaboration. When you sprint, your muscular system demands energy, your respiratory system breathes faster to grab oxygen, your circulatory system races to deliver it, and your nervous system coordinates all of it while your skin sweats to dump heat.",
                        "Follow one bite of food to see the same teamwork: the digestive system breaks it down, the circulatory system carries the nutrients to cells, the endocrine system decides where they go, and the excretory system removes what's left. Trace-the-journey questions are test favorites precisely because they punish students who learned systems in isolation.",
                    ],
                    "bullets": [
                        "Exercise: muscle + respiratory + circulatory + nervous + skin, instantly coordinated",
                        "Digestion ends in your cells, not your stomach — every system plays a role",
                        "Practice journey stories: a bite of food, a breath of air",
                        "No system survives alone — that's why organ failures can chain",
                    ],
                    "example": {
                        "title": "Worked example: trace an oxygen molecule",
                        "body": "Air enters the nose and trachea (respiratory), diffuses into the blood at the lungs' tiny air sacs (respiratory), rides a red blood cell through arteries (circulatory), then diffuses into a muscle cell where mitochondria use it to make ATP (cellular level). Any journey question is just naming systems in the right order.",
                    },
                },
                {
                    "h2": "Memory tricks for all eleven",
                    "paras": [
                        "Eleven systems is a memory sprint, so compress them into four themed buckets: transport (circulatory, respiratory, digestive, excretory), control (nervous, endocrine), support and movement (skeletal, muscular, integumentary), and defense plus continuation (immune/lymphatic, reproductive). A few items per bucket is how memory actually works.",
                        "Then test yourself by organ, not by system: given 'kidneys,' name the system (excretory); given 'hormones,' name it (endocrine); given 'air sacs,' name it (respiratory). Organ-to-system recall is the direction tests usually ask, so drill that direction hardest.",
                    ],
                    "bullets": [
                        "Buckets: transport, control, support/movement, defense/continuation",
                        "Drill organ → system (kidneys → excretory) — the direction tests use",
                        "Link each system to one hero organ to anchor it",
                        "Explain one collaboration story out loud per study session",
                    ],
                },
            ],
            "key_concepts": [
                ("Tissue", "A group of similar cells working together, like muscle tissue or nerve tissue."),
                ("Organ", "A structure made of multiple tissues performing one job, like the heart."),
                ("Organ system", "A team of organs working together on one big function, like digestion."),
                ("Homeostasis", "The body's active maintenance of stable internal conditions — temperature, sugar, water."),
                ("Circulatory system", "Heart and vessels that transport oxygen, nutrients and wastes."),
                ("Respiratory system", "Airways and lungs that exchange oxygen for carbon dioxide."),
                ("Nervous system", "Brain, spinal cord and nerves sending fast electrical signals."),
                ("Endocrine system", "Glands releasing hormones — slower, longer-lasting chemical messages."),
            ],
            "study_tips": [
                "Learn systems as one-line jobs first; details attach easily to a job you already know.",
                "Make organ flashcards where the front is the organ (kidneys) and the back is the system.",
                "Tell one 'journey' story per session — oxygen from air to cell, food from bite to energy.",
                "Color-code a body diagram by system; visual anchoring beats list memorizing.",
                "Link every new fact to homeostasis — ask what stable condition this helps maintain.",
            ],
            "practice": [
                {
                    "q": "Which system delivers oxygen and nutrients to cells all over the body?",
                    "choices": ["Circulatory", "Respiratory", "Digestive", "Nervous"],
                    "answer": 0,
                    "explain": "The circulatory system is the delivery service: blood carries oxygen and nutrients to cells and hauls wastes away. Respiratory loads the oxygen, but circulatory ships it.",
                },
                {
                    "q": "The kidneys belong to which system?",
                    "choices": ["Digestive", "Endocrine", "Lymphatic", "Excretory"],
                    "answer": 3,
                    "explain": "Kidneys filter blood and balance water and salts — the excretory (urinary) system's job. People guess digestive because kidneys are near the stomach; location isn't membership.",
                },
                {
                    "q": "Which two systems are the body's main control and communication networks?",
                    "choices": ["Skeletal and muscular", "Nervous and endocrine", "Digestive and excretory", "Circulatory and respiratory"],
                    "answer": 1,
                    "explain": "Nervous = fast electrical messages; endocrine = slower chemical (hormone) messages. Together they run every other system — the body's text messages and mail service.",
                },
                {
                    "q": "Sweating when you overheat is an example of:",
                    "choices": ["Disease", "Digestion", "Homeostasis", "Cellular respiration"],
                    "answer": 2,
                    "explain": "Sweating cools you back toward your set temperature — the definition of homeostasis. Any 'body fixes a condition' scenario points to homeostasis.",
                },
            ],
            "flashcards": [
                ("Levels of body organization", "Cell → tissue → organ → organ system → organism."),
                ("What is homeostasis?", "Keeping internal conditions stable — temperature, blood sugar, water balance."),
                ("Circulatory system's job", "Pump blood to deliver oxygen and nutrients and remove wastes."),
                ("Respiratory system's job", "Bring in oxygen, expel carbon dioxide."),
                ("Digestive system's job", "Break food into molecules cells can absorb."),
                ("Nervous vs endocrine", "Nervous = fast electrical signals; endocrine = slower hormone signals."),
                ("Excretory system's job", "Filter blood and balance water and salts (kidneys lead)."),
                ("Skeletal system does two jobs", "Support/structure and making new blood cells."),
                ("Integumentary system", "Skin, hair and nails — the body's barrier and temperature regulator."),
                ("Which system makes hormones?", "The endocrine system (glands like the thyroid and adrenal)."),
            ],
            "faqs": [
                ("How many body systems are there?",
                 "Most textbooks count 11: circulatory, respiratory, digestive, nervous, endocrine, skeletal, muscular, integumentary, immune/lymphatic, excretory (urinary) and reproductive. Some books group them differently, so match your class's list."),
                ("What is homeostasis in simple terms?",
                 "Staying the same on the inside while the outside changes — like keeping 98.6 degrees whether it's freezing or scorching. It's the master job all eleven systems serve."),
                ("Which system is the most important?",
                 "It's a trick question — none survives alone. Remove the lungs and blood has no oxygen; remove the nervous system and nothing is coordinated. Test questions love 'how do systems interact' precisely because interdependence is the point."),
                ("What's the fastest way to learn the body systems?",
                 "One-line jobs first, then organ-to-system flashcards, then one trace-the-journey story per day. Three passes through that cycle over a week usually locks in the whole unit."),
            ],
            "paa": [
                ("What are the 11 body systems?", "Circulatory, respiratory, digestive, nervous, endocrine, skeletal, muscular, integumentary, immune/lymphatic, excretory and reproductive."),
                ("Which organs are in the circulatory system?", "The heart, blood and blood vessels (arteries, veins, capillaries) — a closed delivery loop for oxygen and nutrients."),
                ("How do the digestive and circulatory systems work together?", "Digestion breaks food into absorbable molecules; the circulatory system then carries those nutrients from the intestines to every cell."),
                ("Why does your heart beat faster when you exercise?", "Muscles demand more oxygen, so the nervous system signals the heart to pump faster — a homeostatic response to keep oxygen supply matched to demand."),
            ],
        },
        {
            "slug": "ecosystems",
            "title": "Ecosystems",
            "h1": "Ecosystems Explained: Food Webs, Energy Flow & Biomes",
            "meta_title": "Ecosystems and Food Webs Made Easy | StudyBonk",
            "meta_description": "Learn ecosystems free: food chains vs webs, trophic levels, the 10 percent rule and biomes — with flashcards, worked examples and a quiz. No sign-up.",
            "summary": "Food chains, food webs, the 10 percent rule and Earth's biomes — ecology that finally connects.",
            "keywords": [
                "ecosystems explained",
                "food chains and food webs",
                "trophic levels",
                "10 percent rule energy",
                "producers consumers decomposers",
                "types of biomes",
            ],
            "longtail": [
                "what is the difference between a food chain and a food web",
                "what is the 10 percent rule in ecosystems",
                "how does energy flow through an ecosystem",
                "producers consumers and decomposers explained",
                "what are trophic levels in a food chain",
                "what would happen without decomposers",
                "how to read a food web diagram",
                "what determines an area's biome",
                "difference between a biome and an ecosystem",
                "why are there few top predators in an ecosystem",
            ],
            "sections": [
                {
                    "h2": "What an ecosystem is",
                    "paras": [
                        "An ecosystem is every living thing in an area plus the nonliving parts it interacts with — sunlight, water, soil, temperature. A rotting log, a coral reef and the whole Amazon all qualify. The boundary is wherever ecologists decide the interactions are mostly internal.",
                        "Within any ecosystem, organisms sort into roles: producers make their own food (plants, algae), consumers eat other organisms, and decomposers break dead material back into nutrients. Every energy question in ecology comes back to who eats whom.",
                    ],
                    "bullets": [
                        "Ecosystem = living community + nonliving environment",
                        "Producers (autotrophs) make food; consumers (heterotrophs) eat it",
                        "Decomposers recycle dead matter into nutrients plants can reuse",
                        "Size doesn't matter — a puddle and a forest both count",
                    ],
                },
                {
                    "h2": "Food chains and food webs",
                    "paras": [
                        "A food chain is a simple one-way arrow: grass → grasshopper → frog → snake → hawk. Each arrow points to the eater. A food web is the honest version — the tangled map of who actually eats whom, since most animals eat more than one thing and get eaten by more than one thing.",
                        "Trophic levels are the chain's floors: producers at the bottom, then primary consumers (herbivores), secondary consumers, and apex predators on top. Vocabulary to keep straight: herbivores eat plants, carnivores eat animals, omnivores eat both, and decomposers clean up whatever dies. Draw a food web once using animals from your own neighborhood and the vocabulary locks in.",
                    ],
                    "bullets": [
                        "Arrows in a food chain point toward the eater",
                        "Food web = all the overlapping chains in an ecosystem",
                        "Trophic levels: producer → primary consumer → secondary consumer → apex",
                        "Herbivore: plants · carnivore: animals · omnivore: both",
                    ],
                },
                {
                    "h2": "Energy flow and the 10 percent rule",
                    "paras": [
                        "Here's the famous fact: only about 10% of the energy at one trophic level passes to the next — the rest is lost as heat, movement and waste. That's why food chains rarely exceed four or five levels, and why there are millions of grasshoppers but only a few hawks. Energy flows through ecosystems; it does not cycle.",
                        "The 10% rule turns into easy math questions. If producers hold 10,000 kcal of energy, primary consumers get about 1,000, secondary consumers about 100, and third-level consumers about 10. That's also why eating lower on the food chain — plants — supports so many more organisms than eating at the top.",
                    ],
                    "bullets": [
                        "Only about 10% of energy transfers up each trophic level",
                        "Lost energy leaves as heat, movement and waste",
                        "10,000 kcal of producers → 1,000 → 100 → 10 up the chain",
                        "Short chains exist because energy runs out fast",
                    ],
                    "example": {
                        "title": "Worked example: an energy pyramid question",
                        "body": "If a field's plants contain 5,000 kcal and cows eat them, the cows store about 500 kcal (10%). Humans eating the cows access about 50 kcal. If humans ate the plants directly, they'd reach the full 5,000 — that math is exactly why 'eating low on the food chain' can feed more people.",
                    },
                },
                {
                    "h2": "Biomes: Earth's major life zones",
                    "paras": [
                        "A biome is a large region defined by its climate and dominant vegetation — a life-zone template. The big land ones: tropical rainforest (hot, wet, most diverse), desert (very dry), grassland and savanna, temperate forest, taiga (cold conifer forest) and tundra (frozen, treeless). Aquatic biomes split into freshwater and marine, with coral reefs the most diverse water biome.",
                        "Two variables predict almost any biome: temperature and rainfall. Hot and wet gives rainforest; hot and dry gives desert; cold and dry gives tundra. When a test question describes a climate, translate it into those two numbers and the biome practically names itself.",
                    ],
                    "bullets": [
                        "Biome = large region shaped by climate plus dominant plants",
                        "Temperature and rainfall predict the biome almost every time",
                        "Rainforest: most diverse · tundra: coldest land · desert: driest",
                        "Aquatic biomes: freshwater vs marine (ocean)",
                    ],
                },
            ],
            "key_concepts": [
                ("Ecosystem", "A community of living things plus the nonliving environment they interact with."),
                ("Producer", "An organism that makes its own food — plants and algae; the base of every food chain."),
                ("Consumer", "An organism that eats other organisms for energy (herbivores, carnivores, omnivores)."),
                ("Decomposer", "An organism that breaks down dead matter, returning nutrients to the soil."),
                ("Food chain", "A single path of energy flow from producers to apex predators."),
                ("Food web", "All the interconnected food chains in an ecosystem."),
                ("Trophic level", "A feeding position in a food chain — producer, primary consumer, secondary consumer."),
                ("Biome", "A large region defined by climate and dominant vegetation, like desert or tundra."),
            ],
            "study_tips": [
                "Memorize one rule about arrows: they point toward the eater — half of all food web errors come from backwards arrows.",
                "Practice 10% math until dividing by 10 twice is automatic; those are guaranteed test points.",
                "Build a food web from animals you actually know (squirrels, hawks, grass) — familiar organisms make roles stick.",
                "Learn biomes as temperature + rainfall pairs, not as lists of species.",
                "Sketch the energy pyramid (producers wide, predators narrow) once from memory — the shape explains the rules.",
            ],
            "practice": [
                {
                    "q": "In the food chain grass → rabbit → fox, the rabbit is a:",
                    "choices": ["Producer", "Primary consumer", "Secondary consumer", "Decomposer"],
                    "answer": 1,
                    "explain": "The rabbit eats the producer (grass), making it a primary consumer (an herbivore). The fox, eating the rabbit, is the secondary consumer.",
                },
                {
                    "q": "A field's plants contain 20,000 kcal of energy. Roughly how much reaches second-level consumers?",
                    "choices": ["20,000 kcal", "2,000 kcal", "200 kcal", "20 kcal"],
                    "answer": 2,
                    "explain": "Each step keeps about 10%: 20,000 (producers) → 2,000 (primary consumers) → 200 kcal (secondary consumers). Two steps, two divisions by ten.",
                },
                {
                    "q": "Which organism returns nutrients to the soil by breaking down dead material?",
                    "choices": ["Decomposer", "Herbivore", "Producer", "Apex predator"],
                    "answer": 0,
                    "explain": "Decomposers (fungi and bacteria) recycle dead organisms into nutrients producers can absorb. Without them, nutrients would stay locked in dead material forever.",
                },
                {
                    "q": "A biome is hot year-round with very little rain. It is most likely a:",
                    "choices": ["Tropical rainforest", "Tundra", "Desert", "Temperate forest"],
                    "answer": 2,
                    "explain": "Hot + dry = desert. Tropical rainforests are hot but extremely wet, and tundra is cold and dry. Temperature plus rainfall names almost any biome.",
                },
            ],
            "flashcards": [
                ("What is an ecosystem?", "All living things in an area plus the nonliving parts (sunlight, water, soil) they interact with."),
                ("Producer vs consumer", "Producers make their own food; consumers must eat other organisms."),
                ("What do decomposers do?", "Break down dead material and recycle nutrients back to producers."),
                ("Food chain vs food web", "A chain is one path; a web is all the connected chains in an ecosystem."),
                ("Which way do food chain arrows point?", "Toward the eater — the direction energy flows."),
                ("What is a trophic level?", "A feeding position: producer, primary consumer, secondary consumer, and so on."),
                ("The 10 percent rule", "Only ~10% of energy passes to the next trophic level; the rest is lost as heat and waste."),
                ("Why are top predators rare?", "Energy shrinks 10x per level, so little energy is left at the top to support many predators."),
                ("What two factors determine a biome?", "Temperature and rainfall."),
                ("Example biome pairs", "Hot + wet = rainforest; hot + dry = desert; cold + dry = tundra."),
            ],
            "faqs": [
                ("What's the difference between a food chain and a food web?",
                 "A food chain follows one single path (grass → rabbit → fox). A food web shows all the connected chains in an ecosystem, because real animals eat and are eaten by many species. Chains are teaching tools; webs are reality."),
                ("Why are big predators so rare?",
                 "The 10 percent rule. Only about a tenth of the energy at each level makes it upward, so an ecosystem's top can support only a few predators. A million plants might feed thousands of deer that feed just dozens of wolves."),
                ("What's the difference between a biome and an ecosystem?",
                 "A biome is a huge region defined by climate and dominant plants (like a desert); an ecosystem is any community plus its environment, at any scale. A biome contains many ecosystems."),
                ("What would happen if decomposers disappeared?",
                 "Dead material would pile up and nutrients would never return to the soil, so producers would starve and the whole food web would collapse. Decomposers are the recycling department everything else depends on."),
            ],
            "paa": [
                ("What are the trophic levels of a food chain?", "Producers, then primary consumers (herbivores), secondary consumers, tertiary consumers, and apex predators — with decomposers working every level."),
                ("How much energy is lost between trophic levels?", "About 90% is lost at each step — as heat, movement and waste — leaving roughly 10% for the next level."),
                ("What is the most diverse land biome?", "The tropical rainforest: constant warmth and rainfall support more species than any other land biome."),
                ("What eats a hawk in a food web?", "Often nothing — hawks are frequently apex predators. When they die, decomposers break them down, returning their energy and nutrients to the system."),
            ],
        },
        {
            "slug": "mitosis-vs-meiosis",
            "title": "Mitosis vs Meiosis",
            "h1": "Mitosis vs Meiosis: The Differences, Finally Clear",
            "meta_title": "Mitosis vs Meiosis: Clear Comparison | StudyBonk",
            "meta_description": "Mitosis vs meiosis explained simply: PMAT stages, chromosome numbers and a side-by-side comparison. Free flashcards, quiz and worked examples. No sign-up.",
            "summary": "Two identical copies vs four unique gametes — the mitosis/meiosis comparison made permanent.",
            "keywords": [
                "mitosis vs meiosis",
                "stages of mitosis",
                "what is meiosis",
                "crossing over explained",
                "haploid vs diploid",
                "free biology quiz",
            ],
            "longtail": [
                "what is the difference between mitosis and meiosis",
                "how many cells does mitosis produce",
                "what happens in each stage of mitosis",
                "what is crossing over in meiosis",
                "why is meiosis important for genetic variation",
                "how many chromosomes in human gametes",
                "where does meiosis occur in the body",
                "is mitosis identical to the parent cell",
                "what does pmat stand for in cell division",
                "does meiosis happen twice as fast as mitosis",
            ],
            "sections": [
                {
                    "h2": "Why cells divide two different ways",
                    "paras": [
                        "Your body runs two separate division programs for two separate jobs. Mitosis makes new cells for growth and repair — replacing skin, healing cuts, growing taller. Meiosis makes sex cells (sperm and eggs), called gametes, and exists purely for reproduction.",
                        "The results are opposites. Mitosis: one cell splits into two identical cells with the same chromosome number as the parent. Meiosis: one cell splits twice into four cells, each with half the chromosomes — because sperm and egg combine at fertilization to restore the full count. Keep 'two for the body, four for the babies' in mind and the details fall into place.",
                    ],
                    "bullets": [
                        "Mitosis: growth and repair — makes new body cells",
                        "Meiosis: making gametes (sperm and egg) for reproduction",
                        "Mitosis → 2 identical cells; meiosis → 4 unique cells",
                        "Meiosis halves the chromosome number; fertilization restores it",
                    ],
                },
                {
                    "h2": "Mitosis: copy, line up, split",
                    "paras": [
                        "Mitosis has four named phases, PMAT: prophase (chromosomes condense and become visible), metaphase (they line up in the middle), anaphase (sister chromatids are pulled to opposite ends) and telophase (two new nuclei form). Cytokinesis then pinches the cell into two.",
                        "The outcome is clones: every resulting body cell has the exact same DNA as the original. That's what you want for repair — a skin cell should make another skin cell, not a surprise. Memorize PMAT as a story — get ready, line up, pull apart, rebuild — and sequence questions become free points.",
                    ],
                    "bullets": [
                        "PMAT: Prophase, Metaphase, Anaphase, Telophase",
                        "Metaphase = middle · anaphase = apart (matching first letters)",
                        "Cytokinesis: the actual splitting of the cell after PMAT",
                        "Result: 2 genetically identical diploid cells",
                    ],
                },
                {
                    "h2": "Meiosis: two splits, four gametes",
                    "paras": [
                        "Meiosis runs PMAT twice — meiosis I and meiosis II — turning one cell into four. The critical event happens early, in prophase I: crossing over, where matching chromosomes swap chunks of DNA. Combined with the random way chromosome pairs separate, that shuffling is why every gamete — and every sibling — is genetically unique.",
                        "Human body cells are diploid (46 chromosomes); meiosis produces haploid gametes with 23. When sperm meets egg, 23 + 23 = 46 again. Note that meiosis is not just mitosis done twice: the first division separates chromosome pairs, the second separates sister chromatids — different events with different outcomes.",
                    ],
                    "bullets": [
                        "Meiosis = PMAT twice (meiosis I and meiosis II)",
                        "Crossing over in prophase I swaps DNA between chromosome pairs",
                        "Result: 4 haploid cells (23 chromosomes each in humans), all unique",
                        "Fertilization restores the diploid number: 23 + 23 = 46",
                    ],
                    "example": {
                        "title": "Worked example: how many chromosomes?",
                        "body": "A human muscle cell has 46 chromosomes. After mitosis, each new cell has 46 — identical copies. After meiosis, each gamete has 23. If a horse's body cells have 64 chromosomes, its gametes have 32: halving is the rule, whatever the starting number.",
                    },
                },
                {
                    "h2": "The side-by-side comparison (test-ready)",
                    "paras": [
                        "The compare-and-contrast table is where the points live. Mitosis: one division, 2 cells, identical, diploid, body cells, growth and repair. Meiosis: two divisions, 4 cells, unique, haploid, gametes only, reproduction. If a question mentions genetic variation, the answer is meiosis — full stop.",
                        "Watch for the traps. Crossing over and haploid results belong only to meiosis. 'Identical daughter cells' belongs only to mitosis. And meiosis happens in special locations (ovaries and testes in animals), while mitosis happens almost anywhere you have cells. Anchor each keyword to one process and you can't be tricked.",
                    ],
                    "bullets": [
                        "Mitosis: 1 division · 2 cells · identical · diploid · growth/repair",
                        "Meiosis: 2 divisions · 4 cells · unique · haploid · gametes",
                        "Keywords 'variation,' 'crossing over,' 'gamete' → meiosis",
                        "Keywords 'identical,' 'repair,' 'clone' → mitosis",
                    ],
                },
            ],
            "key_concepts": [
                ("Mitosis", "Cell division producing two genetically identical diploid cells for growth and repair."),
                ("Meiosis", "Cell division producing four genetically unique haploid gametes for reproduction."),
                ("Chromosome", "A coiled package of DNA; humans have 46 in each body cell."),
                ("Diploid", "Full chromosome number (46 in humans) — two complete sets, one from each parent."),
                ("Haploid", "Half the chromosome number (23 in humans) — one set, found in gametes."),
                ("Gamete", "A sex cell (sperm or egg), haploid, that combines at fertilization."),
                ("Crossing over", "The swap of DNA segments between chromosome pairs in prophase I of meiosis."),
                ("Cytokinesis", "The final splitting of the cell cytoplasm into two separate cells."),
            ],
            "study_tips": [
                "Anchor the slogan first: 'two identical for the body, four unique for the babies.'",
                "Learn PMAT as a story (ready, middle, apart, rebuild), then run the order forwards and backwards.",
                "Make a two-column comparison table and quiz yourself by covering one column at a time.",
                "For any question, scan for trigger words: variation or gamete means meiosis; repair or clone means mitosis.",
                "Use the flashcard deck daily for a week — this topic is pure recognition speed on tests.",
            ],
            "practice": [
                {
                    "q": "Mitosis produces:",
                    "choices": ["2 identical diploid cells", "4 unique haploid cells", "2 unique haploid cells", "4 identical diploid cells"],
                    "answer": 0,
                    "explain": "One division, two cells, each identical to the parent with the full chromosome count. 'Four unique cells' is meiosis — the classic look-alike answer.",
                },
                {
                    "q": "Crossing over occurs during:",
                    "choices": ["Mitosis", "Cytokinesis", "Prophase I of meiosis", "Interphase"],
                    "answer": 2,
                    "explain": "In prophase I, matching chromosomes pair up and swap segments — a major source of genetic variation. Mitosis never does this; that's why its products are identical.",
                },
                {
                    "q": "A human sperm cell contains how many chromosomes?",
                    "choices": ["46", "92", "12", "23"],
                    "answer": 3,
                    "explain": "Sperm are haploid: half the body's 46, which is 23. Fertilization adds the egg's 23 to restore 46 in the zygote.",
                },
                {
                    "q": "Which process heals a cut on your hand?",
                    "choices": ["Meiosis", "Mitosis", "Fertilization", "Crossing over"],
                    "answer": 1,
                    "explain": "Repair calls for identical replacement cells — mitosis. Trigger words: repair, growth, clone = mitosis; gametes, variation = meiosis.",
                },
            ],
            "flashcards": [
                ("What does PMAT stand for?", "Prophase, Metaphase, Anaphase, Telophase — the four phases of mitosis."),
                ("Purpose of mitosis", "Growth and repair: making identical new body cells."),
                ("Purpose of meiosis", "Making gametes (sperm and eggs) for sexual reproduction."),
                ("Mitosis vs meiosis: number of cells", "Mitosis makes 2 identical cells; meiosis makes 4 unique cells."),
                ("What is crossing over?", "Chromosome pairs swapping DNA segments in prophase I of meiosis — a big source of variation."),
                ("Diploid vs haploid (humans)", "Diploid = 46 chromosomes (body cells); haploid = 23 (gametes)."),
                ("Where does meiosis occur in animals?", "Ovaries and testes — wherever gametes are made."),
                ("What is cytokinesis?", "The final split of the cytoplasm that separates the new cells."),
                ("Fertilization chromosome math", "Haploid (23) + haploid (23) = diploid (46) in the zygote."),
                ("Which process creates genetic variation?", "Meiosis — through crossing over and the random separation of chromosome pairs."),
            ],
            "faqs": [
                ("What is the main difference between mitosis and meiosis?",
                 "Mitosis makes two identical body cells with the full chromosome number for growth and repair. Meiosis makes four unique gametes with half the number for reproduction. Identical vs unique is the fastest test: identical = mitosis, unique = meiosis."),
                ("Is meiosis just mitosis twice?",
                 "No — the two divisions are different events. Meiosis I separates chromosome pairs (and includes crossing over); meiosis II separates sister chromatids, like mitosis does. That's why the result is four halved, shuffled cells rather than four clones."),
                ("Why does meiosis matter for variation?",
                 "Crossing over mixes DNA between chromosomes, and each pair separates randomly. Every gamete gets a unique combination — which is why siblings (except identical twins) are genetically different from each other and from their parents."),
                ("How can I remember the phases of mitosis?",
                 "PMAT as a story: prophase gets ready (chromosomes appear), metaphase meets in the middle, anaphase pulls apart, telophase rebuilds two nuclei. Two mnemonics inside: metaphase-middle and anaphase-apart."),
            ],
            "paa": [
                ("How many cells result from meiosis?", "Four haploid cells, each genetically unique — versus two identical cells from mitosis."),
                ("What happens during crossing over?", "Paired chromosomes swap segments of DNA during prophase I, mixing genes so each gamete carries a brand-new combination."),
                ("Where does mitosis occur in the body?", "Almost everywhere — skin, blood, bones, healing wounds. Any tissue that grows or repairs itself is running mitosis."),
                ("Can a human cell have 23 chromosomes?", "Yes — gametes (sperm and egg) do. That haploid number is the whole point of meiosis: halve now so fertilization can restore 46."),
            ],
        },
    ],
}
