"""Math pillar: 1 pillar page + 6 cluster pages.

Schema (must match exactly — see docs/CONTENT.md):
PILLAR = {slug, title, emoji, meta_title<=60, meta_description<=155, h1,
tagline, summary, keywords[], longtail[10+], intro[paras], bullets[],
faqs[(q,a)x5], paa[(q,a)x5], clusters[{slug, title, h1, meta_title,
meta_description, summary, keywords[], longtail[10-20],
sections[{h2, paras[], bullets[], example?{title, body}}],
key_concepts[(term,def)x6-8], study_tips[x4-6],
practice[{q, choices[4], answer(idx), explain}]x3-4,
flashcards[(front,back)]x8-10, faqs[(q,a)x3-4], paa[(q,a)x4]}]}
"""

PILLAR = {
    "slug": "math",
    "title": "Math",
    "emoji": "➗",
    "meta_title": "Free Math Study Hub — Learn Math Fast | StudyBonk",
    "meta_description": "Free math study guides, flashcards and quizzes: algebra, geometry, trig and word problems. No sign-up, gamified, 100% private. Start bonking math today.",
    "h1": "Free Math Study Hub: Learn Math Fast, One Bonk at a Time",
    "tagline": "From fractions to trigonometry — free guides, decks and quizzes that make math finally click.",
    "summary": "Free math guides, flashcard decks and practice quizzes for algebra, geometry, trig and more.",
    "keywords": [
        "math help",
        "learn math online free",
        "math flashcards",
        "math practice questions",
        "algebra help",
        "geometry basics",
        "trigonometry for beginners",
        "free study app",
        "study tool",
        "learn fast",
    ],
    "longtail": [
        "how to study math effectively for exams",
        "best free website to learn math step by step",
        "why do I keep making careless mistakes in math",
        "how to get better at algebra fast",
        "free math practice questions with explanations",
        "how to memorize math formulas without flashcards",
        "easiest way to learn trigonometry for beginners",
        "how to solve word problems step by step",
        "math study plan for high school students",
        "how to catch up in math when you're behind",
        "free privacy-focused math study app with no ads",
        "how long should I study math each day",
    ],
    "intro": [
        "Math isn't a talent — it's a skill you build rep by rep, like XP in a game. The problem is that most math resources either drown you in theory or throw problems at you with no explanation. StudyBonk splits the difference: short, plain-English lessons, flashcard decks that drill the concepts, and quizzes that explain every answer.",
        "Every page below is 100% free, works without an account, and saves your progress right in your browser. Earn XP and keep your streak alive while you turn your weakest topic into your strongest.",
    ],
    "bullets": [
        "Master algebra basics: variables, expressions and equations",
        "Convert fractions, decimals and percents in your head",
        "Crack geometry: angles, triangles, area and volume",
        "Understand trigonometry with SOH-CAH-TOA made simple",
        "Graph linear equations without fear",
        "Attack word problems with a repeatable strategy",
    ],
    "faqs": [
        ("Is StudyBonk good for learning math?",
         "Yes. StudyBonk gives you short lessons, flashcard decks with spaced repetition and practice quizzes with explanations for core math topics from pre-algebra through trigonometry. It's free, requires no account, and works offline after the first load."),
        ("How much should I study math per day?",
         "Most students see real progress with 20–30 focused minutes a day. Consistency beats marathons: daily practice moves formulas from short-term into long-term memory. StudyBonk's focus timer and daily quests are built around exactly that dose."),
        ("Does StudyBonk replace my textbook or teacher?",
         "No — and it doesn't try to. Use StudyBonk to preview topics before class, drill definitions with flashcards, and practice with instant feedback. Your teacher handles the depth; StudyBonk handles the reps."),
        ("Can I use StudyBonk math offline?",
         "Yes. After your first visit, StudyBonk is cached by your browser and works offline — including flashcards, quizzes and the AI tutor. Your progress is stored locally on your device."),
        ("Is StudyBonk really free with no account?",
         "Really free, really no account. No ads, no paywalls, no email capture, no tracking. Everything saves in your browser's local storage, and the code is open-source on GitHub so you can verify all of this yourself."),
    ],
    "paa": [
        ("What is the fastest way to learn math?",
         "Short daily practice with active recall: read a concept once, then immediately self-test with flashcards and quizzes instead of re-reading. StudyBonk automates that loop for you."),
        ("Why is math so hard for me?",
         "Usually because earlier gaps make later topics feel like a foreign language. Diagnose with a quiz, fix the weakest prerequisite first, and rebuild from there."),
        ("How do I stop making silly mistakes in math?",
         "Slow down on the setup, write every step, and check units/signs at the end. Careless errors come from working memory overload, not lack of knowledge."),
        ("Can you learn math as an adult?",
         "Absolutely. Adults often learn math faster because they have real motivation and better metacognition. 20 focused minutes a day with immediate feedback works at any age."),
        ("What order should I learn math topics in?",
         "Fractions/decimals → algebra basics → linear equations → geometry → word problems → trigonometry. Each rung makes the next one easier."),
    ],
    "clusters": [
        {
            "slug": "algebra-basics",
            "title": "Algebra Basics",
            "h1": "Algebra Basics Made Easy: Variables, Expressions & Equations",
            "meta_title": "Algebra Basics Made Easy — Free Guide | StudyBonk",
            "meta_description": "Learn algebra basics free: variables, expressions, like terms and solving equations step by step. Flashcards, quiz and worked examples. No sign-up.",
            "summary": "Variables, expressions, like terms and your first equations — explained like a friend, not a textbook.",
            "keywords": [
                "algebra basics",
                "learn algebra free",
                "variables and expressions",
                "solving equations",
                "combining like terms",
                "algebra help for beginners",
            ],
            "longtail": [
                "how to understand algebra for beginners",
                "what is a variable in algebra explained simply",
                "how to combine like terms step by step",
                "why do we do the same thing to both sides of an equation",
                "how to solve two step equations easily",
                "common algebra mistakes beginners make",
                "how to get better at algebra fast",
                "free algebra practice problems with explanations",
                "algebra 1 study guide for struggling students",
                "how long does it take to learn basic algebra",
            ],
            "sections": [
                {
                    "h2": "What algebra actually is (in one breath)",
                    "paras": [
                        "Algebra is just arithmetic with mystery boxes. Instead of writing 3 + 4 = 7, algebra writes 3 + x = 7 and asks: what's hiding in the box? That mystery box — the variable — is the entire foundation. Everything else in algebra, from basic equations to calculus, is a system of rules for figuring out what's in boxes.",
                        "If arithmetic gave you tools for calculating things you can see, algebra gives you tools for finding things you can't. That's why it feels weird at first: you're trading numbers you know for symbols you don't. Trust the process — the payoff is that one equation like d = rt suddenly solves a thousand road-trip problems at once.",
                    ],
                    "bullets": [
                        "Variable: a symbol (like x) that stands for an unknown value",
                        "Expression: a math phrase like 3x + 2 (no equals sign)",
                        "Equation: a math sentence like 3x + 2 = 11 (has an equals sign)",
                        "Coefficient: the number in front of a variable, like the 3 in 3x",
                        "Term: a piece separated by + or −, like 3x and 2",
                    ],
                },
                {
                    "h2": "Combining like terms: the first real skill",
                    "paras": [
                        "Before you can solve anything, you must simplify. The rule is simple: only terms with the exact same variable part can combine. Apples with apples, x's with x's. 3x + 5x becomes 8x because they're both x-terms. But 3x + 5 cannot be combined — one term has a variable, one doesn't. It stays 3x + 5, and that's a complete answer.",
                        "The classic mistake is sign errors: in 4x − 7 + 2x − 3, the −7 and −3 both travel with minus signs. Combine to get 6x − 10. Write out every step for your first few weeks of algebra — the steps are cheap, the mistakes are expensive.",
                    ],
                    "bullets": [
                        "3x + 5x = 8x ✓ (same variable part)",
                        "3x + 5 stays as is ✗ (can't mix with plain numbers)",
                        "4x − 7 + 2x − 3 = 6x − 10 (watch the signs!)",
                        "x² + x can NOT combine — x² and x are different animals",
                    ],
                    "example": {
                        "title": "Worked example: simplify 5y + 3 − 2y + 8",
                        "body": "Group the y-terms: 5y − 2y = 3y. Group the numbers: 3 + 8 = 11. Answer: 3y + 11. Notice we kept the minus attached to the 2y when grouping — that's the step where 90% of errors happen.",
                    },
                },
                {
                    "h2": "Solving equations: the golden rule",
                    "paras": [
                        "An equation is a balanced scale. The golden rule: whatever you do to one side, you do to the other. Keep the scale balanced and the equals sign stays true. Your entire job when solving is to peel operations off the variable, one layer at a time, in reverse order of operations.",
                        "For a two-step equation like 3x + 2 = 11: first undo the +2 by subtracting 2 from both sides (3x = 9), then undo the ×3 by dividing both sides by 3 (x = 3). Undo addition/subtraction before multiplication/division when the multiplying is directly attached to the variable. Always check by plugging your answer back in: 3(3) + 2 = 11. ✓",
                    ],
                    "bullets": [
                        "Peel operations in reverse PEMDAS order: +/− first, then ×/÷",
                        "Whatever you do to one side, do to the other",
                        "Always check: substitute your answer back into the original",
                        "A negative in front of the variable: −x = 5 means x = −5",
                    ],
                    "example": {
                        "title": "Worked example: solve 4x − 5 = 19",
                        "body": "Add 5 to both sides: 4x = 24. Divide both sides by 4: x = 6. Check: 4(6) − 5 = 24 − 5 = 19 ✓.",
                    },
                },
                {
                    "h2": "Your algebra study plan",
                    "paras": [
                        "Learn algebra in layers, never in one sitting. Read one concept, immediately drill it with flashcards, then prove it to yourself with a quiz. When you get a question wrong, read the explanation, wait a few minutes, and try again. That struggle-then-retry loop is what moves knowledge into long-term memory — StudyBonk's spaced repetition schedules it for you automatically.",
                    ],
                    "bullets": [
                        "Day 1–2: vocabulary (variable, term, coefficient) + like terms",
                        "Day 3–4: one-step equations until they're boring",
                        "Day 5–7: two-step equations + checking answers",
                        "Every day: 10 minutes of flashcards + 1 quiz to keep the streak alive",
                    ],
                },
            ],
            "key_concepts": [
                ("Variable", "A symbol, usually a letter, representing an unknown or changing value."),
                ("Expression", "A combination of numbers and variables (2x + 3) with no equals sign."),
                ("Equation", "A statement that two expressions are equal (2x + 3 = 7)."),
                ("Coefficient", "The number multiplying a variable — in 5x, the coefficient is 5."),
                ("Like terms", "Terms with identical variable parts (7x and −2x); only these can be combined."),
                ("Inverse operation", "The operation that undoes another: +/− and ×/÷ are inverse pairs."),
                ("Solution", "The value of the variable that makes the equation true."),
                ("Distributive property", "a(b + c) = ab + ac — multiply everything inside the parentheses."),
            ],
            "study_tips": [
                "Write every step, even the obvious ones — algebra errors live in skipped steps.",
                "Say the golden rule out loud each time you solve: 'both sides, always both sides.'",
                "Check every solution by substituting it back — catching your own errors builds self-correction.",
                "Use the flashcard deck below daily; recognizing vocabulary instantly makes lessons twice as fast.",
                "If you're stuck on two-step equations, drop back to one-step drills for a day. Gaps compound.",
            ],
            "practice": [
                {
                    "q": "Simplify: 7x + 4 − 3x",
                    "choices": ["4x + 4", "10x + 4", "4x − 4", "7x + 1"],
                    "answer": 0,
                    "explain": "Combine the like terms 7x and −3x to get 4x. The +4 has no variable, so it stays: 4x + 4.",
                },
                {
                    "q": "Solve for x: 2x + 6 = 14",
                    "choices": ["x = 4", "x = 10", "x = 3", "x = 8"],
                    "answer": 0,
                    "explain": "Subtract 6 from both sides: 2x = 8. Divide both sides by 2: x = 4. Check: 2(4) + 6 = 14 ✓.",
                },
                {
                    "q": "In the expression 5y − 3, what is the coefficient?",
                    "choices": ["5", "y", "−3", "2"],
                    "answer": 0,
                    "explain": "The coefficient is the number attached to the variable: 5 in 5y.",
                },
                {
                    "q": "Which pair are like terms?",
                    "choices": ["3x and 3x²", "4a and 4b", "−2x and 9x", "5 and 5x"],
                    "answer": 2,
                    "explain": "Like terms need identical variable parts. −2x and 9x are both x-to-the-first-power terms, so they combine to 7x.",
                },
            ],
            "flashcards": [
                ("What is a variable?", "A symbol (like x) representing an unknown value — a mystery box to be solved for."),
                ("Expression vs equation?", "Expression = phrase (3x + 2), no equals sign. Equation = sentence (3x + 2 = 11), has an equals sign."),
                ("What are like terms?", "Terms with the exact same variable part, like 7x and −2x. Only like terms can combine."),
                ("What is a coefficient?", "The number multiplying the variable — 5 in '5y'."),
                ("Golden rule of equations?", "Whatever you do to one side, do to the other. A balanced scale stays balanced."),
                ("Simplify: 4x − 7 + 2x − 3", "6x − 10 (combine x-terms, then numbers, keeping signs attached)."),
                ("First step to solve 3x + 5 = 20?", "Subtract 5 from both sides → 3x = 15."),
                ("What does the distributive property say?", "a(b + c) = ab + ac — multiply each term inside the parentheses."),
                ("How do you check a solution?", "Substitute it back into the original equation — both sides must match."),
                ("Solve: −x = 5", "x = −5 (divide both sides by −1)."),
            ],
            "faqs": [
                ("How long does it take to learn basic algebra?",
                 "With 20–30 minutes of daily practice, most students get comfortable with algebra basics (like terms through two-step equations) in 2–4 weeks. Consistency matters far more than session length — daily short practice with active recall beats weekend marathons."),
                ("Why do we do the same operation to both sides?",
                 "The equals sign means the two sides are the same value — a balanced scale. Doing the same thing to both sides keeps them equal while isolating the variable. Do something to only one side and you've changed the problem."),
                ("What's the most common algebra mistake?",
                 "Sign errors when combining terms or moving terms across the equals sign. The fix is mechanical: write every step and keep the sign attached to its term, like −3 traveling with its minus."),
                ("Can I learn algebra on my own without a teacher?",
                 "Yes, especially the fundamentals. Use short lessons plus immediate self-testing (flashcards + quizzes with explanations), and let a teacher, tutor or AI tutor unstick you on the two or three concepts that won't click."),
            ],
            "paa": [
                ("What is algebra in simple words?", "Arithmetic with mystery boxes: using symbols for unknown numbers and finding rules to figure out what's inside."),
                ("What should I learn first in algebra?", "Vocabulary (variable, term, coefficient), then combining like terms, then one-step equations. Everything after builds on these."),
                ("Is algebra hard to learn?", "It's different, not hard — it feels abstract at first. Daily practice with instant feedback makes it click within weeks."),
                ("How is algebra used in real life?", "Whenever you work backwards from a known result: total cost, distance/time, recipe scaling, figuring out what grade you need on the final."),
            ],
        },
        {
            "slug": "fractions-decimals-percents",
            "title": "Fractions, Decimals & Percents",
            "h1": "Fractions, Decimals & Percents: Conquer the Conversion Trio",
            "meta_title": "Fractions, Decimals & Percents Made Easy | StudyBonk",
            "meta_description": "Master fractions, decimals and percents free: conversion tricks, common mistakes and practice quizzes. Gamified, private, no sign-up needed.",
            "summary": "Convert between the big three instantly and finally understand what a fraction actually means.",
            "keywords": [
                "fractions help",
                "decimal to percent",
                "fraction to decimal",
                "percent problems",
                "converting fractions",
                "free math practice",
            ],
            "longtail": [
                "how to convert fractions to decimals step by step",
                "easy trick to convert decimals to percents",
                "why do you flip the second fraction when dividing",
                "how to add fractions with different denominators",
                "how to find percent of a number quickly",
                "common fraction decimal percent conversions to memorize",
                "how to simplify fractions the easy way",
                "what is 0.75 as a fraction and percent",
                "how to order fractions from least to greatest",
                "real life uses of fractions decimals and percents",
            ],
            "sections": [
                {
                    "h2": "One idea, three costumes",
                    "paras": [
                        "A fraction, a decimal and a percent are three ways of wearing the same number. One-half, 0.5 and 50% are identical quantities in different outfits. Once you truly believe that, conversions stop being magic tricks and become obvious moves.",
                        "The bridge between all three is place value and powers of ten. Fraction to decimal: divide the top by the bottom (1 ÷ 4 = 0.25). Decimal to percent: multiply by 100, or just slide the decimal point two places right (0.25 → 25%). Percent back to decimal: slide two places left (7% → 0.07).",
                    ],
                    "bullets": [
                        "1/2 = 0.5 = 50% — same number, three costumes",
                        "Fraction → decimal: divide numerator by denominator",
                        "Decimal → percent: move the decimal point 2 places right",
                        "Percent → decimal: move the decimal point 2 places left",
                        "Decimal → fraction: use place value (0.7 = 7/10)",
                    ],
                },
                {
                    "h2": "Working with fractions without fear",
                    "paras": [
                        "Fractions only follow two big rules. Rule one: you can only add or subtract when the denominators (bottoms) match — find a common denominator first. Rule two: you can always multiply straight across, top times top, bottom times bottom, no matching needed.",
                        "Division uses the famous 'keep, change, flip': keep the first fraction, change ÷ to ×, flip the second fraction upside down. It works because dividing by a fraction means asking 'how many of these fit in that?' And always simplify your final answer by dividing out common factors — 8/12 isn't finished until it's 2/3.",
                    ],
                    "bullets": [
                        "Adding: common denominator first, then add tops only",
                        "Multiplying: straight across, then simplify",
                        "Dividing: keep, change, flip — then multiply",
                        "Simplify by dividing top and bottom by the same number",
                        "Mixed numbers: convert to improper fractions before computing",
                    ],
                    "example": {
                        "title": "Worked example: 2/3 + 1/4",
                        "body": "Common denominator is 12. Rewrite: 2/3 = 8/12 and 1/4 = 3/12. Add the tops: 8/12 + 3/12 = 11/12. No simplification needed — 11 and 12 share no factors.",
                    },
                },
                {
                    "h2": "Percents: the real-world champion",
                    "paras": [
                        "Percents show up everywhere money goes: tips, discounts, tax, interest, test scores. The key insight is that 'percent' literally means 'per hundred,' so 25% is just 25/100 = 0.25. Finding 25% of 80 becomes 0.25 × 80 = 20.",
                        "Learn your benchmark fractions cold and mental math transforms: 1/2 = 50%, 1/4 = 25%, 1/5 = 20%, 1/10 = 10%, 1/3 ≈ 33.3%. To tip 20%, move the decimal on the bill one place left and double it. To take 10% off, move the decimal one left and subtract. Percent power is estimation power.",
                    ],
                    "bullets": [
                        "Percent means 'per hundred' — 25% = 25/100 = 0.25",
                        "Find percent OF a number: convert to decimal, multiply",
                        "20% tip trick: 10% (move decimal left) × 2",
                        "Discount: original × (1 − percent as decimal)",
                        "Memorize: 1/2=50%, 1/4=25%, 1/5=20%, 1/10=10%",
                    ],
                },
            ],
            "key_concepts": [
                ("Numerator", "The top of a fraction — how many parts you have."),
                ("Denominator", "The bottom of a fraction — how many parts the whole is split into."),
                ("Common denominator", "A shared bottom number that lets fractions be added or subtracted."),
                ("Improper fraction", "A fraction where the top ≥ bottom, like 7/4 (same as mixed number 1 3/4)."),
                ("Percent", "A fraction with denominator 100; 'per cent' literally means per hundred."),
                ("Simplify", "Divide top and bottom by their greatest common factor until they share none."),
                ("Repeating decimal", "A decimal that repeats forever, like 1/3 = 0.333… (written 0.3̄)."),
                ("Benchmark fractions", "Common fractions (1/2, 1/4, 1/3, 1/5, 1/10) worth knowing as decimals/percents cold."),
            ],
            "study_tips": [
                "Memorize the benchmark conversions (1/2, 1/3, 1/4, 1/5, 1/8, 1/10) — they power all mental math.",
                "When a fraction problem confuses you, convert everything to decimals; often it becomes obvious.",
                "Draw a rectangle and shade it — visual fraction sense beats rules for beginners.",
                "Drill conversions with the flashcard deck until 3-second recall, then let spaced repetition maintain it.",
            ],
            "practice": [
                {
                    "q": "What is 3/4 as a percent?",
                    "choices": ["34%", "75%", "43%", "0.75%"],
                    "answer": 1,
                    "explain": "3 ÷ 4 = 0.75, and 0.75 as a percent is 75%. (Or: 3/4 × 100/1 = 300/4 = 75.)",
                },
                {
                    "q": "Calculate: 2/3 + 1/6",
                    "choices": ["3/9", "5/6", "3/6", "2/9"],
                    "answer": 1,
                    "explain": "Common denominator 6: 2/3 = 4/6. Then 4/6 + 1/6 = 5/6.",
                },
                {
                    "q": "A $40 shirt is 25% off. What's the sale price?",
                    "choices": ["$35", "$30", "$25", "$32"],
                    "answer": 1,
                    "explain": "25% of 40 = 0.25 × 40 = $10 off. Sale price = 40 − 10 = $30. (Shortcut: 25% off means you pay 75%: 0.75 × 40 = 30.)",
                },
                {
                    "q": "Divide: 1/2 ÷ 1/4",
                    "choices": ["1/8", "2", "1/2", "3/4"],
                    "answer": 1,
                    "explain": "Keep, change, flip: 1/2 × 4/1 = 4/2 = 2. Makes sense: two quarters fit in a half.",
                },
            ],
            "flashcards": [
                ("1/2 as decimal and percent", "0.5 = 50%"),
                ("1/4 as decimal and percent", "0.25 = 25%"),
                ("1/3 as decimal and percent", "0.333… ≈ 33.3%"),
                ("1/5 as decimal and percent", "0.2 = 20%"),
                ("1/8 as decimal and percent", "0.125 = 12.5%"),
                ("Fraction → decimal method", "Divide numerator by denominator (top ÷ bottom)."),
                ("Decimal → percent method", "Move decimal point 2 places right (0.07 → 7%)."),
                ("Rule for adding fractions", "Common denominator first, then add numerators only."),
                ("Keep, change, flip", "Fraction division: keep first, change ÷ to ×, flip the second fraction."),
                ("What does percent mean?", "'Per hundred' — 25% = 25 out of every 100 = 0.25."),
            ],
            "faqs": [
                ("Why do you flip and multiply when dividing fractions?",
                 "Dividing by a fraction asks 'how many of these fit into that?' Mathematically, dividing by 2/3 is the same as multiplying by 3/2 (its reciprocal). Keep–change–flip is just a shortcut for multiplying by the reciprocal."),
                ("How do I add fractions with different denominators?",
                 "Find the least common denominator, rewrite both fractions with it, then add the numerators. Example: 1/3 + 1/4 → 4/12 + 3/12 = 7/12."),
                ("What's the fastest way to calculate a tip?",
                 "For 20%: move the bill's decimal one place left (that's 10%) and double it. For 15%: take 10%, add half of that. No calculator needed."),
                ("Is 0.75 the same as 75%?",
                 "Yes — and the same as 3/4. Fraction, decimal and percent are three notations for one number; converting between them is just re-labeling."),
            ],
            "paa": [
                ("How do you convert a fraction to a decimal without a calculator?", "Divide top by bottom using long division: 3 ÷ 8 = 0.375. For benchmarks like halves and quarters, memorize them instead."),
                ("What is 1/3 as a percent?", "33.3̄% — the 3 repeats forever because 3 never divides evenly into 10-powers."),
                ("How do you simplify a fraction?", "Divide the top and bottom by their biggest shared factor: 8/12 → divide both by 4 → 2/3."),
                ("Which is bigger: 3/5 or 7/12?", "Convert: 3/5 = 0.6 and 7/12 ≈ 0.583. So 3/5 wins. Decimal conversion makes comparisons instant."),
            ],
        },
        {
            "slug": "geometry-fundamentals",
            "title": "Geometry Fundamentals",
            "h1": "Geometry Fundamentals: Angles, Triangles, Area & Volume",
            "meta_title": "Geometry Fundamentals Explained Simply | StudyBonk",
            "meta_description": "Free geometry guide: angles, triangles, the Pythagorean theorem, area and volume formulas with worked examples, flashcards and a quiz. No sign-up.",
            "summary": "Angles, triangles, Pythagoras, area and volume — the geometry toolkit with formulas that finally stick.",
            "keywords": [
                "geometry help",
                "pythagorean theorem",
                "area and perimeter",
                "angles and triangles",
                "geometry formulas",
                "free geometry practice",
            ],
            "longtail": [
                "how to find missing angles in a triangle",
                "pythagorean theorem explained for beginners",
                "how to remember area and perimeter formulas",
                "difference between area and perimeter in simple terms",
                "how to find the area of a circle step by step",
                "types of triangles and their properties",
                "how many degrees in a triangle and why",
                "volume formulas for common 3d shapes",
                "geometry study tips for visual learners",
                "how to use the distance formula in geometry",
            ],
            "sections": [
                {
                    "h2": "Angles: the atoms of geometry",
                    "paras": [
                        "Every geometry structure is built from angles, so learn the vocabulary first. An angle measures rotation between two rays, in degrees. A full turn is 360°, a half turn is 180°, a quarter turn is 90°. Angles under 90° are acute, over 90° are obtuse, and exactly 180° ones are straight.",
                        "Two rules unlock most angle problems. When two lines cross, opposite angles are equal (vertical angles). When angles form a straight line, they sum to 180° (supplementary). Parallel lines add a third: corresponding angles are equal, which is why a transversal creates matching angle patterns like railroad ties.",
                    ],
                    "bullets": [
                        "Acute < 90° · Right = 90° · Obtuse > 90° · Straight = 180°",
                        "Vertical angles (across a crossing) are always equal",
                        "Angles on a straight line sum to 180°",
                        "Angles in a triangle sum to 180° — the most used rule in geometry",
                        "Angles in a quadrilateral sum to 360°",
                    ],
                },
                {
                    "h2": "Triangles and the Pythagorean theorem",
                    "paras": [
                        "Triangles are geometry's favorite shape because they're the only rigid polygon — and their angle sum of exactly 180° powers endless problems. Know the families: equilateral (all sides equal, all angles 60°), isosceles (two sides equal, two angles equal), scalene (nothing equal), and right triangles (one 90° angle, home of Pythagoras).",
                        "The Pythagorean theorem says that in a right triangle, a² + b² = c², where c is the hypotenuse (the side across from the right angle, always the longest). It converts shape knowledge into number knowledge: know any two sides, find the third. The famous 3-4-5 triangle checks out: 9 + 16 = 25.",
                    ],
                    "bullets": [
                        "Equilateral: all equal · Isosceles: two equal · Scalene: none equal",
                        "Right triangle: one 90° angle; the side opposite is the hypotenuse",
                        "Pythagorean theorem: a² + b² = c² (right triangles only!)",
                        "Pythagorean triples to know: 3-4-5, 5-12-13, 8-15-17",
                        "Hypotenuse is always the longest side — sanity-check your answer",
                    ],
                    "example": {
                        "title": "Worked example: legs of 6 and 8 — hypotenuse?",
                        "body": "a² + b² = c² → 36 + 64 = 100 → c² = 100 → c = 10. It's the 3-4-5 triangle scaled by 2. Spotting scaled triples saves minutes on tests.",
                    },
                },
                {
                    "h2": "Area, perimeter and volume",
                    "paras": [
                        "Perimeter is the fence (distance around, 1-D units), area is the lawn (space covered, square units), volume is the water in the pool (space filled, cubic units). Keeping the dimension straight prevents 80% of formula confusion — perimeter adds lengths, area multiplies two lengths, volume multiplies three.",
                        "Start with the rectangle family: P = 2(l + w), A = lw. Triangle: A = ½bh (a triangle is half a rectangle). Circle: A = πr² and C = 2πr (or πd). For volume, prisms are base area × height; a cylinder is πr²h. Don't memorize blindly — every formula is a rectangle idea in disguise, and knowing why means you can rebuild it under exam pressure.",
                    ],
                    "bullets": [
                        "Perimeter: around the edge (units like cm)",
                        "Area: covering the surface (units² like cm²)",
                        "Rectangle A = lw · Triangle A = ½bh · Circle A = πr²",
                        "Circle circumference C = πd, or 2πr",
                        "Prism/cylinder volume = base area × height",
                    ],
                    "example": {
                        "title": "Worked example: circle of radius 5",
                        "body": "Area = πr² = π(5²) = 25π ≈ 78.5 square units. Circumference = 2πr = 10π ≈ 31.4 units. Note: r gets squared in area but not circumference — the #1 circle error.",
                    },
                },
            ],
            "key_concepts": [
                ("Acute / Obtuse angle", "Less than 90° / between 90° and 180°."),
                ("Vertical angles", "Opposite angles formed by two crossing lines — always equal."),
                ("Hypotenuse", "The longest side of a right triangle, opposite the right angle."),
                ("Pythagorean theorem", "a² + b² = c² for right triangles; finds any side from the other two."),
                ("Perimeter", "Distance around a shape — add the side lengths."),
                ("Area", "Surface covered, in square units — rectangle lw, triangle ½bh, circle πr²."),
                ("Volume", "Space filled, in cubic units — prism = base area × height."),
                ("π (pi)", "The circle constant ≈ 3.14159: circumference ÷ diameter for every circle."),
            ],
            "study_tips": [
                "Always draw and label a diagram — geometry is a visual sport, and sketching is free partial credit.",
                "Write the formula before plugging numbers in; it prevents the classic 'squared the diameter' error.",
                "Memorize units along with formulas (cm vs cm² vs cm³) — dimensions catch mistakes formulas miss.",
                "Learn the Pythagorean triples (3-4-5, 5-12-13) to skip computing on common problems.",
                "Explain each proof or formula out loud like you're teaching it — the fastest self-test in geometry.",
            ],
            "practice": [
                {
                    "q": "Two angles of a triangle are 55° and 65°. What's the third?",
                    "choices": ["70°", "60°", "80°", "120°"],
                    "answer": 1,
                    "explain": "Triangle angles sum to 180°: 180 − 55 − 65 = 60°.",
                },
                {
                    "q": "Right triangle legs are 9 and 12. Hypotenuse?",
                    "choices": ["15", "21", "13", "16"],
                    "answer": 0,
                    "explain": "81 + 144 = 225, and √225 = 15. (It's the 3-4-5 triple × 3.)",
                },
                {
                    "q": "Area of a triangle with base 10, height 6?",
                    "choices": ["60", "30", "16", "36"],
                    "answer": 1,
                    "explain": "A = ½bh = ½(10)(6) = 30. Forgetting the ½ (answering 60) is the classic error.",
                },
                {
                    "q": "Circle radius 3 — circumference?",
                    "choices": ["6π", "3π", "9π", "π/3"],
                    "answer": 0,
                    "explain": "C = 2πr = 2π(3) = 6π ≈ 18.8. (9π is the area — don't swap the formulas.)",
                },
            ],
            "flashcards": [
                ("Triangle angle sum", "Exactly 180°, always, every triangle."),
                ("Pythagorean theorem", "a² + b² = c² — right triangles only; c is the hypotenuse."),
                ("What's the hypotenuse?", "The longest side, across from the 90° angle."),
                ("Vertical angles", "Opposite angles at a crossing — always congruent."),
                ("Angles on a straight line", "Sum to 180° (supplementary)."),
                ("Triangle area formula", "A = ½ × base × height."),
                ("Circle area and circumference", "A = πr² · C = 2πr (or πd)."),
                ("Equilateral triangle angles", "All 60° — equal sides mean equal angles."),
                ("Volume of a prism or cylinder", "Base area × height."),
                ("Common Pythagorean triples", "3-4-5, 5-12-13, 8-15-17 (and their multiples)."),
            ],
            "faqs": [
                ("How do I remember all the geometry formulas?",
                 "Don't memorize them cold — derive them once from the rectangle: a triangle is half a rectangle (½bh), a parallelogram is a slanted rectangle (bh), a prism is stacked base areas. Once you see the family tree, you can rebuild any formula on demand. Flashcards then maintain what you derived."),
                ("When can I use the Pythagorean theorem?",
                 "Only in right triangles — one angle must be exactly 90°. If no right angle exists, you need different tools (like the angle sum rule or trigonometry)."),
                ("Why does a triangle's angles sum to 180°?",
                 "Draw a line parallel to one side through the opposite vertex: the three angles line up perfectly along the straight line, and a straight line is 180°. Geometry is consistent that way."),
                ("What's the difference between area and perimeter?",
                 "Perimeter is the fence around the yard (1-D, plain units); area is the grass inside it (2-D, square units). A 4×4 plot and a 2×8 plot have the same area (16) but different fences (16 vs 20) — and a 1×15 plot has even more fence (32) for the same grass. Same lawn, very different fence budgets."),
            ],
            "paa": [
                ("How many degrees in a triangle?", "180° — subtract the two known angles from 180 to find any missing angle."),
                ("What is the Pythagorean theorem used for?", "Finding any missing side of a right triangle, checking if a corner is truly square, and computing distances on a grid (the distance formula is Pythagoras in disguise)."),
                ("How do you find the area of a circle?", "Square the radius, multiply by π: A = πr². Diameter given? Halve it first — r = d/2."),
                ("What are the types of triangles?", "By sides: equilateral, isosceles, scalene. By angles: acute, right, obtuse."),
            ],
        },
        {
            "slug": "trigonometry-essentials",
            "title": "Trigonometry Essentials",
            "h1": "Trigonometry Essentials: SOH-CAH-TOA Without the Tears",
            "meta_title": "Trigonometry for Beginners — Free Guide | StudyBonk",
            "meta_description": "Learn trigonometry free: SOH-CAH-TOA, sine cosine tangent, right triangles and inverse trig — with examples, flashcards and a practice quiz.",
            "summary": "Right triangles, sine/cosine/tangent and the famous SOH-CAH-TOA chant — demystified for good.",
            "keywords": [
                "trigonometry help",
                "soh cah toa",
                "sine cosine tangent",
                "right triangle trig",
                "inverse trig functions",
                "free trigonometry practice",
            ],
            "longtail": [
                "how to understand soh cah toa easily",
                "what is sine cosine and tangent in simple terms",
                "how to find a missing side using trigonometry",
                "how to find an angle using inverse trig functions",
                "trigonometry for absolute beginners",
                "when to use sin cos or tan in a problem",
                "how to label opposite and adjacent sides",
                "special right triangles 45 45 90 and 30 60 90",
                "common trigonometry mistakes students make",
                "real world uses of trigonometry",
            ],
            "sections": [
                {
                    "h2": "What trigonometry is actually for",
                    "paras": [
                        "The Pythagorean theorem handles right triangles when you know two sides. But what if you know one side and one angle? Trigonometry is the tool for that: it reveals the fixed ratios hiding inside every right triangle. Pick any angle in any right triangle and the ratios of its sides (opposite/hypotenuse, adjacent/hypotenuse, opposite/adjacent) never change for that angle.",
                        "That's why sin(30°) is always 0.5, in a triangle the size of your thumb or the size of a skyscraper. Those three ratios get names — sine, cosine, tangent — and suddenly triangles become calculators for measuring things you can't reach: building heights, river widths, satellite orbits.",
                    ],
                    "bullets": [
                        "Trig = side ratios inside right triangles, fixed per angle",
                        "Opposite: across from your angle · Adjacent: next to it · Hypotenuse: longest",
                        "The reference angle decides which side is 'opposite' — label first!",
                        "Same angle → same ratios, no matter the triangle's size",
                    ],
                },
                {
                    "h2": "SOH-CAH-TOA: the chant that pays rent",
                    "paras": [
                        "SOH-CAH-TOA encodes the three definitions: Sine = Opposite over Hypotenuse. Cosine = Adjacent over Hypotenuse. Tangent = Opposite over Adjacent. Every trig problem for the next month is: label the sides, pick the ratio that uses what you know and what you want, solve the little equation.",
                        "Two problem types, one recipe. Missing side? You know an angle + one side: pick your ratio, plug in, solve with algebra (multiply both sides to isolate the unknown). Missing angle? You know two sides: pick the ratio, compute the value, then use inverse trig (sin⁻¹, cos⁻¹, tan⁻¹) to undo it and reveal the angle.",
                    ],
                    "bullets": [
                        "SOH: sin θ = Opp / Hyp",
                        "CAH: cos θ = Adj / Hyp",
                        "TOA: tan θ = Opp / Adj",
                        "Missing side → normal trig ratio, then algebra",
                        "Missing angle → inverse trig (sin⁻¹ etc.) on your calculator",
                    ],
                    "example": {
                        "title": "Worked example: ladder at 60°, reach 10 ft — how long?",
                        "body": "The ladder is the hypotenuse; 10 ft is opposite the 60° angle. Use SOH: sin 60° = 10/L → L = 10 ÷ sin 60° ≈ 10 ÷ 0.866 ≈ 11.5 ft. Label sides first and the ratio chooses itself.",
                    },
                },
                {
                    "h2": "Special triangles and why engineers love trig",
                    "paras": [
                        "Two right triangles appear so often they're worth memorizing exactly. The 45-45-90 triangle has sides 1 : 1 : √2 (half a square). The 30-60-90 triangle has sides 1 : √3 : 2 (half an equilateral). These give exact values like sin 45° = √2/2 and tan 60° = √3 — no calculator needed.",
                        "And the real-world reach is enormous: video game graphics (rotating objects), GPS triangulation, architecture (roof pitches), music (sound waves are sine waves), medical imaging. Every time something rotates, oscillates, or must be measured from afar, trig is quietly doing the work.",
                    ],
                    "bullets": [
                        "45-45-90 sides: 1 : 1 : √2",
                        "30-60-90 sides: 1 : √3 : 2 (short : long : hyp)",
                        "sin 30° = 1/2 · sin 45° = √2/2 · sin 60° = √3/2",
                        "Waves, rotation and navigation are all sine/cosine in disguise",
                    ],
                },
            ],
            "key_concepts": [
                ("Opposite side", "The side across from the angle you're working with — it changes when the angle changes."),
                ("Adjacent side", "The side next to your angle that is NOT the hypotenuse."),
                ("Sine (sin)", "Opposite ÷ Hypotenuse."),
                ("Cosine (cos)", "Adjacent ÷ Hypotenuse."),
                ("Tangent (tan)", "Opposite ÷ Adjacent. (Mnemonic tan = sin/cos.)"),
                ("Inverse trig (sin⁻¹)", "Undoes a ratio to return the angle: if sin θ = 0.5, then θ = sin⁻¹(0.5) = 30°."),
                ("45-45-90 triangle", "Isosceles right triangle with sides 1 : 1 : √2."),
                ("30-60-90 triangle", "Half-equilateral with sides 1 : √3 : 2."),
            ],
            "study_tips": [
                "Always label O, A, H before touching your calculator — mislabeled sides cause most trig errors.",
                "Chant SOH-CAH-TOA during flashcard reps until decoding it is automatic (~1 week of daily drills).",
                "Estimate first: opposite/hypotenuse can never exceed 1, so a sine of 1.5 means something's wrong.",
                "Learn the two special triangles by drawing them from scratch — deriving beats memorizing.",
                "Teach one problem out loud per study session; trig fluency is largely vocabulary fluency.",
            ],
            "practice": [
                {
                    "q": "In a right triangle, the side across from your angle is 3 and the hypotenuse is 5. What ratio is this?",
                    "choices": ["sin θ = 3/5", "cos θ = 3/5", "tan θ = 3/5", "sin θ = 5/3"],
                    "answer": 0,
                    "explain": "Opposite over hypotenuse is the definition of sine: sin θ = 3/5 = 0.6.",
                },
                {
                    "q": "tan θ = 1. What is θ?",
                    "choices": ["30°", "45°", "60°", "90°"],
                    "answer": 1,
                    "explain": "tan 45° = opp/adj = 1 because the 45-45-90 triangle's legs are equal. θ = tan⁻¹(1) = 45°.",
                },
                {
                    "q": "You know the angle and the adjacent side, and need the hypotenuse. Use:",
                    "choices": ["sin", "cos", "tan", "Pythagorean theorem"],
                    "answer": 1,
                    "explain": "Cosine links adjacent and hypotenuse: cos θ = adj/hyp. Pythagoras needs two sides, not an angle.",
                },
                {
                    "q": "Sides of a 30-60-90 triangle, shortest side = 4. Hypotenuse?",
                    "choices": ["4√3", "8", "8√3", "6"],
                    "answer": 1,
                    "explain": "30-60-90 is 1 : √3 : 2, so the hypotenuse is double the shortest side: 4 × 2 = 8.",
                },
            ],
            "flashcards": [
                ("SOH", "Sine = Opposite / Hypotenuse"),
                ("CAH", "Cosine = Adjacent / Hypotenuse"),
                ("TOA", "Tangent = Opposite / Adjacent"),
                ("How to find a missing side", "Pick the ratio with the known angle + side and the wanted side; substitute; solve with algebra."),
                ("How to find a missing angle", "Use two sides to compute a ratio, then apply inverse trig (sin⁻¹, cos⁻¹, tan⁻¹)."),
                ("Which side is 'opposite'?", "Across from the angle in question — it changes if you switch angles."),
                ("45-45-90 side ratio", "1 : 1 : √2 (legs equal, hypotenuse = leg × √2)."),
                ("30-60-90 side ratio", "1 : √3 : 2 (short leg, long leg, hypotenuse)."),
                ("sin 30°", "1/2 (or 0.5)"),
                ("Largest a sine or cosine value can be", "1 — opposite can never exceed the hypotenuse."),
            ],
            "faqs": [
                ("Is trigonometry hard to learn?",
                 "The ideas are simple — three ratios in right triangles — but the vocabulary creates a wall at first. Label sides on every problem for two weeks, drill SOH-CAH-TOA with flashcards daily, and it typically clicks in 2–3 weeks of short sessions."),
                ("When do I use sin vs cos vs tan?",
                 "Let your labels decide: use sine if you have/want the opposite side with the hypotenuse, cosine for adjacent with hypotenuse, tangent for opposite with adjacent. If your knowns don't match any ratio, you may have labeled from the wrong angle."),
                ("What is inverse sine for?",
                 "It runs trig backwards: when you know a ratio (like opp/hyp = 0.5) and need the angle, sin⁻¹(0.5) = 30°. Your calculator's sin⁻¹ button answers 'which angle has this ratio?'"),
                ("Do I need to memorize the special triangles?",
                 "Yes — 45-45-90 (1:1:√2) and 30-60-90 (1:√3:2) appear constantly on exams. Draw each from a square and an equilateral triangle once, and they become impossible to forget."),
            ],
            "paa": [
                ("What does SOH-CAH-TOA stand for?", "Sin = Opp/Hyp, Cos = Adj/Hyp, Tan = Opp/Adj — the three defining ratios of right-triangle trigonometry."),
                ("How is trigonometry used in real life?", "Measuring unreachable heights and distances, navigation and GPS, architecture, engineering, wave physics, music synthesis, and rotating anything in computer graphics."),
                ("Can sine be greater than 1?", "No — the opposite side can't be longer than the hypotenuse, so sine and cosine live between −1 and 1. Seeing 1.5 as an answer signals an error."),
                ("What's the first thing to do in any trig problem?", "Label the sides O, A, H relative to the given angle. With labels in place, choosing the correct ratio becomes automatic."),
            ],
        },
        {
            "slug": "linear-equations-graphing",
            "title": "Linear Equations & Graphing",
            "h1": "Linear Equations & Graphing: Straight Lines, Zero Stress",
            "meta_title": "Linear Equations & Graphing Made Simple | StudyBonk",
            "meta_description": "Master linear equations free: slope, y-intercept, y = mx + b, graphing lines and systems of equations. Examples, flashcards, quiz — no sign-up.",
            "summary": "Slope, y-intercept and y = mx + b — turn equations into lines and lines back into equations.",
            "keywords": [
                "linear equations",
                "slope intercept form",
                "graphing lines",
                "y = mx + b",
                "systems of equations",
                "free algebra practice",
            ],
            "longtail": [
                "what does y equals mx plus b mean",
                "how to find slope from two points",
                "how to graph a linear equation step by step",
                "slope intercept form vs standard form",
                "how to solve systems of equations by substitution",
                "what does the slope represent in real life",
                "how to find the equation of a line",
                "positive negative and zero slope explained",
                "how to solve systems of equations by elimination",
                "parallel and perpendicular lines slope rules",
            ],
            "sections": [
                {
                    "h2": "y = mx + b: the most useful equation in school math",
                    "paras": [
                        "Every straight line on a graph can be described by y = mx + b, and every y = mx + b draws a straight line. m is the slope — how steeply the line climbs (rise over run). b is the y-intercept — where the line crosses the y-axis. Two numbers fully describe any line, which is why this form is everywhere from algebra to machine learning.",
                        "Reading a line is then instant: y = 2x + 1 starts at 1 on the y-axis and climbs 2 units for every 1 unit right. Negative slope descends. Slope 0 is flat. Once you internalize 'm = steepness, b = starting height,' graphs turn into sentences you can read at a glance.",
                    ],
                    "bullets": [
                        "m = slope = rise/run = how fast y changes per step right",
                        "b = y-intercept = where the line crosses the y-axis",
                        "Positive m climbs →, negative m descends, m = 0 is horizontal",
                        "Graphing: plot b, use m to step to a second point, connect",
                    ],
                },
                {
                    "h2": "Finding slope and building equations",
                    "paras": [
                        "Slope between two points (x₁, y₁) and (x₂, y₂) is m = (y₂ − y₁)/(x₂ − x₁) — rise over run. A slope of 3/2 means: up 3, right 2. Slope tells a story: in y = 5x, 5 might be $5 per hour; the intercept is the starting amount; the line is every possible (hours, money) pair.",
                        "To build an equation from data: compute m from two points, then substitute one point into y = mx + b to solve for b. That's the whole technique. Two points → one line, always. And lines are parallel when they share a slope; perpendicular when slopes multiply to −1 (like 2 and −½).",
                    ],
                    "bullets": [
                        "Slope formula: m = (y₂ − y₁)/(x₂ − x₁)",
                        "Equation from 2 points: find m, then plug a point in for b",
                        "Parallel lines: same slope",
                        "Perpendicular lines: slopes multiply to −1",
                        "Real-world slope = a rate: $/hr, miles/gallon, °C per km",
                    ],
                    "example": {
                        "title": "Worked example: line through (1, 3) and (3, 11)",
                        "body": "Slope: m = (11 − 3)/(3 − 1) = 8/2 = 4. Find b with (1,3): 3 = 4(1) + b → b = −1. Equation: y = 4x − 1. Check with the other point: 4(3) − 1 = 11 ✓.",
                    },
                },
                {
                    "h2": "Systems of equations: where lines meet",
                    "paras": [
                        "A system of two linear equations asks: where do these two lines cross? That intersection point satisfies both equations at once. Graphically it's the crossing point; algebraically you can find it exactly with substitution (solve one equation for a variable, substitute into the other) or elimination (add/subtract equations to cancel a variable).",
                        "Substitution shines when one equation already gives x or y alone. Elimination shines when coefficients align (2x + y = 7 and 2x − y = 1: add them → 4x = 8 → x = 2, then back-substitute). Pick the tool that fits the shape of the problem — and if the lines turn out parallel, the system has no solution; identical lines mean infinite solutions.",
                    ],
                    "bullets": [
                        "Solution of a system = the point both equations share",
                        "Substitution: isolate a variable, plug into the other equation",
                        "Elimination: add/subtract equations to cancel one variable",
                        "Parallel lines → no solution · Same line → infinitely many",
                    ],
                },
            ],
            "key_concepts": [
                ("Slope (m)", "Steepness: rise over run; the change in y per 1 unit change in x."),
                ("y-intercept (b)", "Where the line crosses the y-axis — the value of y when x = 0."),
                ("Slope-intercept form", "y = mx + b — the read-it-instantly form of a line."),
                ("Standard form", "Ax + By = C — tidy for finding intercepts and eliminations."),
                ("Point-slope form", "y − y₁ = m(x − x₁) — builds a line from a point and slope."),
                ("System of equations", "Two+ equations solved together; the answer is where graphs intersect."),
                ("Substitution", "Solve one equation for a variable and substitute into the other."),
                ("Elimination", "Add or subtract whole equations to cancel out one variable."),
            ],
            "study_tips": [
                "Always write 'm = slope, b = starting point' at the top of your notes until reading y = mx + b is automatic.",
                "Make a table of x/y values for your first graphs — plotting points builds intuition faster than formulas.",
                "Interpret slope in a sentence ('$5 per hour') — meaning anchors memory better than symbols.",
                "Check system solutions by substituting into BOTH original equations — it catches algebra slips instantly.",
                "Use the flashcard deck for forms (slope-intercept, point-slope, standard) so switching forms becomes reflex.",
            ],
            "practice": [
                {
                    "q": "What is the slope of y = −3x + 7?",
                    "choices": ["7", "−3", "3", "−7"],
                    "answer": 1,
                    "explain": "In y = mx + b, m is the coefficient of x: here m = −3. The line falls 3 units per step right.",
                },
                {
                    "q": "Slope through (2, 5) and (6, 13)?",
                    "choices": ["2", "8", "1/2", "−2"],
                    "answer": 0,
                    "explain": "m = (13 − 5)/(6 − 2) = 8/4 = 2.",
                },
                {
                    "q": "Where does y = 2x + 4 cross the y-axis?",
                    "choices": ["(0, 4)", "(4, 0)", "(0, 2)", "(2, 0)"],
                    "answer": 0,
                    "explain": "The y-intercept is b = 4, at the point (0, 4) — x is always 0 on the y-axis.",
                },
                {
                    "q": "Solve: x + y = 5 and x − y = 1",
                    "choices": ["x = 3, y = 2", "x = 2, y = 3", "x = 4, y = 1", "x = 1, y = 4"],
                    "answer": 0,
                    "explain": "Add the equations: 2x = 6 → x = 3. Then 3 + y = 5 → y = 2. Check both: 3+2=5 ✓, 3−2=1 ✓.",
                },
            ],
            "flashcards": [
                ("In y = mx + b, what is m?", "The slope — rise over run, how much y changes per unit x."),
                ("In y = mx + b, what is b?", "The y-intercept — where the line crosses the y-axis."),
                ("Slope formula from two points", "m = (y₂ − y₁) / (x₂ − x₁)"),
                ("How to graph y = mx + b fast", "Plot b on the y-axis, then step by m (rise/run) to a second point; draw the line."),
                ("Slopes of parallel lines", "Identical slopes, different intercepts."),
                ("Slopes of perpendicular lines", "Negative reciprocals — they multiply to −1 (e.g., 3 and −1/3)."),
                ("Substitution method", "Solve one equation for one variable, substitute that expression into the other equation."),
                ("Elimination method", "Add or subtract the equations to eliminate one variable, then solve."),
                ("When a system has no solution", "The lines are parallel — same slope, never intersect."),
                ("Real-world meaning of slope", "A rate of change: dollars per hour, km per liter, points per game."),
            ],
            "faqs": [
                ("What does the b in y = mx + b represent?",
                 "The y-intercept: the value of y when x = 0, i.e., where the line crosses the y-axis. In real-world problems it's usually the starting value — the initial fee, the base salary, the head start."),
                ("How do I graph a line without making a table?",
                 "Use y = mx + b directly: plot the intercept b at (0, b), then treat slope m as rise/run and step to a second point. Two points determine the line — connect and extend with arrows."),
                ("Which is easier, substitution or elimination?",
                 "Use substitution when one equation already isolates a variable (y = 2x + 1); use elimination when the same variable has matching or opposite coefficients. With practice you'll pick the right tool in under ten seconds."),
                ("What if a system's lines are parallel?",
                 "There's no solution — no point lies on both lines. Algebraically you'll get a contradiction like 0 = 4. If the equations describe the same line, every point works: infinite solutions."),
            ],
            "paa": [
                ("What is slope in simple terms?", "Steepness measured as rise over run: how much y goes up (or down) for each step right."),
                ("How do you find the equation of a line from two points?", "Slope from m = (y₂−y₁)/(x₂−x₁), then substitute either point into y = mx + b to find b."),
                ("What does the intersection point of two lines mean?", "The (x, y) that satisfies both equations simultaneously — the system's solution."),
                ("Why is y = mx + b so important?", "It compresses everything about a line into two readable numbers: steepness (m) and starting point (b) — the template for linear thinking across math, science, and data."),
            ],
        },
        {
            "slug": "word-problems-strategies",
            "title": "Word Problem Strategies",
            "h1": "Word Problem Strategies: Turn Panic Into Points",
            "meta_title": "How to Solve Word Problems Step by Step | StudyBonk",
            "meta_description": "A repeatable strategy for math word problems: translate English to math, set up equations and avoid traps. Free examples, flashcards and quiz.",
            "summary": "A repeatable 5-step system for turning scary paragraphs into simple equations.",
            "keywords": [
                "word problems help",
                "math problem solving",
                "translate words to equations",
                "word problem strategies",
                "free math practice",
            ],
            "longtail": [
                "how to solve math word problems step by step",
                "why are word problems so hard for students",
                "how to translate english into math equations",
                "common keywords in word problems and what they mean",
                "how to know which operation to use in a word problem",
                "word problem strategies for struggling students",
                "how to check if your word problem answer makes sense",
                "how to set up equations from word problems",
                "test taking tips for word problems",
                "how to stop panicking when you see a word problem",
            ],
            "sections": [
                {
                    "h2": "Why word problems feel evil (and the cure)",
                    "paras": [
                        "Word problems are hard because they test two skills at once: reading comprehension and math. The math is usually easier than the naked equation version you'd happily solve. The panic comes from trying to do both skills simultaneously. The cure is a fixed routine that separates reading from computing — so each step is easy on its own.",
                        "The routine: Read (whole problem, no pencil), Draw (picture, table or timeline), Define (name your variables in English: 'x = minutes per day'), Translate (convert each sentence to math), Solve & Sanity-check (does the answer make sense?). Five steps, every single time, even for easy problems — the routine is what makes hard problems tractable.",
                    ],
                    "bullets": [
                        "Step 1 — Read the whole thing once without writing anything",
                        "Step 2 — Draw it: picture, table, or timeline",
                        "Step 3 — Define variables in plain English ('x = price per shirt')",
                        "Step 4 — Translate sentence by sentence into math",
                        "Step 5 — Solve, then ask: 'is this answer reasonable?'",
                    ],
                },
                {
                    "h2": "The translation dictionary",
                    "paras": [
                        "English words map to math symbols with surprising consistency. 'Sum, more than, increased by' → +. 'Difference, fewer than, less than' → −. 'Of, product, times' → ×. 'Per, ratio, quotient' → ÷. 'Is, was, will be, results in' → =. Bookmark this dictionary: most word problems are 90% translation, 10% algebra.",
                        "Beware the traps. 'Less than' reverses order: '5 less than x' is x − 5, not 5 − x. 'Of' means multiply: 'half of 30' = ½ × 30. And 'consecutive integers' means x, x+1, x+2. When a problem mentions total, that's usually your equation's equals sign. Underline the question sentence — literally the last question asked — so you solve for the right thing.",
                    ],
                    "bullets": [
                        "sum, more than, increased by → add",
                        "difference, fewer than, less than → subtract (watch order!)",
                        "of, product, times, twice → multiply",
                        "per, quotient, ratio, split → divide",
                        "is, was, equals, totals → equals sign",
                    ],
                    "example": {
                        "title": "Worked example: 'Three consecutive integers sum to 51.'",
                        "body": "Define: x = smallest. Translate: x + (x+1) + (x+2) = 51. Solve: 3x + 3 = 51 → 3x = 48 → x = 16. Sanity-check: 16 + 17 + 18 = 51 ✓. Answer: 16, 17, 18.",
                    },
                },
                {
                    "h2": "The sanity check: your secret weapon",
                    "paras": [
                        "The difference between a 70% and a 90% student is often just the last 20 seconds: re-read the question and ask whether your answer is plausible. A cat weighing 400 pounds, a negative number of people, an average above every score — implausible answers are free error signals, and checking costs almost nothing.",
                        "Three checks worth habituating: (1) Answer the actual question asked (they asked for the smaller number and you found both). (2) Re-substitute into the original setup. (3) Estimate the magnitude before computing — if your exact answer is wildly far from your estimate, hunt the slip. Build the checks into your routine and careless errors mostly evaporate.",
                    ],
                    "bullets": [
                        "Re-read the question sentence — did you answer what was asked?",
                        "Plug the answer back into the original words, not just your equation",
                        "Estimate first, compare after — magnitude errors stand out",
                        "Watch units: answer in the units the problem requested",
                    ],
                },
            ],
            "key_concepts": [
                ("Variable definition", "Naming the unknown in words — 'x = price per shirt' — before any algebra."),
                ("Translation", "Converting English phrases into math expressions using the keyword dictionary."),
                ("Sanity check", "Testing whether an answer is plausible (size, sign, units) before moving on."),
                ("Draw it first", "Sketching the situation — picture, table, or timeline — to make relationships visible."),
                ("Total signals '='", "Words like 'total', 'altogether', 'combined' usually mark the equation's equals sign."),
                ("Hidden numbers", "Quantities implied but not stated — 'consecutive', 'per', 'each' — that must appear in your setup."),
                ("Multi-part answers", "Problems asking for several values: solve for one variable, then compute the rest before answering."),
                ("Estimation", "Rounding to get a rough magnitude, catching gross errors cheaply."),
            ],
            "study_tips": [
                "Force yourself to write the variable definition sentence — vague variables cause vague equations.",
                "Do translation drills (English phrase → expression) separately from full problems; it isolates the weak skill.",
                "Circle the question sentence before solving; solving the wrong question wastes everything.",
                "After solving, spend 15 seconds on the three sanity checks; it's the highest-ROI habit in test math.",
                "Redo every missed word problem 24 hours later — spaced repetition works on strategies, not just facts.",
            ],
            "practice": [
                {
                    "q": "Translate: 'seven less than twice a number is 19'",
                    "choices": ["2x − 7 = 19", "7 − 2x = 19", "2(x − 7) = 19", "2x = 19 − 7"],
                    "answer": 0,
                    "explain": "'Twice a number' = 2x; 'seven less than' that = 2x − 7; 'is' = equals. Watch the reversal trap: 7 − 2x is wrong.",
                },
                {
                    "q": "A shirt costs $x. It's on sale for 25% off. The sale price expression is:",
                    "choices": ["0.25x", "x − 0.25", "0.75x", "x/25"],
                    "answer": 2,
                    "explain": "25% off means you pay 75%: 0.75x. Or compute x − 0.25x = 0.75x. (x − 0.25 subtracts 25 cents, not 25 percent.)",
                },
                {
                    "q": "Two consecutive even integers sum to 46. The smaller one is:",
                    "choices": ["22", "23", "24", "20"],
                    "answer": 0,
                    "explain": "x + (x + 2) = 46 → 2x = 44 → x = 22. Check: 22 + 24 = 46 ✓. Even integers step by 2.",
                },
                {
                    "q": "You answer 'x = 5 books' but books are sold in packs shown as $12 each. Best sanity check?",
                    "choices": [
                        "Re-read what the question actually asked for",
                        "Move to the next problem immediately",
                        "Erase and start over completely",
                        "Change 5 to a bigger number",
                    ],
                    "answer": 0,
                    "explain": "Most word-problem misses are answering the wrong quantity (books vs dollars). Re-reading the question sentence is the fastest check.",
                },
            ],
            "flashcards": [
                ("'More than / increased by' means", "Addition (+)."),
                ("'Less than' means", "Subtraction — and it reverses the order: '5 less than x' = x − 5."),
                ("'Of' means (in word problems)", "Multiply — 'half of 30' = ½ × 30 = 15."),
                ("'Per' means", "Divide — a rate: miles per hour = miles ÷ hours."),
                ("'Is / was / totals' means", "Equals (=) — the backbone of your equation."),
                ("Step 1 of the word problem routine", "Read the entire problem once without writing anything."),
                ("Why define variables in English?", "'x = minutes per day' prevents setting up the wrong equation — precision before algebra."),
                ("The three sanity checks", "Answer the asked question · substitute back · compare to an estimate."),
                ("'Consecutive integers' in algebra", "x, x+1, x+2 (consecutive even/odd: x, x+2, x+4)."),
                ("Best first move when stuck", "Draw a picture, table, or timeline — visualizing reveals the relationships."),
            ],
            "faqs": [
                ("Why do I understand classwork but fail word problems?",
                 "Classwork hands you pre-translated equations; word problems make you do the translation yourself. Practice translation as its own skill — convert English phrases to expressions — and the gap closes fast."),
                ("How do I know which operation a word problem needs?",
                 "Let keywords guide you (sum→+, difference→−, of→×, per→÷), then confirm with the story: should the answer get bigger or smaller? If a 'discount' answer costs more than the original, the operation was wrong."),
                ("What's the biggest word-problem mistake?",
                 "Answering the wrong question. You solve for x, the problem asked for the total, or the other item, or the remaining amount. Circle the question sentence before you compute anything."),
                ("How can I stop panicking at long word problems?",
                 "Long problems are short problems wearing a coat. Your fixed 5-step routine (Read, Draw, Define, Translate, Solve & Check) breaks any problem into easy pieces — panic can't attach to a routine."),
            ],
            "paa": [
                ("What are the steps to solve a word problem?", "Read fully → draw → define variables → translate to equations → solve → sanity-check the answer against the question."),
                ("How do you turn words into an equation?", "Replace keywords with symbols (of→×, is→=, less than→−), let a variable hold the unknown, and build one sentence of math per sentence of English."),
                ("Why do word problems matter?", "Life delivers math as words — budgets, recipes, travel times, data — never as naked equations. Word problems are the actual transfer skill."),
                ("How long should a word problem take?", "On a test, budget 1.5–2.5 minutes: ~30 seconds on setup, the rest computing. If setup is right, computing is usually the easy part."),
            ],
        },
    ],
}
