"""Chemistry pillar: 1 pillar page + 6 cluster pages.

Schema (must match exactly — see docs/CONTENT.md and topic_math.py):
PILLAR = {slug, title, emoji, meta_title<=62, meta_description<=160, h1,
tagline, summary, keywords[], longtail[12+], intro[paras], bullets[],
faqs[(q,a)x5], paa[(q,a)x5], clusters[{slug, title, h1, meta_title,
meta_description, summary, keywords[], longtail[10+],
sections[{h2, paras[], bullets[], example?{title, body}}],
key_concepts[(term,def)x8], study_tips[x5],
practice[{q, choices[4], answer(idx), explain}]x4,
flashcards[(front,back)]x10, faqs[(q,a)x4], paa[(q,a)x4]}]}
"""

PILLAR = {
    "slug": "chemistry",
    "title": "Chemistry",
    "emoji": "⚗️",
    "meta_title": "Free Chemistry Study Hub — Learn Chem Fast | StudyBonk",
    "meta_description": "Free chemistry study guides, flashcards and quizzes: atoms, the periodic table, bonding, moles, acids and bases. No sign-up, gamified, 100% private.",
    "h1": "Free Chemistry Study Hub: Atoms, Bonds, Moles & More",
    "tagline": "From atomic structure to acids and bases — free guides, decks and quizzes that make chemistry finally click.",
    "summary": "Free chemistry guides, flashcard decks and practice quizzes for atomic structure, the periodic table, bonding, reactions, moles and pH.",
    "keywords": [
        "chemistry help",
        "learn chemistry online free",
        "chemistry flashcards",
        "periodic table explained",
        "balancing equations help",
        "moles and stoichiometry",
        "acids and bases",
        "ionic and covalent bonds",
        "atomic structure",
        "free chemistry quiz",
    ],
    "longtail": [
        "how to study chemistry effectively for exams",
        "what is a mole in chemistry explained simply",
        "how to balance chemical equations step by step",
        "easiest way to read the periodic table",
        "ionic vs covalent bonds difference",
        "what is the difference between atomic number and mass number",
        "how to do stoichiometry for beginners",
        "acids and bases examples in everyday life",
        "how does the ph scale work",
        "how to find protons neutrons and electrons",
        "why is chemistry so hard for students",
        "how to memorize periodic table trends",
        "best free chemistry practice with explanations",
    ],
    "intro": [
        "Chemistry is the science of matter — what stuff is made of and how it changes. It gets a reputation for being hard because it stacks math on top of new vocabulary on top of particles too small to see. StudyBonk unwinds that stack in order: short lessons that build each idea on the last one, flashcard decks for the terms, and quizzes where every answer is explained.",
        "Everything below is 100% free, requires no account, and keeps your progress stored privately in your browser. Earn XP, keep your streak alive, and walk into your next chem test actually feeling ready.",
    ],
    "bullets": [
        "Master atomic structure: protons, neutrons, electrons, isotopes",
        "Read the periodic table like a map: groups, periods, trends",
        "Explain ionic, covalent and metallic bonding in plain English",
        "Balance chemical equations and recognize the reaction types",
        "Conquer moles and stoichiometry with three simple conversions",
        "Understand acids, bases, the pH scale and neutralization",
    ],
    "faqs": [
        ("Is StudyBonk good for learning chemistry?",
         "Yes. StudyBonk covers the core units of nearly every intro chemistry course — atomic structure, the periodic table, bonding, reactions, the mole and acid-base chemistry — with short lessons, flashcard decks and quizzes that explain every answer. It's free, requires no account, and works offline after the first load."),
        ("Why does chemistry feel so much harder than other subjects?",
         "Because it layers three skills at once: new vocabulary, tiny invisible particles, and math. Fix them in that order — learn the terms with flashcards, build mental pictures with the lessons, then practice the math. When the layers stop competing for attention, chemistry gets dramatically easier."),
        ("How much should I study chemistry per day?",
         "About 20-30 focused minutes daily beats a three-hour cram. Chemistry rewards worked problems and spaced repetition: a few practice questions and a flashcard session every day will outperform weekend marathons every time."),
        ("Can I use StudyBonk chemistry offline?",
         "Yes. After your first visit, the app is cached by your browser and works offline, including flashcards, quizzes and the AI tutor. Your XP, streaks and progress are stored locally on your device."),
        ("Is StudyBonk really free with no sign-up?",
         "Really free, really no account. No ads, no paywalls, no email capture, no tracking. Everything saves in your browser's local storage, and the code is open-source on GitHub so you can verify it yourself."),
    ],
    "paa": [
        ("What is chemistry in simple words?",
         "The study of matter — what everything is made of, how atoms combine, and how those combinations change. Cooking, medicine, batteries and rust are all chemistry in action."),
        ("How do I start learning chemistry from scratch?",
         "In this order: atomic structure (the pieces), the periodic table (the map), bonding (how pieces connect), reactions (what connections do), the mole (the counting system), then acids and bases. Each topic is the foundation of the next."),
        ("Why do students fail chemistry?",
         "Usually from two compounding gaps: memorizing vocabulary without understanding it, and falling behind on math they could have drilled early (unit conversions especially). Both are fixable with daily short practice and instant feedback."),
        ("Is chemistry mostly math or memorization?",
         "Both, but at different layers — vocabulary first (what things are called), then a small set of repeatable math tools (mole conversions, balancing, pH). Master the terms and the math becomes plug-and-play."),
        ("What's the hardest topic in chemistry?",
         "For most students it's the mole and stoichiometry, because it blends vocabulary, units and multi-step problem solving. That's why StudyBonk gives it its own page with extra-clear worked examples."),
    ],
    "clusters": [
        {
            "slug": "atomic-structure",
            "title": "Atomic Structure",
            "h1": "Atomic Structure Explained: Protons, Neutrons & Electrons",
            "meta_title": "Atomic Structure Made Simple — Free | StudyBonk",
            "meta_description": "Learn atomic structure free: protons, neutrons, electrons, mass number, ions and isotopes — with flashcards, worked examples and a quiz. No sign-up.",
            "summary": "Protons, neutrons, electrons, ions and isotopes — the subatomic world explained simply.",
            "keywords": [
                "atomic structure basics",
                "protons neutrons electrons",
                "atomic number vs mass number",
                "what are isotopes",
                "how to find neutrons",
                "free chemistry practice",
            ],
            "longtail": [
                "how to find protons neutrons and electrons",
                "what is the difference between atomic number and mass number",
                "what are isotopes in simple terms",
                "what makes an atom a certain element",
                "what happens when an atom gains or loses electrons",
                "dalton thomson rutherford bohr models explained",
                "what is an ion in chemistry",
                "where is most of an atom's mass located",
                "why is the periodic table mass not a whole number",
                "how to read an element symbol on the periodic table",
            ],
            "sections": [
                {
                    "h2": "What an atom is made of",
                    "paras": [
                        "An atom is the smallest unit of an element, and it has three particles worth knowing: protons (positive charge, in the nucleus), neutrons (no charge, also in the nucleus) and electrons (negative charge, zooming around the outside). Protons and neutrons are heavy and carry nearly all the atom's mass; an electron is about 2,000 times lighter.",
                        "The particle counts decide everything. The number of protons — the atomic number — defines which element you have; change the proton count and you've changed the element itself. Electrons control how atoms bond. Neutrons add mass and can vary without changing the element, and those variants are isotopes.",
                    ],
                    "bullets": [
                        "Proton: positive, in the nucleus, defines the element",
                        "Neutron: neutral, in the nucleus, adds mass",
                        "Electron: negative, outside the nucleus, controls bonding",
                        "Atoms are neutral when protons = electrons",
                        "Almost all of the atom's mass lives in the nucleus",
                    ],
                },
                {
                    "h2": "Reading the symbol: atomic number and mass number",
                    "paras": [
                        "Every element box shows an atomic number (the proton count) and an average atomic mass. For a single atom, the mass number is protons plus neutrons — which turns neutrons into a subtraction problem: neutrons = mass number − atomic number. That one formula answers a huge share of exam questions.",
                        "Watch what the numbers mean. The mass printed on the periodic table is an average across all of that element's natural isotopes, so it's rarely a whole number — oxygen's 16.00 doesn't mean every oxygen atom has exactly 8 neutrons. When a problem gives you a whole-number mass for one specific atom, that's the mass number; use subtraction from there.",
                    ],
                    "bullets": [
                        "Atomic number = protons = the element's identity",
                        "Mass number = protons + neutrons (for one atom)",
                        "Neutrons = mass number − atomic number",
                        "Periodic table mass is an isotope average, rarely a whole number",
                    ],
                    "example": {
                        "title": "Worked example: mass number 23, atomic number 11",
                        "body": "Atomic number 11 means 11 protons — that's sodium (Na). Neutrons = 23 − 11 = 12. If the atom is neutral, it also has 11 electrons. Any 'find the particles' question is this exact recipe: identify the element, subtract for neutrons, match electrons.",
                    },
                },
                {
                    "h2": "Isotopes: same element, different mass",
                    "paras": [
                        "Isotopes are atoms of the same element with different neutron counts — same protons, so same chemistry; different mass, so slightly different physics. Carbon-12 (6 neutrons) and carbon-14 (8 neutrons) are the classic pair: identical as elements, but carbon-14 is radioactive and famously used to date fossils.",
                        "Isotope notation is friendly once you decode it: carbon-14 means the mass number is 14. Since carbon's atomic number is always 6, the neutrons are again a subtraction: 14 − 6 = 8. In nature most elements are a blend of isotopes, which is exactly why periodic table masses are weighted averages instead of neat whole numbers.",
                    ],
                    "bullets": [
                        "Isotopes = same protons, different neutrons",
                        "Same element and same chemistry, different mass",
                        "Carbon-12 vs carbon-14: 6 vs 8 neutrons, the classic pair",
                        "The name's number is the mass number (uranium-238)",
                    ],
                },
                {
                    "h2": "How the atomic model evolved",
                    "paras": [
                        "The atom's history is a story of 'wrong but useful.' Dalton (early 1800s): atoms are solid indivisible spheres. Thomson (1897): discovers the electron — atoms have parts, the plum pudding model. Rutherford (1911): fires particles at gold foil; most fly through but a few bounce, so the atom is mostly empty space around a tiny dense nucleus. Bohr (1913): electrons orbit at fixed energy levels like planets.",
                        "Today's quantum model replaces neat orbits with clouds of probability — electrons are somewhere within regions called orbitals. For school purposes the Bohr model still powers most drawings and bonding questions, so learn it well; just know it's a simplification. Science models are tools that get sharper, not statues that were perfect from the start.",
                    ],
                    "bullets": [
                        "Dalton: solid spheres → Thomson: electrons exist → Rutherford: nucleus → Bohr: shells",
                        "Rutherford's gold foil: mostly empty space + a tiny dense core",
                        "Bohr model: electrons in fixed shells (still used for bonding)",
                        "Modern model: probability clouds (orbitals), not tiny planets",
                    ],
                },
            ],
            "key_concepts": [
                ("Atom", "The smallest unit of an element that still has that element's properties."),
                ("Proton", "Positively charged particle in the nucleus; its count defines the element."),
                ("Neutron", "Chargeless particle in the nucleus; adds mass but never changes the element."),
                ("Electron", "Negatively charged particle outside the nucleus; responsible for bonding."),
                ("Atomic number", "The number of protons — an element's unique ID."),
                ("Mass number", "Protons + neutrons for a single atom."),
                ("Isotope", "A version of an element with a different neutron count (carbon-12 vs carbon-14)."),
                ("Nucleus", "The dense center of protons and neutrons holding nearly all the mass."),
            ],
            "study_tips": [
                "Drill the one formula until it's reflex: neutrons = mass number − atomic number.",
                "Say the three charges as a beat: 'proton plus, neutron none, electron minus.'",
                "For ion questions, remember electrons are the only particle that changes — protons never do.",
                "Sketch the gold foil experiment once; understanding why it proved a nucleus makes it unforgettable.",
                "Run the flashcard deck daily for a week — atomic structure questions are pure speed once you know the recipe.",
            ],
            "practice": [
                {
                    "q": "An atom has 17 protons, 18 neutrons and 17 electrons. Its mass number is:",
                    "choices": ["17", "18", "35", "52"],
                    "answer": 2,
                    "explain": "Mass number = protons + neutrons = 17 + 18 = 35. Electrons are ignored — they're so light they barely count toward mass.",
                },
                {
                    "q": "What determines which element an atom is?",
                    "choices": ["Neutron count", "Proton count", "Electron count", "Mass number"],
                    "answer": 1,
                    "explain": "The proton count (atomic number) is the element's identity card. Change neutrons and you get an isotope; change electrons and you get an ion; change protons and you have a different element entirely.",
                },
                {
                    "q": "Carbon-14 has how many neutrons? (Carbon's atomic number is 6.)",
                    "choices": ["8", "6", "14", "20"],
                    "answer": 0,
                    "explain": "The 14 is the mass number: protons + neutrons. So neutrons = 14 − 6 = 8. Carbon-12 would have 12 − 6 = 6 neutrons.",
                },
                {
                    "q": "An atom that gains electrons becomes:",
                    "choices": ["A different element", "A positive ion", "An isotope", "A negative ion"],
                    "answer": 3,
                    "explain": "Extra electrons bring extra negative charge — a negative ion (anion). Losing electrons leaves more protons than electrons, making a positive ion (cation). The element never changes.",
                },
            ],
            "flashcards": [
                ("Charge and location of a proton", "Positive, inside the nucleus."),
                ("Charge and location of a neutron", "Neutral (no charge), inside the nucleus."),
                ("Charge and location of an electron", "Negative, outside the nucleus."),
                ("Atomic number tells you", "The number of protons — and therefore the element."),
                ("Mass number formula", "Protons + neutrons."),
                ("How to find neutrons", "Mass number − atomic number."),
                ("What is an isotope?", "Same element, same protons, different neutrons — like carbon-12 vs carbon-14."),
                ("Where is almost all the atom's mass?", "In the nucleus (protons and neutrons)."),
                ("What is an ion?", "An atom that gained or lost electrons, giving it a net charge."),
                ("Rutherford's gold foil experiment proved", "Atoms are mostly empty space with a tiny dense positive nucleus."),
            ],
            "faqs": [
                ("What's the difference between atomic number and mass number?",
                 "Atomic number counts just protons — it identifies the element. Mass number counts protons plus neutrons for one atom. Subtract the first from the second and you get the neutron count, which is the single most-used move on atomic structure tests."),
                ("Can an atom lose protons?",
                 "Not by ordinary chemistry. Adding or losing electrons makes ions; changing neutrons makes isotopes; changing protons makes a different element — that takes nuclear reactions. Chemistry only ever shuffles electrons."),
                ("Why isn't the mass on the periodic table a whole number?",
                 "Because it's a weighted average of all that element's natural isotopes. Chlorine's 35.45 means a mix of mostly chlorine-35 and some chlorine-37 averaging out to 35.45 — individual atoms still have whole-number mass numbers."),
                ("Do I need to memorize the atomic models history?",
                 "Know the order and the one-line discovery each added: Dalton (atoms exist), Thomson (electrons), Rutherford (nucleus), Bohr (shells), quantum (orbitals). Questions almost always ask which model came from which experiment."),
            ],
            "paa": [
                ("How do you find the number of neutrons?", "Subtract the atomic number from the mass number: neutrons = mass − protons. Example: sodium-23 has 23 − 11 = 12 neutrons."),
                ("What is the difference between an ion and an isotope?", "An ion has gained or lost electrons (charge changes); an isotope has a different number of neutrons (mass changes). Ions are about charge, isotopes about mass."),
                ("What are isotopes used for?", "Carbon-14 dates fossils, radioactive isotopes treat cancer and power medical imaging, and uranium-235 fuels nuclear reactors — same chemistry as their stable cousins, different nuclei."),
                ("Which particle is the smallest?", "The electron by far — roughly 2,000 times lighter than a proton or neutron. That's why electron counts don't change an atom's mass number in class problems."),
            ],
        },
        {
            "slug": "periodic-table",
            "title": "Periodic Table",
            "h1": "How to Read the Periodic Table: Groups, Periods & Trends",
            "meta_title": "How to Read the Periodic Table — Free | StudyBonk",
            "meta_description": "Read the periodic table with confidence: groups, periods, valence electrons, metals vs nonmetals and the big trends. Free flashcards and quiz, no sign-up.",
            "summary": "Groups, periods, valence electrons and the big trends — the periodic table turned into a map you can read.",
            "keywords": [
                "periodic table explained",
                "groups and periods",
                "valence electrons",
                "periodic table trends",
                "metals nonmetals metalloids",
                "free chemistry quiz",
            ],
            "longtail": [
                "how to read the periodic table for beginners",
                "what is the difference between a group and a period",
                "what are valence electrons and why do they matter",
                "periodic table trends atomic radius and electronegativity",
                "why are noble gases unreactive",
                "where are metals located on the periodic table",
                "what are the halogens and alkali metals",
                "how does the periodic table predict bonding",
                "what does the group number tell you",
                "easiest way to memorize periodic table families",
            ],
            "sections": [
                {
                    "h2": "How the table is organized (and why)",
                    "paras": [
                        "The periodic table looks like a wall of random boxes until you learn its two rules. Rule one: elements are arranged by increasing atomic number — the number of protons. Rule two: elements in the same vertical column, called a group, have the same number of valence electrons, so they behave alike. That's the whole trick — the table stacks similar elements into columns on purpose.",
                        "Rows are called periods. Moving across a period fills up the same outer electron shell; moving down a group adds a new shell. Metals occupy the left and middle (about three-quarters of the table), nonmetals sit in the upper right, and metalloids zigzag along the staircase border between them.",
                    ],
                    "bullets": [
                        "Arranged by atomic number, left to right, top to bottom",
                        "Group (column) = same valence electrons = similar behavior",
                        "Period (row) = same number of electron shells",
                        "Metals: left and middle · nonmetals: upper right · metalloids: the staircase",
                    ],
                },
                {
                    "h2": "Groups and periods: the cheat codes",
                    "paras": [
                        "Certain groups have names worth memorizing because they show up constantly. Group 1: alkali metals, wildly reactive (think sodium fizzing in water). Group 2: alkaline earth metals. Group 17: halogens, the most reactive nonmetals. Group 18: noble gases, famously unreactive because their outer shells are already full — they never need to bond with anyone.",
                        "The group number tells you valence electrons directly: Group 1 has 1, Group 2 has 2, and Groups 13-18 have 1 through 6 (skip the middle transition metals for now). Since atoms bond to fill their outer shell, knowing the valence count is knowing the chemistry. An element in Group 17 needs exactly one more electron — that's why it reacts so aggressively.",
                    ],
                    "bullets": [
                        "Group 1: alkali metals — explosively reactive",
                        "Group 17: halogens — most reactive nonmetals, need 1 electron",
                        "Group 18: noble gases — full outer shell, nearly inert",
                        "Group number = valence electron count (for main-group elements)",
                    ],
                    "example": {
                        "title": "Worked example: predicting behavior from the table",
                        "body": "Chlorine sits in Group 17, so it has 7 valence electrons and needs 1 more to fill its shell. Sodium sits in Group 1 with 1 valence electron, eager to lose it. That's why NaCl forms so easily: sodium gives, chlorine takes, both end up with full outer shells. You just predicted an ionic bond from two column positions.",
                    },
                },
                {
                    "h2": "The trends: three arrows to remember",
                    "paras": [
                        "The table has built-in trends. Atomic radius shrinks moving left to right across a period (more protons pull the electrons in tighter) and grows moving down a group (more shells stack up). So the biggest atoms live bottom-left and the smallest sit top-right near helium.",
                        "Electronegativity and ionization energy share one rule: both increase up and to the right, peaking at fluorine. Electronegativity is an atom's pull on shared electrons; ionization energy is the effort needed to pry an electron away. Metallic character runs the opposite direction, strongest bottom-left. Draw the trend arrows once on a blank table and the patterns become visual instead of memorized.",
                    ],
                    "bullets": [
                        "Atomic radius: decreases across a period, increases down a group",
                        "Biggest atoms bottom-left · smallest top-right",
                        "Electronegativity: strongest at fluorine (up and to the right)",
                        "Ionization energy follows the same arrow as electronegativity",
                    ],
                },
                {
                    "h2": "How to actually use the table on a test",
                    "paras": [
                        "Most periodic table questions are really reading practice. Find the element's box, read the atomic number for protons, estimate neutrons from a rounded mass, count columns for valence electrons, and classify it as metal, nonmetal or metalloid. Those five steps answer identity, bonding and reactivity questions alike.",
                        "On test day you'll almost always get a copy of the table — so the skill isn't memorizing it, it's navigating it fast. Practice until locating any element takes under five seconds, and annotate your own practice copy with the trend arrows so reading them becomes automatic.",
                    ],
                    "bullets": [
                        "Locate the element → count valence electrons → classify → predict bonding",
                        "Trend arrows drawn once on a blank table stick forever",
                        "You get the table on tests — navigation speed is the real skill",
                        "Color-code metals, nonmetals and metalloids on your practice copy",
                    ],
                },
            ],
            "key_concepts": [
                ("Group", "A vertical column; elements share valence electrons and behave alike."),
                ("Period", "A horizontal row; elements share the number of electron shells."),
                ("Valence electron", "An electron in the outermost shell — the ones that do all the bonding."),
                ("Alkali metals", "Group 1: soft, explosively reactive metals with 1 valence electron."),
                ("Halogens", "Group 17: highly reactive nonmetals needing 1 more electron."),
                ("Noble gases", "Group 18: full outer shells make them nearly unreactive."),
                ("Electronegativity", "An atom's pull on shared electrons; increases up and to the right."),
                ("Atomic radius", "An atom's size; decreases across a period, increases down a group."),
            ],
            "study_tips": [
                "Learn the map before the facts: groups are columns, periods are rows — that orientation alone answers half of questions.",
                "Memorize the three famous families (alkali metals, halogens, noble gases) with their group numbers.",
                "Draw the trend arrows on a blank periodic table once a week — direction memory beats definition memory.",
                "Drill valence counts: Group 1 → 1, Group 2 → 2, Groups 13-18 → 1 through 6.",
                "Use the flashcards for trends so 'which is bigger, Na or Cl?' becomes a three-second answer.",
            ],
            "practice": [
                {
                    "q": "Elements in the same group of the periodic table share the same number of:",
                    "choices": ["Protons", "Valence electrons", "Neutrons", "Electron shells"],
                    "answer": 1,
                    "explain": "Groups are columns, and column-mates have matching valence electron counts — which is exactly why they react similarly. Electron shells match within a period (a row), not a group.",
                },
                {
                    "q": "Which group is famously unreactive because its outer shells are already full?",
                    "choices": ["Group 1", "Group 2", "Group 17", "Group 18"],
                    "answer": 3,
                    "explain": "Group 18, the noble gases (helium, neon, argon...), have full outer shells. With nothing to gain or lose, they rarely bond — the introverts of the table.",
                },
                {
                    "q": "Moving left to right across a period, atomic radius generally:",
                    "choices": ["Increases", "Decreases", "Stays the same", "Doubles"],
                    "answer": 1,
                    "explain": "Each step right adds a proton, and the stronger pull drags electrons closer — atoms shrink across a row. Down a column they grow, because new shells get added.",
                },
                {
                    "q": "An element in Group 1, with 1 valence electron, will most likely:",
                    "choices": ["Gain 7 electrons", "Share 4 electrons", "Lose 1 electron", "Do nothing"],
                    "answer": 2,
                    "explain": "Losing its single valence electron empties the outer shell, exposing the full shell beneath — the easy path. That's why alkali metals form +1 ions so eagerly.",
                },
            ],
            "flashcards": [
                ("Group vs period", "Group = vertical column (same valence electrons); period = horizontal row (same shells)."),
                ("What are valence electrons?", "Outer-shell electrons — they determine how an atom bonds."),
                ("Group 1 is called", "The alkali metals — highly reactive, 1 valence electron."),
                ("Group 17 is called", "The halogens — reactive nonmetals that need 1 more electron."),
                ("Group 18 is called", "The noble gases — full shells, nearly unreactive."),
                ("Where are the metals?", "Left and center — about three-quarters of the table."),
                ("Atomic radius trend", "Decreases across a period, increases down a group."),
                ("Electronegativity trend", "Increases up and to the right — fluorine is the strongest."),
                ("Which element is the most electronegative?", "Fluorine."),
                ("Why do noble gases barely react?", "Their outer shells are already full — no drive to gain, lose or share."),
            ],
            "faqs": [
                ("How do I read a periodic table box?",
                 "Two numbers and a symbol: the whole number (usually above) is the atomic number = protons; the decimal is the average atomic mass. Locate the column for valence electrons and you've extracted everything a test will ask."),
                ("What's the difference between a group and a period?",
                 "A group is a vertical column — members share valence electrons and react alike. A period is a horizontal row — members share the number of electron shells. Column = behavior, row = size of cloud."),
                ("Why do alkali metals explode in water?",
                 "They desperately want to shed their single valence electron. Water lets them react fast enough to release hydrogen gas and heat at once — boom. Reactivity increases down Group 1, so cesium is wilder than sodium."),
                ("Do I have to memorize the whole periodic table?",
                 "No — you'll get a copy on nearly every test. What pays off is instant navigation plus the trends and the famous families (alkali metals, halogens, noble gases). Memorize the map's logic, not all 118 boxes."),
            ],
            "paa": [
                ("What does the group number tell you?", "For main-group elements, the valence electron count: Group 1 has 1, Group 2 has 2, and Groups 13-18 have 1 through 6. Valence electrons predict bonding, so the column predicts chemistry."),
                ("Which is bigger: a sodium atom or a chlorine atom?", "Sodium. Atomic radius shrinks across a period, and sodium is further left in the same row — chlorine's extra protons pull its electrons in tighter."),
                ("Why is fluorine the most reactive nonmetal?", "It needs just one electron to fill its shell, sits highest on the right among elements that accept electrons, and pulls shared electrons hardest — maximum motivation plus maximum grip."),
                ("What are metalloids?", "The staircase elements (boron, silicon, germanium...) that sit between metals and nonmetals and behave like both — silicon's semi-conductivity is why your phone exists."),
            ],
        },
        {
            "slug": "chemical-bonding",
            "title": "Chemical Bonding",
            "h1": "Chemical Bonding Explained: Ionic, Covalent & Metallic",
            "meta_title": "Ionic, Covalent & Metallic Bonding Made Easy | StudyBonk",
            "meta_description": "Learn chemical bonding free: the octet rule, ionic vs covalent vs metallic bonds and how to predict bond types. Flashcards, quiz, no sign-up needed.",
            "summary": "Why atoms bond, and the three ways they do it — ionic, covalent and metallic, in plain English.",
            "keywords": [
                "chemical bonding basics",
                "ionic vs covalent bonds",
                "metallic bonding",
                "octet rule explained",
                "cations and anions",
                "free chemistry quiz",
            ],
            "longtail": [
                "what is the difference between ionic and covalent bonds",
                "what is the octet rule in simple terms",
                "how do you know if a bond is ionic or covalent",
                "why do metals conduct electricity",
                "what happens when sodium bonds with chlorine",
                "what is a cation and an anion",
                "properties of ionic vs covalent compounds",
                "what is a polar covalent bond",
                "why is water a polar molecule",
                "what is metallic bonding and how does it work",
            ],
            "sections": [
                {
                    "h2": "Why atoms bond: the octet rule",
                    "paras": [
                        "Atoms bond for one reason: to reach a stable outer electron shell, usually one holding eight electrons — the octet rule. The noble gases already have that setup, which is why they float around alone and unbothered. Everyone else must gain, lose or share electrons to get there, and that drive produces every compound you've ever met.",
                        "The key player is the valence electron — the electrons in the outermost shell. Atoms holding one or two valence electrons tend to lose them (metals); atoms holding six or seven tend to gain (nonmetals); atoms in the middle prefer sharing. Count valence electrons and you can usually predict the bond type before doing any math.",
                    ],
                    "bullets": [
                        "Octet rule: atoms want a full outer shell of 8 electrons",
                        "Noble gases already qualify — that's why they don't react",
                        "Valence electrons do all the bonding work",
                        "Few valence electrons → lose them · many → gain · middle → share",
                    ],
                },
                {
                    "h2": "Ionic bonds: give and take",
                    "paras": [
                        "An ionic bond forms when one atom transfers electrons to another. Sodium (1 valence electron) hands its electron to chlorine (7 valence electrons). Sodium becomes a positive ion, Na+, because it lost a negative electron; chlorine becomes negative, Cl−. Opposite charges snap together into a repeating crystal lattice — and that's table salt.",
                        "Because ionic compounds are held by full positive-negative attractions, they form hard crystals with high melting points, and they conduct electricity when dissolved in water (the freed ions carry the charge). Remember the shortcut: a metal bonded to a nonmetal is almost always ionic.",
                    ],
                    "bullets": [
                        "Electron transfer: metal gives, nonmetal takes",
                        "Cation = positive ion (lost electrons); anion = negative ion (gained)",
                        "Properties: hard crystals, high melting points, conduct when dissolved",
                        "Metal + nonmetal → almost always ionic",
                    ],
                },
                {
                    "h2": "Covalent bonds: share and share alike",
                    "paras": [
                        "A covalent bond forms when two atoms share one or more pairs of electrons — usually two nonmetals, because neither wants to surrender electrons outright. Two hydrogen atoms each share their single electron, and both count the pair as a full shell. Water (H2O), CO2 and nearly every molecule in your body are covalent.",
                        "Covalent compounds come as molecules rather than crystals: lower melting and boiling points than ionic compounds, and no conduction in water because no ions break free. When sharing is unequal — one atom pulls harder because of higher electronegativity — you get polar covalent bonds, which is why water bends toward charged objects and dissolves salt so well.",
                    ],
                    "bullets": [
                        "Electron sharing between (usually) two nonmetals",
                        "Forms molecules: H2O, CO2, CH4 — most of biology",
                        "Lower melting and boiling points than ionic compounds",
                        "Polar covalent = unequal sharing, like in water",
                    ],
                    "example": {
                        "title": "Worked example: classifying a bond",
                        "body": "KCl: potassium (metal) + chlorine (nonmetal) → ionic, an electron transfers. CO2: carbon + oxygen, both nonmetals → covalent, electrons shared. The test is who's involved: classify the elements first and the bond type follows. Electronegativity difference is the tiebreaker when you need precision.",
                    },
                },
                {
                    "h2": "Metallic bonds and the three-way comparison",
                    "paras": [
                        "In a metal, atoms pack together and their valence electrons float free through the whole structure — a sea of electrons. Those mobile electrons explain everything about metals: they conduct electricity and heat because charged particles roam, they bend instead of shatter because the sea absorbs the shift, and they shine because the electrons interact with light.",
                        "Comparison in one breath: ionic = transfer (metal + nonmetal, crystals), covalent = share (nonmetal + nonmetal, molecules), metallic = pool (metal + metal, malleable conductors). Any 'which bond is this?' question is answered by checking which categories the elements fall into.",
                    ],
                    "bullets": [
                        "Metallic bonding: positive metal ions in a sea of shared electrons",
                        "Free-flowing electrons explain conductivity, bendiness and shine",
                        "Ionic = transfer · covalent = share · metallic = pool",
                        "Identify the elements first, then the bond type follows",
                    ],
                },
            ],
            "key_concepts": [
                ("Chemical bond", "An attraction between atoms that holds them together in a compound."),
                ("Octet rule", "Atoms bond to reach a full outer shell of 8 electrons, like the noble gases."),
                ("Valence electron", "Outer-shell electron; its count decides whether atoms lose, gain or share."),
                ("Ion", "A charged atom — a cation (positive, lost electrons) or anion (negative, gained)."),
                ("Ionic bond", "A bond formed by transferring electrons from a metal to a nonmetal."),
                ("Covalent bond", "A bond formed by sharing electron pairs, usually between nonmetals."),
                ("Metallic bond", "A bond where metal atoms pool their electrons into a mobile sea."),
                ("Molecule", "Two or more atoms covalently bonded — the unit of covalent compounds."),
            ],
            "study_tips": [
                "Classify by players first: metal + nonmetal = ionic, nonmetal + nonmetal = covalent, metal + metal = metallic.",
                "Link every property to its bond: crystals and high melting points = ionic; soft molecules = covalent; bendy and conductive = metallic.",
                "Draw sodium giving chlorine one electron as a cartoon once — transfer bonds are easier to remember as pictures.",
                "Memorize cation/anion with the vowels: a-plus (cation is positive... careful) — or just 'cats are paws-itive.'",
                "Run the flashcard deck daily until bond-type questions take under ten seconds.",
            ],
            "practice": [
                {
                    "q": "A bond formed when one atom transfers electrons to another is:",
                    "choices": ["Covalent", "Metallic", "Ionic", "Polar"],
                    "answer": 2,
                    "explain": "Transfer = ionic. The giver becomes a positive ion, the taker negative, and their attraction forms the bond. Sharing is covalent; pooling is metallic.",
                },
                {
                    "q": "Which compound is most likely covalent?",
                    "choices": ["H2O", "NaCl", "MgO", "KBr"],
                    "answer": 0,
                    "explain": "H2O bonds hydrogen to oxygen — both nonmetals — so they share: covalent. The other three all pair a metal with a nonmetal, the ionic signature.",
                },
                {
                    "q": "Metals conduct electricity because:",
                    "choices": [
                        "Their electrons are locked in fixed orbits",
                        "Their valence electrons flow freely through the structure",
                        "They are ionic crystals",
                        "They contain noble gases",
                    ],
                    "answer": 1,
                    "explain": "In metallic bonding, valence electrons detach from individual atoms and roam the whole metal — a sea of electrons. Moving charge is exactly what conduction is.",
                },
                {
                    "q": "When an atom loses electrons, it becomes:",
                    "choices": ["A negative ion", "A neutral atom", "An isotope", "A positive ion"],
                    "answer": 3,
                    "explain": "Losing negative electrons leaves more positive protons than electrons — a positive ion (cation). Gaining electrons makes a negative ion (anion); the element itself never changes.",
                },
            ],
            "flashcards": [
                ("Why do atoms bond?", "To reach a full outer electron shell — the octet rule."),
                ("Ionic bond in one line", "A metal transfers electrons to a nonmetal; opposite charges attract."),
                ("Covalent bond in one line", "Two atoms (usually nonmetals) share electron pairs."),
                ("Metallic bond in one line", "Metal atoms pool their valence electrons into a mobile sea."),
                ("Cation vs anion", "Cation = positive (lost electrons); anion = negative (gained electrons)."),
                ("Signature of an ionic compound", "A metal bonded to a nonmetal, e.g., NaCl."),
                ("Properties of ionic compounds", "Hard crystals, high melting points, conduct when dissolved in water."),
                ("Properties of covalent compounds", "Molecules with lower melting/boiling points; don't conduct."),
                ("What is a polar covalent bond?", "Unequal sharing — the more electronegative atom pulls harder, like oxygen in water."),
                ("Why do metals bend instead of shatter?", "The electron sea lets atoms slide past each other without breaking the bonding."),
            ],
            "faqs": [
                ("What's the difference between ionic and covalent bonds?",
                 "Ionic bonds transfer electrons from a metal to a nonmetal, making charged ions that lock into crystals. Covalent bonds share electrons between nonmetals, making discrete molecules. Transfer vs share is the whole distinction — and metal + nonmetal vs nonmetal + nonmetal predicts it."),
                ("Why does salt dissolve in water but oil doesn't?",
                 "Water is polar, so its slightly charged ends pull Na+ and Cl− ions apart — polar dissolves ionic and polar. Oil is nonpolar, so it ignores charged stuff and mixes only with other nonpolar molecules: like dissolves like."),
                ("Is a covalent bond stronger than an ionic bond?",
                 "Individually, covalent bonds are often stronger, but ionic compounds stack millions of attractions into a crystal, giving them high melting points. Test questions usually mean melting point when they say strength — ionic wins there."),
                ("How can I tell the bond type from a formula?",
                 "Check the elements. Metal + nonmetal (NaCl, MgO) = ionic. Nonmetal + nonmetal (H2O, CO2) = covalent. Metal + metal or a pure metal = metallic. For precision, an electronegativity difference above about 1.7 points to ionic."),
            ],
            "paa": [
                ("What is the octet rule?", "Atoms gain, lose or share electrons to end up with 8 in their outer shell — the stable arrangement noble gases already have."),
                ("Why is water a polar molecule?", "Oxygen pulls the shared electrons much harder than hydrogen, leaving oxygen slightly negative and the hydrogens slightly positive — an unequal-share (polar covalent) bond plus a bent shape."),
                ("What holds a metal together?", "A sea of shared, freely moving valence electrons surrounding positive metal ions — that's why metals conduct, bend and shine."),
                ("What are polyatomic ions?", "Groups of covalently bonded atoms that carry a net charge, like SO4 2− or NO3− — they act as single charged units inside ionic compounds."),
            ],
        },
        {
            "slug": "chemical-reactions",
            "title": "Chemical Reactions",
            "h1": "Chemical Reactions: Types & Balancing Equations",
            "meta_title": "Balancing Equations & Reaction Types | StudyBonk",
            "meta_description": "Learn chemical reactions free: the 5 reaction types, conservation of mass and balancing equations step by step. Flashcards, worked examples, quiz. No sign-up.",
            "summary": "The five reaction types and balancing equations step by step — with worked examples at every stage.",
            "keywords": [
                "chemical reactions basics",
                "balancing equations help",
                "types of chemical reactions",
                "law of conservation of mass",
                "reactants and products",
                "free chemistry quiz",
            ],
            "longtail": [
                "how to balance chemical equations step by step",
                "what are the five types of chemical reactions",
                "what does the law of conservation of mass mean",
                "synthesis vs decomposition reaction examples",
                "single vs double replacement reactions difference",
                "what is a combustion reaction",
                "why do chemical equations need to be balanced",
                "difference between coefficients and subscripts",
                "how to know a chemical reaction has occurred",
                "what do the state symbols mean in equations",
            ],
            "sections": [
                {
                    "h2": "What a chemical reaction is",
                    "paras": [
                        "A chemical reaction is a rearrangement of atoms: bonds break, new bonds form, and you end up with different substances. The starting materials are the reactants (left of the arrow) and the new substances are the products (right of it). Burning wood, rusting iron and baking a cake are all reactions — matter hasn't vanished, it has been rearranged.",
                        "The rule that governs every equation is the law of conservation of mass: atoms are neither created nor destroyed. Whatever atoms go in must come out — same elements, same counts. That single law is why we balance equations at all: an unbalanced equation is literally claiming that atoms appeared out of nowhere.",
                    ],
                    "bullets": [
                        "Reactants → products: atoms rearranged, never destroyed",
                        "Law of conservation of mass: atoms in = atoms out",
                        "Chemical change makes a new substance; physical change doesn't",
                        "Signs of a reaction: color change, gas bubbles, precipitate, heat or light",
                    ],
                },
                {
                    "h2": "The five reaction types",
                    "paras": [
                        "Most school reactions fall into five patterns. Synthesis (combination): A + B → AB — two things join. Decomposition: AB → A + B — one thing breaks apart. Single replacement: A + BC → AC + B — one element kicks another out. Double replacement: AB + CD → AD + CB — two compounds swap partners. Combustion: a fuel burns with oxygen, producing CO2 and H2O.",
                        "Identifying the type is pattern-matching, not deep chemistry. Count the pieces: two into one is synthesis, one into two is decomposition. Two compounds trading pieces is double replacement. If oxygen is a reactant and the products include CO2 and water, it's combustion. Learn each pattern's silhouette and categorizing takes seconds.",
                    ],
                    "bullets": [
                        "Synthesis: A + B → AB (building up)",
                        "Decomposition: AB → A + B (breaking down)",
                        "Single replacement: A + BC → AC + B (one element swaps in)",
                        "Double replacement: AB + CD → AD + CB (partners swap)",
                        "Combustion: fuel + O2 → CO2 + H2O (burning)",
                    ],
                    "example": {
                        "title": "Worked example: name the reaction type",
                        "body": "CaCO3 → CaO + CO2: one compound becomes two — decomposition. Zn + CuSO4 → ZnSO4 + Cu: zinc replaces copper — single replacement. CH4 + 2O2 → CO2 + 2H2O: a fuel plus oxygen giving CO2 and water — combustion. Count the pieces, spot the pattern, done.",
                    },
                },
                {
                    "h2": "Balancing equations step by step",
                    "paras": [
                        "Balancing means adding coefficients — the big numbers in front of formulas — until the atom counts match on both sides. You never change subscripts, the little numbers inside formulas, because that would change the substance itself. H2O and H2O2 are different chemicals; balancing by touching subscripts is the classic error.",
                        "The method: write the equation, count each element's atoms on both sides, and adjust coefficients one element at a time, saving hydrogen and oxygen for last since they appear in several compounds. Finish with a full recount. For H2 + O2 → H2O: oxygen is unbalanced (2 in, 1 out), so put a 2 in front of H2O; then rebalance hydrogen with a 2 in front of H2. Result: 2H2 + O2 → 2H2O.",
                    ],
                    "bullets": [
                        "Change coefficients (front numbers), never subscripts",
                        "Count every element on both sides before and after",
                        "Balance H and O last — they appear in multiple compounds",
                        "Finish with a complete recount; one unbalanced atom fails everything",
                    ],
                    "example": {
                        "title": "Worked example: balance CH4 + O2 → CO2 + H2O",
                        "body": "Carbon: 1 on each side, done. Hydrogen: 4 in (CH4) but only 2 in one H2O — put a 2 in front of H2O: now H = 4 = 4. Oxygen: right side now has 2 + 2 = 4, left has 2 — put a 2 in front of O2. Final: CH4 + 2O2 → CO2 + 2H2O. Recount every element: 1 C, 4 H, 4 O on both sides. Balanced.",
                    },
                },
                {
                    "h2": "Reading equations like a chemist",
                    "paras": [
                        "A balanced equation tells a story with numbers. The coefficients are ratios: 2H2 + O2 → 2H2O means two hydrogen molecules react with one oxygen molecule to make two water molecules — or, scaled up, 2 moles with 1 mole makes 2 moles. Those ratios are the foundation of stoichiometry, the next page in this hub.",
                        "Equations also carry state symbols: (s) solid, (l) liquid, (g) gas and (aq) aqueous, meaning dissolved in water. They look decorative but matter — a precipitate forms when two aqueous solutions produce a solid, and gas bubbling out is one of the signs a reaction actually happened. Read the equation as a sentence and the symbols become information, not decoration.",
                    ],
                    "bullets": [
                        "Coefficients are mole ratios (the bridge to stoichiometry)",
                        "State symbols: (s), (l), (g), and (aq) = dissolved in water",
                        "Precipitate: a solid formed from two aqueous solutions",
                        "Unbalanced equations can't be used for calculations",
                    ],
                },
            ],
            "key_concepts": [
                ("Chemical reaction", "A process that rearranges atoms into new substances with new properties."),
                ("Reactant", "A starting substance, written left of the arrow."),
                ("Product", "A new substance formed by the reaction, written right of the arrow."),
                ("Conservation of mass", "Atoms are neither created nor destroyed — the reason equations must balance."),
                ("Coefficient", "The number in front of a formula; multiplies the whole formula when balancing."),
                ("Subscript", "The small number inside a formula; changing it changes the substance."),
                ("Synthesis reaction", "Two or more reactants combine into one product: A + B → AB."),
                ("Combustion reaction", "A fuel reacts with oxygen, producing carbon dioxide and water."),
            ],
            "study_tips": [
                "Write an atom-count table (element | left | right) under every equation you balance — invisible counting causes most errors.",
                "Remember the golden rule out loud: coefficients change, subscripts never do.",
                "Balance hydrogen and oxygen last, especially in combustion problems.",
                "Learn the five types as silhouettes (2→1, 1→2, swap one, swap two, burn) and classify by shape.",
                "Finish every balancing problem with a full recount — the last check catches the sneaky O or H you forgot.",
            ],
            "practice": [
                {
                    "q": "What is the balanced form of H2 + O2 → H2O?",
                    "choices": ["H2 + O2 → H2O", "2H2 + O2 → 2H2O", "H2 + 2O2 → 2H2O", "2H2 + 2O2 → 2H2O"],
                    "answer": 1,
                    "explain": "Left side has 2 H and 2 O, so we need 2 H2O on the right (4 H, 2 O) — which forces 2H2 on the left. Check: 4 H and 2 O on both sides. Balanced.",
                },
                {
                    "q": "CaCO3 → CaO + CO2 is what type of reaction?",
                    "choices": ["Synthesis", "Combustion", "Decomposition", "Double replacement"],
                    "answer": 2,
                    "explain": "One compound breaks into two products — the decomposition silhouette (1 → 2). Two things joining would be synthesis.",
                },
                {
                    "q": "In a balanced equation, the number of atoms of each element:",
                    "choices": ["Is equal on both sides", "Is always greater in the reactants", "Is always greater in the products", "Doesn't matter"],
                    "answer": 0,
                    "explain": "Conservation of mass demands it: atoms can't be created or destroyed, so every element must match left and right. That's the definition of balanced.",
                },
                {
                    "q": "Which observation is a sign that a chemical reaction occurred?",
                    "choices": ["Ice melting", "Water evaporating", "Sugar dissolving in tea", "A solid forming when two clear solutions mix"],
                    "answer": 3,
                    "explain": "A new solid from two solutions is a precipitate — evidence of a new substance. Melting, evaporating and dissolving are physical changes: same substance, different form.",
                },
            ],
            "flashcards": [
                ("What does the arrow in an equation mean?", "Yields — reactants become products."),
                ("Law of conservation of mass", "Atoms are neither created nor destroyed; equations must reflect it."),
                ("What is a coefficient?", "The number in front of a formula — the number you change when balancing."),
                ("What is a subscript?", "The small number inside a formula — never change it when balancing."),
                ("Synthesis reaction", "A + B → AB (two things join into one)."),
                ("Decomposition reaction", "AB → A + B (one compound breaks apart)."),
                ("Single replacement", "A + BC → AC + B (one element kicks out another)."),
                ("Double replacement", "AB + CD → AD + CB (two compounds swap partners)."),
                ("Combustion reaction", "Fuel + O2 → CO2 + H2O (burning in oxygen)."),
                ("What does (aq) mean?", "Aqueous — dissolved in water."),
            ],
            "faqs": [
                ("Why do chemical equations have to be balanced?",
                 "Because of conservation of mass: atoms can't be created or destroyed, so every atom among the reactants must appear among the products. Balancing makes the equation honest — and only balanced equations can be used for calculations."),
                ("What's the difference between a coefficient and a subscript?",
                 "A subscript is part of the formula (the 2 in H2O — water always has 2 hydrogens). A coefficient multiplies the whole formula (2H2O means two water molecules). Subscripts describe substances; coefficients count them."),
                ("How do I know a chemical reaction happened?",
                 "Look for the evidence: a color change, gas bubbles, a solid precipitate forming, or energy change like heat, light or flame. If nothing new appeared, it was probably just a physical change."),
                ("What's the fastest way to identify a reaction type?",
                 "Count the players. Two into one is synthesis; one into two is decomposition; an element plus a compound is single replacement; two compounds trading partners is double replacement; anything with O2 making CO2 and H2O is combustion."),
            ],
            "paa": [
                ("How do you balance a chemical equation?", "Count atoms of each element on both sides, adjust only coefficients one element at a time (hydrogen and oxygen last), then recount everything to confirm."),
                ("What are the signs of a chemical change?", "Color change, gas bubbles, precipitate forming, and heat or light released — any evidence a new substance appeared."),
                ("What is the difference between a physical and chemical change?", "Physical changes rearrange molecules without making new substances (ice melting); chemical changes create new substances with new properties (iron rusting)."),
                ("What is a precipitate?", "A solid that forms suddenly when two solutions react — one of the clearest visible signs a double replacement reaction occurred."),
            ],
        },
        {
            "slug": "moles-and-stoichiometry",
            "title": "Moles & Stoichiometry",
            "h1": "The Mole & Stoichiometry Explained (Without the Panic)",
            "meta_title": "Moles and Stoichiometry Made Simple | StudyBonk",
            "meta_description": "The mole explained for real: Avogadro's number, molar mass and stoichiometry step by step with worked examples. Free flashcards and quiz, no sign-up.",
            "summary": "Avogadro's number, molar mass and the three conversions that solve almost every mole problem.",
            "keywords": [
                "mole chemistry help",
                "stoichiometry explained",
                "avogadro's number",
                "molar mass",
                "grams to moles conversion",
                "free chemistry practice",
            ],
            "longtail": [
                "what is a mole in chemistry explained simply",
                "how to convert grams to moles step by step",
                "how to calculate molar mass easily",
                "what is avogadro's number used for",
                "stoichiometry for beginners made easy",
                "how to use mole ratios from an equation",
                "what is a limiting reactant in simple terms",
                "how many particles are in one mole",
                "why is the mole so confusing",
                "grams to particles conversion practice",
            ],
            "sections": [
                {
                    "h2": "The mole is just a counting word",
                    "paras": [
                        "A mole is chemistry's version of 'a dozen' — except instead of 12, it means 6.022 × 10²³ particles. That absurdly specific number is Avogadro's number, and it wasn't chosen at random: 6.022 × 10²³ carbon-12 atoms happens to weigh exactly 12 grams. That coincidence (by design) makes the mole the bridge between the atomic world of particles and the human world of grams you can actually weigh.",
                        "Here's the emotional unlock: you never count atoms directly — they're too small. You weigh them. The mole is the exchange rate that converts 'number of particles' into 'grams on a scale' and back. Whenever a problem mentions particles, atoms or molecules on one side and grams on the other, the mole is the middleman making the trade.",
                    ],
                    "bullets": [
                        "1 mole = 6.022 × 10²³ particles (Avogadro's number)",
                        "It's a counting word, like dozen = 12 or pair = 2",
                        "1 mole of carbon-12 weighs exactly 12 grams — the whole point",
                        "The mole connects the particle world to the weighable world",
                    ],
                },
                {
                    "h2": "Molar mass: grams per mole",
                    "paras": [
                        "Molar mass is the mass of one mole of a substance, in grams per mole — and the beautiful part is that the periodic table already tells you. Oxygen's box says 16.00, so one mole of oxygen atoms weighs 16.00 grams. For compounds, add up each element's mass times how many of it you have: water, H2O, is 2(1.008) + 16.00 = 18.02 g/mol.",
                        "Molar mass is the universal conversion factor between grams and moles. Grams ÷ molar mass = moles, and moles × molar mass = grams. Write the units on every step and they cancel like fractions, telling you whether to multiply or divide. Most mole mistakes aren't chemistry mistakes — they're unit bookkeeping slips.",
                    ],
                    "bullets": [
                        "Molar mass = grams per mole, read straight off the periodic table",
                        "Compounds: add each element's mass times its count",
                        "H2O = 2(1.008) + 16.00 = 18.02 g/mol",
                        "Grams ÷ molar mass = moles · moles × molar mass = grams",
                    ],
                    "example": {
                        "title": "Worked example: molar mass of CO2",
                        "body": "Carbon: 12.01. Oxygen: 16.00 each, and there are two: 2 × 16.00 = 32.00. Total: 12.01 + 32.00 = 44.01 g/mol. So one mole of CO2 — that's 6.022 × 10²³ molecules — weighs 44.01 grams, roughly the mass of a small chocolate bar, but containing an unimaginable number of molecules.",
                    },
                },
                {
                    "h2": "The three conversions that solve most problems",
                    "paras": [
                        "Nearly every mole problem is one of three moves. (1) Grams → moles: divide by molar mass. (2) Moles → particles: multiply by Avogadro's number. (3) The reverse of each. Chain them and you can go from grams to particles or back in two steps, with moles always in the middle — the mole tunnel.",
                        "Set up conversions as unit-fraction chains so the units cancel visibly. To find how many molecules are in 36.0 g of water: 36.0 g ÷ 18.02 g/mol = 2.00 mol, then 2.00 mol × 6.022 × 10²³ molecules/mol = 1.20 × 10²⁴ molecules. The grams cancel to moles, then moles cancel to particles. If your units don't cancel to the target, you flipped a fraction — that single check catches most errors.",
                    ],
                    "bullets": [
                        "Grams ↔ moles: use molar mass",
                        "Moles ↔ particles: use Avogadro's number (6.022 × 10²³)",
                        "Always travel through moles — never grams straight to particles",
                        "Units must cancel visibly; if they don't, flip a fraction",
                    ],
                },
                {
                    "h2": "Stoichiometry: equations as recipes",
                    "paras": [
                        "A balanced equation is a recipe: the coefficients tell you how many moles of each ingredient combine. In 2H2 + O2 → 2H2O, the hydrogen-to-water ratio is 2:2 and the oxygen-to-water ratio is 1:2. Stoichiometry questions just ask you to scale the recipe — like doubling a cake recipe, but with moles.",
                        "The universal setup for all stoichiometry: grams of A → moles of A (molar mass) → moles of B (coefficient ratio from the equation) → grams of B (molar mass of B). Three bridges, always in the same order. The limiting-reactant wrinkle: whichever ingredient runs out first caps the output, exactly like running out of flour mid-recipe — no flour, no more cake, no matter how much sugar is left.",
                    ],
                    "bullets": [
                        "Balanced coefficients = the recipe's mole ratios",
                        "The chain: grams A → moles A → moles B → grams B",
                        "Convert to moles BEFORE using the equation's ratios",
                        "Limiting reactant = the ingredient that runs out first; it sets the maximum product",
                    ],
                    "example": {
                        "title": "Worked example: how much water from 8.00 g of O2?",
                        "body": "Step 1: 8.00 g O2 ÷ 32.00 g/mol = 0.250 mol O2. Step 2: the equation 2H2 + O2 → 2H2O says 1 mol O2 makes 2 mol H2O, so 0.250 × 2 = 0.500 mol H2O. Step 3: 0.500 mol × 18.02 g/mol = 9.01 g of water. Grams to moles, ratio jump, moles to grams — every stoichiometry problem is this same staircase.",
                    },
                },
            ],
            "key_concepts": [
                ("Mole", "A counting unit equal to 6.022 × 10²³ particles — chemistry's dozen."),
                ("Avogadro's number", "6.022 × 10²³ — the number of particles in one mole of anything."),
                ("Molar mass", "The mass of one mole of a substance in grams; read from the periodic table."),
                ("Mole ratio", "The ratio of coefficients between two substances in a balanced equation."),
                ("Stoichiometry", "Using balanced equations and mole ratios to calculate amounts of reactants and products."),
                ("Limiting reactant", "The reactant that runs out first; it determines the maximum product possible."),
                ("Excess reactant", "The ingredient left over after the limiting reactant is used up."),
                ("Theoretical yield", "The maximum amount of product calculated from the limiting reactant."),
            ],
            "study_tips": [
                "Anchor the mole in one sentence: 'a dozen = 12, a mole = 6.022 × 10²³' — say it until the panic fades.",
                "Write units on every single step and watch them cancel; the units do the thinking for you.",
                "Always convert to moles before touching the equation's ratios — grams never jump directly across.",
                "Practice molar mass with random compounds from a shampoo bottle until it's a 15-second calculation.",
                "Memorize the staircase: grams → moles → moles → grams. Every stoichiometry problem walks it.",
            ],
            "practice": [
                {
                    "q": "One mole of any substance contains how many particles?",
                    "choices": ["6.022 × 10²³", "12", "3.14 × 10⁸", "100"],
                    "answer": 0,
                    "explain": "Avogadro's number: 6.022 × 10²³ particles per mole — true for atoms, molecules or ions, of any substance. That's the definition of the mole.",
                },
                {
                    "q": "What is the molar mass of H2O? (H = 1.008, O = 16.00)",
                    "choices": ["17.01 g/mol", "18.02 g/mol", "16.00 g/mol", "33.02 g/mol"],
                    "answer": 1,
                    "explain": "Two hydrogens and one oxygen: 2(1.008) + 16.00 = 2.016 + 16.00 = 18.02 g/mol. Forgetting to double the hydrogen gives the classic wrong answer, 17.01.",
                },
                {
                    "q": "How many moles are in 88.02 g of CO2 (molar mass 44.01 g/mol)?",
                    "choices": ["0.5 mol", "44.01 mol", "2 mol", "4 mol"],
                    "answer": 2,
                    "explain": "Moles = grams ÷ molar mass = 88.02 ÷ 44.01 = 2 mol. The units tell you to divide: grams over grams-per-mole leaves plain moles.",
                },
                {
                    "q": "In N2 + 3H2 → 2NH3, how many moles of NH3 form from 3 moles of N2 (with plenty of H2)?",
                    "choices": ["2", "3", "4", "6"],
                    "answer": 3,
                    "explain": "The ratio N2:NH3 is 1:2. Three moles of N2 × (2 NH3 / 1 N2) = 6 moles of ammonia. Read coefficients as a recipe and scale it.",
                },
            ],
            "flashcards": [
                ("What is a mole?", "A counting unit: 6.022 × 10²³ particles — like a dozen, but for atoms."),
                ("Avogadro's number", "6.022 × 10²³ particles per mole."),
                ("What is molar mass?", "The mass of one mole in grams — read from the periodic table."),
                ("Molar mass of H2O", "18.02 g/mol (2 × 1.008 + 16.00)."),
                ("Grams → moles", "Divide grams by molar mass."),
                ("Moles → grams", "Multiply moles by molar mass."),
                ("Moles → particles", "Multiply by Avogadro's number."),
                ("What is a mole ratio?", "The coefficient ratio between two substances in a balanced equation."),
                ("The stoichiometry staircase", "grams A → moles A → moles B → grams B."),
                ("What is a limiting reactant?", "The reactant that runs out first; it caps how much product can form."),
            ],
            "faqs": [
                ("What is a mole in chemistry, in simple words?",
                 "A counting word. Just as a dozen means 12, a mole means 6.022 × 10²³ particles. It exists because atoms are too small to count one by one, but 6.022 × 10²³ of them has a convenient mass in grams you can weigh."),
                ("Why is the mole so confusing?",
                 "Because it mixes a huge abstract number with unit conversions most students never fully drilled. Fix both pieces separately: first accept 'mole = 6.022 × 10²³, like dozen = 12,' then practice the grams↔moles↔particles conversions with units written out. It stops being scary within a week of short daily practice."),
                ("How do I calculate molar mass quickly?",
                 "Count the atoms of each element in the formula, multiply each by its periodic-table mass, and add. H2SO4 = 2(1.008) + 32.06 + 4(16.00) = 98.08 g/mol. Fifteen seconds once you've practiced on a dozen compounds."),
                ("What is the limiting reactant, simply?",
                 "The ingredient that runs out first. Just like a recipe, the output is capped by whatever you exhaust — if you have tons of bread but one slice of cheese, you make one sandwich. Everything else is excess."),
            ],
            "paa": [
                ("How many particles are in one mole?", "6.022 × 10²³ — always, for any substance: atoms, molecules or ions. That number is Avogadro's number."),
                ("How do you convert grams to moles?", "Divide the mass by the molar mass: moles = grams ÷ g/mol. Example: 36.0 g of water ÷ 18.02 g/mol = 2.00 moles."),
                ("Why do we use moles instead of grams in equations?", "Chemical equations describe particle ratios, not gram ratios. Converting everything to moles puts quantities into the equation's own language, letting the coefficients do the scaling."),
                ("What is the difference between molar mass and molecular mass?", "Same number, different units and framing: molecular mass is one molecule's mass in atomic mass units; molar mass is one mole's mass in grams. Numerically identical for a given substance."),
            ],
        },
        {
            "slug": "acids-and-bases",
            "title": "Acids & Bases",
            "h1": "Acids & Bases Explained: pH Scale & Neutralization",
            "meta_title": "Acids, Bases and the pH Scale Made Easy | StudyBonk",
            "meta_description": "Learn acids and bases free: H+ ions, the pH scale, neutralization reactions and everyday examples. Free flashcards, worked examples and quiz. No sign-up.",
            "summary": "What acids and bases are, how the pH scale works and what happens when they meet.",
            "keywords": [
                "acids and bases basics",
                "ph scale explained",
                "neutralization reaction",
                "acid vs base examples",
                "what is ph",
                "free chemistry quiz",
            ],
            "longtail": [
                "what is the difference between an acid and a base",
                "how does the ph scale work",
                "what happens when an acid reacts with a base",
                "examples of acids and bases in everyday life",
                "is ph 3 more acidic than ph 5",
                "what do antacids do chemically",
                "what is a neutralization reaction in simple terms",
                "how does litmus paper indicate acids and bases",
                "what does it mean for a solution to be neutral",
                "why is blood ph 7.4 important",
            ],
            "sections": [
                {
                    "h2": "What makes something an acid or a base",
                    "paras": [
                        "Acids and bases are opposite personalities defined by one particle: the hydrogen ion, H+. An acid is a substance that releases H+ in water — a proton donor. A base accepts H+, most commonly by releasing hydroxide ions, OH−, which mop up free H+. That single push-pull over hydrogen ions is the entire acid-base story.",
                        "You can often identify them without a test kit. Acids taste sour (citric acid in lemons, acetic acid in vinegar), turn blue litmus paper red and dissolve reactive metals. Bases taste bitter, feel slippery — they're mildly dissolving your skin, and soap is a base — and turn red litmus blue. In a lab, never taste anything: use indicators or pH paper.",
                    ],
                    "bullets": [
                        "Acid: releases H+ ions (a proton donor)",
                        "Base: accepts H+, usually by releasing OH−",
                        "Acid traits: sour, blue litmus turns red, reacts with metals",
                        "Base traits: bitter, slippery, red litmus turns blue",
                        "Never taste to test — use an indicator",
                    ],
                },
                {
                    "h2": "The pH scale",
                    "paras": [
                        "The pH scale measures how acidic or basic a solution is, from 0 to 14. Seven is neutral (pure water). Below 7 is acidic — and the lower the number, the stronger the acid. Above 7 is basic (also called alkaline). Each pH step is a tenfold change: pH 3 is ten times more acidic than pH 4 and one hundred times more acidic than pH 5. That exponential part is what makes pH counterintuitive.",
                        "Technically pH tracks H+ concentration — low pH means lots of it. For quick anchoring, memorize stations along the scale: stomach acid ~2, lemon juice ~2-3, black coffee ~5, pure water 7, blood 7.4 (a number your body defends fiercely), baking soda solution ~9, ammonia ~11, drain cleaner ~14. Real-world examples are exactly how pH questions get asked.",
                    ],
                    "bullets": [
                        "pH 0-14: below 7 acid, 7 neutral, above 7 base",
                        "Each unit = a 10× change in strength",
                        "pH 3 is 100× more acidic than pH 5",
                        "Blood sits at 7.4 — homeostasis guards that number",
                    ],
                    "example": {
                        "title": "Worked example: comparing strengths",
                        "body": "Solution A has pH 2; solution B has pH 5. How much more acidic is A? Count the steps: 2 → 3 → 4 → 5 is three steps, each worth 10×. So 10 × 10 × 10 = 1,000. A is a thousand times more acidic. pH differences always multiply, never add.",
                    },
                },
                {
                    "h2": "Neutralization: acid meets base",
                    "paras": [
                        "Mix an acid and a base and they neutralize each other: the acid's H+ combines with the base's OH− to form plain water. Whatever ions are left over pair up as a salt. The general equation is always the same: acid + base → salt + water. Hydrochloric acid + sodium hydroxide → sodium chloride + water — heartburn chemistry meets drain cleaner and the result is salt water.",
                        "This reaction is why antacids work: your stomach sits around pH 2, and antacid tablets are mild bases that nudge it back toward comfortable. Farmers spread lime (a base) on acidic soil, and lakes damaged by acid rain are sometimes treated with limestone. Neutralization is chemistry's most useful reset button, applied anywhere pH has drifted too far.",
                    ],
                    "bullets": [
                        "Acid + base → salt + water, every time",
                        "H+ + OH− → H2O is the heart of the reaction",
                        "Antacids are bases neutralizing excess stomach acid",
                        "Equal moles of strong acid and base land near pH 7",
                    ],
                },
                {
                    "h2": "Acids and bases in your daily life",
                    "paras": [
                        "You swim in acid-base chemistry daily. On the acid side: citric acid in citrus, acetic acid in vinegar, carbonic acid in fizzy drinks (the bubbles are that acid decomposing), lactic acid in yogurt and tired muscles. On the base side: sodium hydroxide in drain and oven cleaners, ammonia in glass cleaner, and sodium bicarbonate — baking soda — as an antacid, cleaner and deodorizer.",
                        "Two notes worth more points than they cost. 'Strong' technically means fully ionized, not dangerously concentrated — a strong acid at high dilution can be gentler than a concentrated weak acid. And never mix household cleaners: bleach plus ammonia releases toxic chloramine gas. The chemistry that cleans your kitchen can also hurt you, which is exactly why it's worth understanding.",
                    ],
                    "bullets": [
                        "Acids around you: citrus, vinegar, soda fizz, yogurt",
                        "Bases around you: soap, baking soda, ammonia, drain cleaner",
                        "'Strong' means fully ionized — not automatically more hazardous at all dilutions",
                        "Never mix bleach and ammonia — toxic gas forms",
                    ],
                },
            ],
            "key_concepts": [
                ("Acid", "A substance that releases H+ ions in water; turns blue litmus red."),
                ("Base", "A substance that accepts H+, usually releasing OH−; turns red litmus blue."),
                ("pH scale", "A 0-14 measure of acidity; 7 neutral, below acidic, above basic."),
                ("Neutralization", "Acid + base → salt + water, as H+ and OH− combine."),
                ("Salt", "The ionic compound left over after neutralization, like NaCl."),
                ("Indicator", "A substance, like litmus, that changes color to reveal acid or base."),
                ("Hydrogen ion (H+)", "The particle acids release and bases capture — the heart of all acid-base chemistry."),
                ("Alkali", "A base that dissolves in water, releasing OH− ions."),
            ],
            "study_tips": [
                "Anchor the scale with landmarks (stomach 2, water 7, blood 7.4, ammonia 11) — recall beats calculating.",
                "Remember each pH step multiplies by 10 — practice 'how many times more acidic' questions until automatic.",
                "Learn neutralization as one formula: acid + base → salt + water. It never changes.",
                "Study one everyday example per concept (antacid, lemon, soap) — concrete examples stick to test questions.",
                "Drill litmus directions with flashcards: acids turn blue to red, bases turn red to blue.",
            ],
            "practice": [
                {
                    "q": "A solution has a pH of 3. It is:",
                    "choices": ["Basic", "Neutral", "Acidic", "A salt"],
                    "answer": 2,
                    "explain": "Anything below 7 on the pH scale is acidic — and pH 3 is strongly acidic. Neutral is exactly 7; above 7 is basic.",
                },
                {
                    "q": "What are the two products of a neutralization reaction?",
                    "choices": ["Salt and water", "Two acids", "Hydrogen gas and salt", "Water and oxygen"],
                    "answer": 0,
                    "explain": "The acid's H+ joins the base's OH− to make water, and the leftover ions form a salt: acid + base → salt + water, no exceptions in this course.",
                },
                {
                    "q": "How many times more acidic is pH 2 than pH 5?",
                    "choices": ["3", "30", "100", "1,000"],
                    "answer": 3,
                    "explain": "Three pH steps (2→3→4→5), each worth a factor of 10: 10 × 10 × 10 = 1,000 times more acidic. pH differences multiply, never add.",
                },
                {
                    "q": "Which everyday substance is a base?",
                    "choices": ["Lemon juice", "Baking soda", "Vinegar", "Soda"],
                    "answer": 1,
                    "explain": "Baking soda (sodium bicarbonate) is a mild base — that's why it calms acidic stomachs. Lemon juice, vinegar and soda are all acids.",
                },
            ],
            "flashcards": [
                ("What is an acid?", "A substance that releases H+ ions in water; tastes sour, turns blue litmus red."),
                ("What is a base?", "A substance that accepts H+ (often releasing OH−); feels slippery, turns red litmus blue."),
                ("What is pH?", "A 0-14 scale of acidity: below 7 acid, 7 neutral, above 7 base."),
                ("What does one pH unit mean?", "A 10× change in acidity — pH 4 is ten times more acidic than pH 5."),
                ("pH of pure water", "7 — neutral."),
                ("pH of blood", "About 7.4 — slightly basic, and tightly maintained."),
                ("Neutralization equation", "Acid + base → salt + water."),
                ("What is an indicator?", "A substance that changes color in acids vs bases — litmus is the classic."),
                ("What is a salt?", "The ionic compound left after neutralization — table salt, NaCl, is the famous example."),
                ("Why do antacids work?", "They're mild bases that neutralize excess stomach acid, raising pH toward comfort."),
            ],
            "faqs": [
                ("What is the difference between an acid and a base?",
                 "An acid releases H+ ions in water; a base accepts them (usually by releasing OH−). Acids taste sour and turn blue litmus red; bases feel slippery and turn red litmus blue. One donates hydrogen ions, the other collects them."),
                ("Is pH 3 twice as acidic as pH 6?",
                 "No — a thousand times. Each pH unit is a factor of 10, so three units apart means 10 × 10 × 10 = 1,000. pH is a logarithmic scale, which is why small numbers mean big differences."),
                ("Why do acids and bases neutralize each other?",
                 "Because the acid's H+ and the base's OH− are perfect partners: they combine into H2O, plain water. Once the free ions pair off, neither acidic nor basic character remains — just salt water."),
                ("What's the difference between a strong acid and a weak acid?",
                 "A strong acid (like HCl) fully breaks apart into ions in water; a weak acid (like vinegar's acetic acid) only partially does. 'Strong' is about ionization, not concentration or danger."),
            ],
            "paa": [
                ("What has a pH of 7?", "Pure water — the neutral point of the scale, where H+ and OH− concentrations are equal."),
                ("What happens when you mix an acid and a base?", "Neutralization: H+ + OH− forms water, and the leftover ions form a salt. Mix equal amounts of a strong acid and base and you land near pH 7."),
                ("What are common household acids and bases?", "Acids: lemon juice, vinegar, soda, coffee. Bases: baking soda, soap, ammonia, bleach, drain cleaner."),
                ("Why is blood slightly basic?", "Blood's pH of about 7.4 keeps proteins working properly; enzymes lose their shape outside a narrow range. Your breathing and kidneys team up to hold that number — homeostasis in action."),
            ],
        },
    ],
}
