"""History pillar: 1 pillar page + 6 cluster pages.

Schema (must match exactly — see docs/CONTENT.md and content/topic_math.py):
PILLAR = {slug, title, emoji, meta_title<=62, meta_description<=160, h1,
tagline, summary, keywords[10], longtail[12+], intro[2 paras], bullets[6],
faqs[(q,a)x5], paa[(q,a)x5], clusters[{slug, title, h1, meta_title<=62,
meta_description<=160, summary, keywords[6], longtail[10+],
sections[3-4]{h2, paras[], bullets[], example?{title, body}},
key_concepts[(term,def)x8], study_tips[x5], practice[{q, choices[4],
answer(idx), explain}]x4, flashcards[(front,back)]x10, faqs[(q,a)x4],
paa[(q,a)x4]}]}
"""

PILLAR = {
    "slug": "history",
    "title": "History",
    "emoji": "🏛️",
    "meta_title": "Free History Study Hub — Learn History Fast | StudyBonk",
    "meta_description": "Free history study guides, flashcards and quizzes: ancient civilizations, revolutions, the World Wars and the Cold War. No sign-up, private, gamified.",
    "h1": "Free History Study Hub: Learn History Fast, One Bonk at a Time",
    "tagline": "From the pyramids to the fall of the Berlin Wall — free guides, decks and quizzes that make history finally stick.",
    "summary": "Free history guides, flashcard decks and practice quizzes for ancient civilizations through the Cold War and civil rights.",
    "keywords": [
        "history help",
        "learn history online free",
        "history flashcards",
        "world history study guide",
        "us history practice questions",
        "american revolution causes",
        "world war 1 explained",
        "cold war summary",
        "civil rights movement facts",
        "free study app",
    ],
    "longtail": [
        "how to memorize history dates and timelines",
        "best free website to learn history for students",
        "why do I keep failing history tests",
        "main causes of world war 1 explained simply",
        "how to remember the american revolution timeline",
        "what was the cold war in simple terms",
        "world war 2 causes and turning points summary",
        "civil rights movement timeline for students",
        "ancient civilizations quick summary for middle school",
        "how was rome different from greece",
        "difference between primary and secondary sources",
        "how to study history effectively for exams",
        "fall of the berlin wall explained for students",
    ],
    "intro": [
        "History isn't a pile of dates — it's a chain of causes and effects, and once you see the chain, the dates hang on it naturally. The problem is that most resources either drown you in names or compress everything into soulless bullet points. StudyBonk splits the difference: short, story-first lessons, flashcard decks that drill dates and terms, and quizzes that explain every answer.",
        "Every page below is 100% free, works without an account, and saves your progress right in your browser. Earn XP, keep your streak alive, and turn 'I hate memorizing this stuff' into 'wait, that actually makes sense.'",
    ],
    "bullets": [
        "Trace the rise of civilizations from Mesopotamia to Rome",
        "Explain the causes and outcomes of the American Revolution",
        "Master the MAIN causes and aftermath of World War I",
        "Understand how World War II happened — and what it left behind",
        "Explain containment, the crises and the end of the Cold War",
        "Know the key events and figures of the civil rights movement",
    ],
    "faqs": [
        ("Is StudyBonk good for studying history?",
         "Yes. StudyBonk gives you short lessons, spaced-repetition flashcard decks that drill dates, causes and terms, and practice quizzes with explanations. It's free, requires no account, and works offline after the first load."),
        ("How do I memorize history dates?",
         "Don't memorize a pile of random numbers — build a timeline skeleton with 4–6 anchor dates, then hang events onto it. Flashcards with spaced repetition keep the details; the story keeps the order. StudyBonk's decks are built exactly this way."),
        ("How much should I study history per day?",
         "Most students do best with 20–30 focused minutes a day. History rewards steady exposure: one era per session, flashcards to lock the terms, a quiz to prove it stuck."),
        ("Does StudyBonk replace my textbook or teacher?",
         "No — and it doesn't try to. Use StudyBonk to preview an era before class, drill causes and dates with flashcards, and practice with instant feedback. Your teacher handles depth and documents; StudyBonk handles the reps."),
        ("Is StudyBonk really free with no account?",
         "Really free, really no account. No ads, no paywalls, no email capture, no tracking. Everything saves in your browser's local storage, and the code is open-source on GitHub so you can verify it yourself."),
    ],
    "paa": [
        ("What is the fastest way to learn history?",
         "Learn causes and effects as a story, then drill the details with active recall — flashcards and self-quizzing — instead of re-reading. StudyBonk automates that loop."),
        ("Why do I keep failing history tests?",
         "Usually you're memorizing facts without the storyline connecting them. Learn the causes first — why events had to happen — then attach dates and names. Facts stick to stories."),
        ("How do you memorize timelines?",
         "Pick a few anchor dates and space everything else between them. Chunk by decade or era, and quiz yourself both directions: date → event and event → date."),
        ("What are the most important topics in history?",
         "At the survey level: ancient civilizations, the American Revolution, both World Wars, the Cold War and the civil rights movement. That's exactly the run of this pillar."),
        ("Is history just memorization?",
         "No — it's cause and effect with evidence. Dates and names are the vocabulary, but explaining why an event happened and what it caused is the actual skill tests measure."),
    ],
    "clusters": [
        {
            "slug": "ancient-civilizations",
            "title": "Ancient Civilizations",
            "h1": "Ancient Civilizations: Mesopotamia, Egypt, Greece & Rome",
            "meta_title": "Ancient Civilizations Overview — Free Guide | StudyBonk",
            "meta_description": "Master ancient civilizations free: Mesopotamia, Egypt, Greece and Rome — big ideas, key dates and terms with flashcards, a quiz and a timeline trick.",
            "summary": "Mesopotamia, Egypt, Greece and Rome — the big picture, key dates and the words tests love.",
            "keywords": [
                "ancient civilizations",
                "mesopotamia overview",
                "ancient egypt facts",
                "ancient greece government",
                "roman republic vs empire",
                "world history study guide",
            ],
            "longtail": [
                "what are the four early civilizations in order",
                "why did civilization start in river valleys",
                "what is the fertile crescent in simple terms",
                "difference between cuneiform and hieroglyphics",
                "what was hammurabi's code and why did it matter",
                "athens vs sparta differences for students",
                "what is a city-state in ancient greece",
                "how did the roman republic become an empire",
                "why did the roman empire fall for beginners",
                "what did rome borrow from greece",
                "ancient civilizations study guide for middle school",
            ],
            "sections": [
                {
                    "h2": "Mesopotamia and Egypt: civilization starts on rivers",
                    "paras": [
                        "The first civilizations grew where farming was easy, and farming was easiest in river valleys. Mesopotamia ('land between rivers' — the Tigris and Euphrates, in modern Iraq) gave the world the first writing, cuneiform, pressed into clay around 3200 BCE, plus the wheel, irrigation and written law under Hammurabi's Code. Egypt grew along the predictable Nile, unified under pharaohs treated as gods, building pyramids as tombs and writing in hieroglyphics.",
                        "Notice the pattern both share: surplus food → bigger populations → cities, specialized jobs, organized religion, government and writing. Historians use that checklist to decide when a society counts as a 'civilization.' Rivers made the food surplus possible, which is why 'first civilizations = river valleys' is a test favorite.",
                    ],
                    "bullets": [
                        "Mesopotamia: Tigris and Euphrates — cuneiform, the wheel, Hammurabi's Code",
                        "Egypt: the Nile — pharaohs, pyramids, hieroglyphics",
                        "Civilization checklist: cities, government, religion, writing, specialized jobs",
                        "Both began around 3000 BCE in the Fertile Crescent region",
                    ],
                    "example": {
                        "title": "How to remember this timeline",
                        "body": "Anchor the chapter with two bookends: writing begins around 3200 BCE and Rome falls in 476 CE — nearly 3,700 years apart. Then place the middle in order M-E-G-R: Mesopotamia, Egypt, Greece, Rome. Say it as 'Many Elephants Get Ready' and you'll never scramble the order again.",
                    },
                },
                {
                    "h2": "Greece: city-states, democracy and philosophy",
                    "paras": [
                        "Ancient Greece wasn't one country — it was hundreds of independent city-states (poleis), often fighting each other. The two you must know are opposites: Athens, the sea-trading democracy where citizens voted directly on laws, and Sparta, the inland military state where boys trained for war from age seven. Their alliance beat the Persian invasions, then they turned on each other in the Peloponnesian War, weakening them both.",
                        "Greece's golden age (roughly 450–350 BCE) packed in philosophy (Socrates taught Plato, who taught Aristotle), history, drama, geometry and the Olympics. Alexander the Great later spread Greek culture across a huge empire — the reason 'Hellenistic' ideas show up from Egypt to India. Rome then copied freely: Greek gods with new names, Greek architecture, Greek philosophy.",
                    ],
                    "bullets": [
                        "City-state (polis): an independent city plus its surrounding farmland",
                        "Athens: democracy, trade, ideas · Sparta: military discipline",
                        "Democracy = rule by the people (demos = people, kratos = rule)",
                        "Philosophy chain: Socrates → Plato → Aristotle",
                        "Alexander spread Greek culture — the Hellenistic age",
                    ],
                },
                {
                    "h2": "Rome: republic, empire and the long fall",
                    "paras": [
                        "Rome started as a republic — no king, power held by elected leaders and the Senate — from roughly 509 BCE. It conquered the Mediterranean, but power struggles ended the republic: Julius Caesar seized control and was assassinated in 44 BCE, and his heir Augustus became the first emperor in 27 BCE. The empire's first 200 years, the Pax Romana, were stable and connected: roads, aqueducts, uniform law — and Christianity spreading along those roads.",
                        "The fall was slow, not a single crash. The empire split in two, and the western half crumbled under invasions, money trouble and overstretched borders; 476 CE is the traditional end, when a Germanic leader deposed the last western emperor. The eastern half survived nearly 1,000 more years as the Byzantine Empire. 'Fall of Rome' means the west — and it took centuries.",
                    ],
                    "bullets": [
                        "Republic: elected leaders + Senate, no king (from ~509 BCE)",
                        "Julius Caesar assassinated 44 BCE → Augustus, first emperor, 27 BCE",
                        "Pax Romana: ~200 years of stability, roads, trade, law",
                        "Western empire falls 476 CE; eastern (Byzantine) lasts to 1453",
                        "Legacy: law, Latin-based languages, architecture, the calendar",
                    ],
                },
            ],
            "key_concepts": [
                ("Fertile Crescent", "The arc of rich farmland between the Mediterranean and the Persian Gulf where farming and the first civilizations began."),
                ("Cuneiform", "The world's first writing system — wedge-shaped marks pressed into clay by Sumerian scribes in Mesopotamia."),
                ("Hammurabi's Code", "One of the earliest written law collections (Babylon, ~1750 BCE), famous for clear, published punishments."),
                ("Pharaoh", "An Egyptian king regarded as a god on earth — both ruler and religious figure."),
                ("City-state (polis)", "An independent city with its own government and farmland; the basic unit of ancient Greece."),
                ("Democracy", "Government by the people; in Athens, citizens voted on laws directly."),
                ("Republic", "Government where citizens elect representatives and leaders, with no monarch; Rome's system from 509 BCE."),
                ("Pax Romana", "The ~200-year stretch of Roman peace and stability at the start of the empire."),
            ],
            "study_tips": [
                "Learn the M-E-G-R order before any dates — sequence first, numbers second.",
                "For each civilization, force a one-sentence answer to 'what did they contribute?' — tests love legacies.",
                "Flashcard the pairs that get confused: Athens/Sparta, cuneiform/hieroglyphics, republic/empire.",
                "Draw a simple timeline with just five anchors: 3200 BCE, ~3000 BCE, 509 BCE, 27 BCE, 476 CE.",
                "Compare instead of memorizing: how was Rome's republic different from Athens's democracy? Comparison sticks.",
            ],
            "practice": [
                {
                    "q": "The world's first writing system developed in:",
                    "choices": ["Rome", "Mesopotamia", "Greece", "Persia"],
                    "answer": 1,
                    "explain": "Sumerian scribes in Mesopotamia pressed cuneiform into clay around 3200 BCE — the first writing we know of. Egypt's hieroglyphics followed soon after.",
                },
                {
                    "q": "Athenian democracy is best described as:",
                    "choices": ["Rule by a pharaoh", "Rule by kings", "Citizens voting directly on laws", "Rule by generals"],
                    "answer": 2,
                    "explain": "In Athens, citizens assembled and voted on laws themselves — direct democracy. But 'citizens' excluded women, enslaved people and foreigners, so a minority actually voted.",
                },
                {
                    "q": "Rome's early government, with elected leaders and a Senate and no king, was a:",
                    "choices": ["Democracy", "Republic", "Monarchy", "Dynasty"],
                    "answer": 1,
                    "explain": "From 509 BCE Rome was a republic: power held by elected magistrates and the Senate. It became an empire only after Augustus in 27 BCE.",
                },
                {
                    "q": "Hammurabi's Code is famous as:",
                    "choices": ["An early written set of laws", "Epic poems about the gods", "Maps of the Nile", "Records of the Olympic games"],
                    "answer": 0,
                    "explain": "Hammurabi's Code (Babylon, ~1750 BCE) was one of history's first written law codes — laws publicly displayed so everyone knew the rules and punishments.",
                },
            ],
            "flashcards": [
                ("First writing system, and where", "Cuneiform, in Mesopotamia (Sumer), around 3200 BCE."),
                ("Why civilizations started in river valleys", "Rivers provided water, fertile soil and transport → food surpluses → cities, jobs, government, writing."),
                ("Hammurabi's Code", "An early written law code from Babylon — laws published so everyone knew the punishments."),
                ("Egypt's god-king was called a", "Pharaoh."),
                ("Egyptian writing system", "Hieroglyphics — picture symbols, decoded with the Rosetta Stone."),
                ("Athens vs Sparta in three words", "Athens: ideas, trade, democracy. Sparta: war, discipline, obedience."),
                ("A Greek city-state is called a", "Polis."),
                ("Philosophy chain in order", "Socrates → Plato → Aristotle."),
                ("Rome's government before the emperors", "A republic — elected leaders and the Senate, no king (from 509 BCE)."),
                ("Traditional end of the western Roman Empire", "476 CE, when the last western emperor was deposed."),
            ],
            "faqs": [
                ("Why did the first civilizations form in river valleys?",
                 "Rivers delivered three gifts: water for crops, rich silt soil refreshed by floods, and easy transport. That produced food surpluses, freeing some people to become priests, scribes, builders and rulers — the jobs that make a civilization."),
                ("How was Rome different from Greece?",
                 "Greece was hundreds of independent city-states that rarely unified; Rome centralized power and built a huge empire. Rome also prided itself on republican institutions and law, while borrowing Greece's art, gods and philosophy wholesale."),
                ("Was Athens a real democracy?",
                 "For its time, radically so — citizens assembled and voted directly. But 'citizens' excluded women, enslaved people and foreign residents, so a minority of Athenians actually voted. Direct democracy with sharp limits."),
                ("Why did Rome fall?",
                 "Slowly, from many pressures: overstretched borders, economic trouble, political instability and waves of invasions. The western empire's last emperor fell in 476 CE; the eastern half carried on as the Byzantine Empire until 1453."),
            ],
            "paa": [
                ("What are the four ancient civilizations to know?", "Mesopotamia, Egypt, Greece and Rome — the arc from the first writing to the empire that shaped Western law, language and religion."),
                ("What came first, Greece or Rome?", "Greece. Greek civilization peaked centuries before Rome's republic began in 509 BCE — and Rome copied heavily from Greek culture."),
                ("Why is Hammurabi's Code important?", "It's one of history's first written law codes: publicly displayed laws with set punishments — an early step toward rule of law instead of rule by whim."),
                ("How long did the Roman Empire last?", "The republic ran ~500 years, the western empire another ~500 (ending 476 CE), and the eastern empire until 1453 — over two millennia of Rome in some form."),
            ],
        },
        {
            "slug": "american-revolution",
            "title": "American Revolution",
            "h1": "The American Revolution: Causes, Key Events & Outcomes",
            "meta_title": "American Revolution Explained Simply | StudyBonk",
            "meta_description": "Learn the American Revolution free: causes like taxation without representation, key events from Lexington to Yorktown, and the outcomes. Quiz included.",
            "summary": "Causes, key battles and outcomes of 1763–1783 — plus a timeline trick you'll never forget.",
            "keywords": [
                "american revolution causes",
                "declaration of independence",
                "revolutionary war battles",
                "boston tea party",
                "treaty of paris 1783",
                "us history study guide",
            ],
            "longtail": [
                "main causes of the american revolution explained",
                "what does taxation without representation mean",
                "why did the colonists boycott british goods",
                "what happened at the boston tea party",
                "declaration of independence summary for students",
                "why was the battle of saratoga a turning point",
                "how did the us win the revolutionary war",
                "what was the treaty of paris 1783",
                "loyalists vs patriots differences",
                "american revolution timeline for middle school",
                "what did the constitution do after the revolution",
            ],
            "sections": [
                {
                    "h2": "Why it started: taxes without a voice",
                    "paras": [
                        "After the French and Indian War (1754–1763), Britain was deep in debt and expected the colonies to help pay. Parliament passed a stack of taxes — the Stamp Act, the Townshend Acts — on printed paper, glass, paint and tea. The colonies' objection wasn't only the money: they had no representatives in Parliament, so 'taxation without representation' became the rallying cry, and boycotts of British goods became the weapon.",
                        "Tensions escalated into drama: the Boston Massacre (1770), the Boston Tea Party (1773, colonists dumped 342 chests of tea into the harbor), and Britain's punishing response, the Intolerable Acts, which closed Boston's port. Britain intended to isolate Massachusetts; instead the other colonies rallied, organized the First Continental Congress, and drifted toward war.",
                    ],
                    "bullets": [
                        "French and Indian War left Britain in debt → new colonial taxes",
                        "Stamp Act (1765): tax on printed paper · Townshend Acts: glass, paint, tea",
                        "Cry of the colonies: 'no taxation without representation'",
                        "Boston Massacre 1770 · Boston Tea Party 1773 · Intolerable Acts 1774",
                        "Boycotts of British goods were the colonies' main weapon before the war",
                    ],
                },
                {
                    "h2": "The war: from Lexington to Yorktown",
                    "paras": [
                        "Shooting started in April 1775 at Lexington and Concord, when British troops marched to seize colonial weapons and met militia — 'the shot heard round the world.' Weeks later the Second Continental Congress made George Washington commander of the army. In July 1776, with war already raging, the Declaration of Independence (mostly Thomas Jefferson's pen) announced the breakup: the colonies were now states, entitled to independence by natural rights.",
                        "The war ran on grit plus one huge assist. Washington's army survived disasters and a brutal winter at Valley Forge (1777–78). The turning point was Saratoga (October 1777): an American victory so convincing that France joined the war openly, bringing its navy, money and troops. The endgame came at Yorktown (1781), where Washington and the French trapped Cornwallis's army against the sea with no escape — and Britain surrendered.",
                    ],
                    "bullets": [
                        "Lexington and Concord, April 1775: the war begins",
                        "Declaration of Independence adopted July 4, 1776 (Jefferson's draft)",
                        "Valley Forge winter 1777–78: the army's lowest, most legendary point",
                        "Saratoga 1777: the turning point — wins France as an ally",
                        "Yorktown, October 1781: Cornwallis surrenders; the fighting ends",
                    ],
                    "example": {
                        "title": "How to remember this timeline",
                        "body": "Memorize five two-digit endings and fill in the story: '75 — the fighting arrives (Lexington); '76 — we write the breakup letter (Declaration); '77 — Saratoga convinces France to help; '81 — Yorktown ends the shooting; '83 — the Treaty of Paris makes it official. Say it as a rhythm: arrive, write, convince, end, official.",
                    },
                },
                {
                    "h2": "What changed: outcomes and limits",
                    "paras": [
                        "The Treaty of Paris (1783) did three big things: Britain recognized the United States as independent, and the new nation roughly doubled its territory, stretching west to the Mississippi River. The wartime government under the Articles of Confederation proved too weak — no taxes, no power to stop squabbling states — so in 1787 the Constitution built a stronger federal government with checks and balances, adding the Bill of Rights in 1791.",
                        "The revolution's promise outran its practice. The Declaration's 'all men are created equal' coexisted with slavery, the exclusion of Native Americans, and voting mostly limited to white male property owners. Those gaps became the arguments of later eras — including the civil rights movement in this same pillar — which is why historians call the Revolution a beginning, not a finish line.",
                    ],
                    "bullets": [
                        "Treaty of Paris 1783: independence recognized, borders to the Mississippi",
                        "Articles of Confederation too weak → Constitution, 1787",
                        "Bill of Rights, 1791: first ten amendments protecting individual liberties",
                        "Limits: slavery continued; voting stayed restricted",
                        "Global effect: inspired later revolutions, especially France's in 1789",
                    ],
                },
            ],
            "key_concepts": [
                ("Taxation without representation", "Parliament taxing colonists who had no elected representatives in Parliament — the core colonial grievance."),
                ("Stamp Act", "1765 British tax on printed materials; triggered the first major organized colonial protest and boycott."),
                ("Boston Tea Party", "1773 protest in which colonists dumped 342 chests of British tea into Boston Harbor to defy the tea tax."),
                ("Intolerable Acts", "Britain's 1774 punishment of Massachusetts, closing Boston's port — pushing the colonies toward unity and war."),
                ("Declaration of Independence", "The July 4, 1776 document, chiefly drafted by Jefferson, declaring the colonies independent states with natural rights."),
                ("Patriots and Loyalists", "Patriots fought for independence; Loyalists stayed loyal to Britain — about a third of colonists each, with many neutral."),
                ("Battle of Saratoga", "1777 American victory that persuaded France to ally with the United States — the war's turning point."),
                ("Treaty of Paris (1783)", "The peace treaty ending the war: Britain recognized US independence and set borders at the Mississippi."),
            ],
            "study_tips": [
                "Run the five-date rhythm: '75, '76, '77, '81, '83 — arrive, write, convince, end, official.",
                "Sort every fact into cause, event or outcome; tests almost always ask in those buckets.",
                "Flashcard cause-and-effect pairs: Stamp Act → boycotts · Tea Party → Intolerable Acts · Saratoga → French alliance.",
                "Remember France's role — students forget the US won with French money, troops and navy.",
                "Practice explaining why the Articles failed in one sentence; it's the bridge to the Constitution.",
            ],
            "practice": [
                {
                    "q": "'No taxation without representation' protested:",
                    "choices": ["British taxes on colonists who had no vote in Parliament", "Taxes paid by Britain itself", "Church taxes in Virginia", "Spanish trade tariffs"],
                    "answer": 0,
                    "explain": "Parliament taxed the colonies to pay war debt, but the colonies sent no representatives to Parliament. The money was secondary — the lack of a voice was the grievance.",
                },
                {
                    "q": "The Declaration of Independence was adopted in:",
                    "choices": ["1775", "1776", "1781", "1783"],
                    "answer": 1,
                    "explain": "July 4, 1776 — more than a year after the fighting started at Lexington, and seven years before the Treaty of Paris made independence official.",
                },
                {
                    "q": "Which victory convinced France to ally with the United States?",
                    "choices": ["Yorktown", "Lexington", "Saratoga", "Bunker Hill"],
                    "answer": 2,
                    "explain": "Saratoga (1777) proved the Americans could beat a full British army. France took that as evidence the rebellion was worth backing — and French power decided the endgame at Yorktown.",
                },
                {
                    "q": "The Treaty of Paris of 1783:",
                    "choices": ["Started the French alliance", "Imposed new taxes on tea", "Wrote the Constitution", "Ended the war and recognized US independence"],
                    "answer": 3,
                    "explain": "The 1783 Treaty of Paris ended the war: Britain recognized independence and set US borders at the Mississippi River. The Constitution came four years later, in 1787.",
                },
            ],
            "flashcards": [
                ("The war begins here, April 1775", "Lexington and Concord — 'the shot heard round the world.'"),
                ("Declaration of Independence date", "July 4, 1776."),
                ("Main author of the Declaration", "Thomas Jefferson."),
                ("Turning point battle, 1777", "Saratoga — the victory that won France as an ally."),
                ("Why France mattered", "French navy, money and troops trapped Cornwallis and forced the surrender at Yorktown."),
                ("Final major battle, 1781", "Yorktown — Cornwallis surrenders to Washington."),
                ("Treaty that ended the war, 1783", "Treaty of Paris: independence recognized, borders to the Mississippi."),
                ("Boston Tea Party, 1773", "Colonists dumped 342 chests of British tea into the harbor to protest the tea tax."),
                ("Patriots vs Loyalists", "Patriots wanted independence; Loyalists stayed loyal to the Crown."),
                ("The weak first US government", "The Articles of Confederation — replaced by the Constitution in 1787."),
            ],
            "faqs": [
                ("Why did the American Revolution start?",
                 "Britain's debt from the French and Indian War led to new colonial taxes, imposed without colonial representation in Parliament. Protests, boycotts and crackdowns — ending in the Intolerable Acts — escalated until fighting broke out at Lexington and Concord in 1775."),
                ("How did the colonies beat the world's strongest army?",
                 "Three reasons: fighting on home ground for a cause, Washington keeping an army alive through disasters, and France's alliance after Saratoga — money, troops and especially the navy that sealed Cornwallis in at Yorktown."),
                ("What did the Declaration of Independence actually do?",
                 "It announced the breakup: the colonies were now independent states, justified by natural rights — life, liberty and the pursuit of happiness — and it listed grievances against King George III. It didn't start the war (already a year old) or set up a government (that came later)."),
                ("Who were the Loyalists?",
                 "Colonists who remained loyal to Britain — roughly a third of the population, by John Adams's famous estimate, with another third neutral. Thousands fled during and after the war, mostly to Canada and Britain."),
            ],
            "paa": [
                ("What caused the American Revolution in simple terms?", "Britain taxed the colonies to pay war debts, refused them a voice in Parliament, and cracked down on protest until fighting started in 1775."),
                ("When did America actually become independent?", "Declared July 4, 1776; won at Yorktown in 1781; made official by the Treaty of Paris in 1783 — three dates, three different meanings of 'independent.'"),
                ("Why was Saratoga the turning point?", "It proved the Americans could beat a full British army, which convinced France the rebellion was worth backing — and French power decided the endgame at Yorktown."),
                ("What did the US gain in the Treaty of Paris 1783?", "Recognition of independence plus territory stretching west to the Mississippi River — roughly double the original colonies."),
            ],
        },
        {
            "slug": "world-war-i",
            "title": "World War I",
            "h1": "World War I: MAIN Causes, Trench Warfare & the Treaty of Versailles",
            "meta_title": "World War I Explained: Causes & Outcome | StudyBonk",
            "meta_description": "Learn World War I free: the MAIN causes, trench warfare, why the US entered and the Treaty of Versailles — with a timeline trick, flashcards and a quiz.",
            "summary": "The MAIN causes, life in the trenches and the treaty that accidentally set up round two.",
            "keywords": [
                "world war 1 causes",
                "main causes of wwi",
                "trench warfare explained",
                "treaty of versailles summary",
                "why the us entered wwi",
                "world history study guide",
            ],
            "longtail": [
                "what were the main causes of world war 1",
                "what does main stand for in world war 1",
                "why was the franz ferdinand assassination important",
                "how did alliances turn a small conflict into a world war",
                "what was trench warfare like for soldiers",
                "why did the us enter world war 1",
                "what was the lusitania and zimmermann telegram",
                "how did world war 1 end",
                "what did the treaty of versailles blame germany for",
                "how did wwi lead to world war 2",
                "what was no man's land in wwi",
            ],
            "sections": [
                {
                    "h2": "The MAIN causes and the spark",
                    "paras": [
                        "Historians compress World War I's causes into the acronym MAIN: Militarism (building huge armies and glorifying military power), Alliances (Europe split into two armed camps, all promising to fight together), Imperialism (competing for colonies and global status), and Nationalism (intense pride that made every nation ready to fight for its side).",
                        "The spark: in June 1914, a Serbian nationalist assassinated Archduke Franz Ferdinand, heir to Austria-Hungary's throne, in Sarajevo. Austria-Hungary declared war on Serbia; alliances yanked nation after nation in — Russia, Germany, France, Britain — and within about six weeks a Balkan shootout was a world war.",
                    ],
                    "bullets": [
                        "Militarism: an arms race and glorified military power",
                        "Alliances: everyone was chained to someone else",
                        "Imperialism: colonial rivalries added friction",
                        "Nationalism: every nation primed to defend its pride",
                        "The spark: Franz Ferdinand assassinated, June 1914",
                    ],
                    "example": {
                        "title": "How to remember this timeline",
                        "body": "Four words: Spark, Surge, Stop, Sign. 1914 — the Spark (the assassination). 1917 — the Surge (the US enters). 1918 — the Stop (armistice on November 11, at the 11th hour). 1919 — the Sign (Treaty of Versailles). MAIN explains why it started; Spark-Surge-Stop-Sign tells you what happened.",
                    },
                },
                {
                    "h2": "Trench warfare and new technology",
                    "paras": [
                        "On the Western Front, neither side could push the other out of France and Belgium, so both dug in — literally. Soldiers lived in muddy, rat-infested trenches stretching for hundreds of miles, separated from the enemy by 'no man's land,' a shell-blasted strip that attacks had to cross. Machine guns, barbed wire and artillery made charges suicidal: battles lasted months and moved the front a few miles. Verdun and the Somme in 1916 together caused roughly two million casualties.",
                        "The war industrialized killing: poison gas, tanks, submarines (U-boats) and airplanes all debuted or matured. Germany's unrestricted U-boat warfare sank civilian ships — most famously the Lusitania in 1915 — and the leaked Zimmermann Telegram (Germany offering Mexico US territory) pushed a reluctant United States into the war in April 1917. Fresh American troops and supplies helped exhaust Germany into seeking an armistice.",
                    ],
                    "bullets": [
                        "Trenches + no man's land defined the Western Front",
                        "Machine guns, artillery and barbed wire froze the front lines",
                        "Verdun and the Somme (1916): months of fighting, tiny gains",
                        "New tech: poison gas, tanks, U-boats, airplanes",
                        "US enters April 1917 after U-boat attacks and the Zimmermann Telegram",
                    ],
                },
                {
                    "h2": "The Treaty of Versailles and the aftermath",
                    "paras": [
                        "Germany, exhausted and blockaded, signed the armistice on November 11, 1918 — the 11th hour of the 11th day of the 11th month, now commemorated as Veterans Day. The 1919 Treaty of Versailles then dictated peace: Germany accepted blame for the war (the war guilt clause), lost territory and colonies, had its military capped, and owed crushing reparations. A new League of Nations was created to prevent future wars — but the US Senate refused to join, weakening it from birth.",
                        "The treaty's harshness backfired. Germans felt humiliated and betrayed, their economy collapsed under reparations and hyperinflation, and resentment fed extremist politics. Within twenty years, World War II grew from that wreckage — which is why historians call Versailles the peace that ended nothing.",
                    ],
                    "bullets": [
                        "Armistice: November 11, 1918, 11 a.m.",
                        "War guilt clause: Germany forced to accept blame",
                        "Reparations: massive payments that wrecked Germany's economy",
                        "League of Nations created — but the US never joined",
                        "Resentment over Versailles fed the rise of Hitler",
                    ],
                },
            ],
            "key_concepts": [
                ("Militarism", "Building up armed forces and glorifying military power — one of the MAIN causes."),
                ("Alliances", "Mutual-defense promises that pulled nation after nation into a small conflict."),
                ("Nationalism", "Intense pride in and loyalty to one's nation or ethnic group, ready to be defended by force."),
                ("Trench warfare", "Armies fighting from long dug-in trenches, facing each other across no man's land."),
                ("No man's land", "The deadly strip between opposing trenches that attacks had to cross."),
                ("U-boat", "German submarine; unrestricted U-boat warfare helped pull the US into the war."),
                ("Armistice", "The agreement ending the fighting, November 11, 1918."),
                ("Treaty of Versailles", "The 1919 peace treaty blaming and punishing Germany — sowing the grievances behind WWII."),
            ],
            "study_tips": [
                "Burn MAIN into memory with the flashcard deck first — it anchors every essay question.",
                "Run the four-word spine: Spark (1914), Surge (1917), Stop (1918), Sign (1919).",
                "For Versailles, memorize the three punishments: guilt, land, reparations.",
                "Practice explaining how one assassination became a world war — the chain of alliances is the answer.",
                "Link forward: for every WWI outcome, ask 'and how did this cause WWII?' — that's the classic exam move.",
            ],
            "practice": [
                {
                    "q": "Which is NOT one of the MAIN causes of World War I?",
                    "choices": ["Militarism", "Alliances", "Isolationism", "Nationalism"],
                    "answer": 2,
                    "explain": "MAIN = Militarism, Alliances, Imperialism, Nationalism. Isolationism — staying out of foreign conflicts — is closer to the opposite of the alliance system that spread the war.",
                },
                {
                    "q": "The spark that started World War I was:",
                    "choices": ["The invasion of Poland", "The assassination of Archduke Franz Ferdinand", "The bombing of Pearl Harbor", "The Berlin Blockade"],
                    "answer": 1,
                    "explain": "In June 1914 a Serbian nationalist killed the heir to Austria-Hungary's throne in Sarajevo. Alliances then dragged Europe into war within weeks.",
                },
                {
                    "q": "The US entered WWI in 1917 largely because of:",
                    "choices": ["Unrestricted submarine warfare and the Zimmermann Telegram", "The Treaty of Versailles", "The fall of the Berlin Wall", "Its alliance with Austria-Hungary"],
                    "answer": 0,
                    "explain": "German U-boats sank civilian and American ships (like the Lusitania), and the Zimmermann Telegram revealed Germany offering Mexico US territory. Together they ended US neutrality.",
                },
                {
                    "q": "The Treaty of Versailles:",
                    "choices": ["Made Germany an equal partner in Europe", "Created the United Nations", "Blamed Germany and imposed massive reparations", "Was signed only by Germany and Russia"],
                    "answer": 2,
                    "explain": "Versailles (1919) forced Germany to accept war guilt, lose territory, cap its military and pay crushing reparations — punishments whose backlash helped cause WWII.",
                },
            ],
            "flashcards": [
                ("MAIN stands for", "Militarism, Alliances, Imperialism, Nationalism — the four long-term causes of WWI."),
                ("Spark of WWI", "Assassination of Archduke Franz Ferdinand, June 1914, Sarajevo."),
                ("WWI dates", "1914–1918."),
                ("No man's land is", "The deadly strip of ground between enemy trenches."),
                ("Why the US entered in 1917", "German U-boat attacks (including the Lusitania) and the Zimmermann Telegram."),
                ("Armistice date", "November 11, 1918 — the 11th hour of the 11th day of the 11th month."),
                ("War guilt clause", "The Versailles clause forcing Germany to accept full blame for the war."),
                ("Reparations", "Huge payments Germany owed the Allies under Versailles — wrecking its economy."),
                ("League of Nations", "The post-WWI peace organization — weakened because the US never joined."),
                ("How Versailles fed WWII", "Humiliation, lost land, economic collapse and resentment gave extremists like Hitler their opening."),
            ],
            "faqs": [
                ("Why was WWI called a 'world' war?",
                 "The fighting centered on Europe, but empires pulled in their colonies worldwide — troops from India, Africa, Australia and Canada fought — and battles reached the Middle East, Africa and the Pacific. Europe's empires made it global."),
                ("Why couldn't either side win in the trenches?",
                 "Defensive technology — machine guns, artillery, barbed wire — outran offensive tactics. Attacking across no man's land was nearly suicidal, so fronts barely moved for years until tanks, fresh American troops and exhaustion broke the stalemate."),
                ("What was the Zimmermann Telegram?",
                 "A secret 1917 German offer to Mexico: ally with Germany and win back territory lost to the US. Britain intercepted and shared it, outraging Americans and pushing the US into the war weeks later."),
                ("Was the Treaty of Versailles too harsh?",
                 "Most historians say it was harsh enough to humiliate and impoverish Germany yet too weak to keep it down long. The resentment it generated became fuel for Hitler's rise — some call it 'an armistice for twenty years.'"),
            ],
            "paa": [
                ("What caused World War I in simple terms?", "MAIN: Militarism, Alliances, Imperialism, Nationalism — decades of buildup, ignited by the 1914 assassination of Franz Ferdinand."),
                ("When and how did WWI end?", "Germany, exhausted and blockaded, signed an armistice on November 11, 1918; the Treaty of Versailles formally settled the peace in 1919."),
                ("Why did the US join World War I?", "German submarines sank civilian and American ships, and the Zimmermann Telegram revealed Germany offering Mexico US land. War came in April 1917."),
                ("What was life like in the trenches?", "Mud, rats, disease and shellfire in dug-in lines separated by no man's land — month-long battles moved the front only a few miles."),
            ],
        },
        {
            "slug": "world-war-ii",
            "title": "World War II",
            "h1": "World War II: Causes, Turning Points & Aftermath",
            "meta_title": "World War II Explained: Causes & Aftermath | StudyBonk",
            "meta_description": "Learn World War II free: causes like fascism and appeasement, turning points like D-Day and Stalingrad, and the aftermath. Flashcards, quiz, no sign-up.",
            "summary": "Causes, turning points and aftermath of 1939–1945 — the war that remade the world.",
            "keywords": [
                "world war 2 causes",
                "wwii turning points",
                "d-day explained",
                "pearl harbor",
                "holocaust explained",
                "world history study guide",
            ],
            "longtail": [
                "main causes of world war 2 explained",
                "how did the treaty of versailles lead to world war 2",
                "what was appeasement before wwii",
                "why did japan attack pearl harbor",
                "what happened on d-day in simple terms",
                "why was stalingrad a turning point",
                "what was the holocaust",
                "how did world war 2 end",
                "what was created after world war 2",
                "difference between world war 1 and world war 2 causes",
                "wwii timeline for students",
            ],
            "sections": [
                {
                    "h2": "How it happened again: the causes",
                    "paras": [
                        "World War II grew directly from World War I's wreckage. The Treaty of Versailles humiliated Germany; the Great Depression threw millions out of work worldwide; and in that desperation, fascist leaders promised national greatness — Hitler in Germany, Mussolini in Italy, militarists in Japan. Fascism promised order and glory at the cost of freedom, and it blamed scapegoats, especially Jewish people.",
                        "The democracies tried appeasement — giving in to demands to avoid another war. Britain and France let Hitler rearm and annex Austria, then at Munich in 1938 handed him Czechoslovakia's borderlands ('peace for our time' lasted under a year). When Germany and the USSR signed a surprise nonaggression pact, Hitler invaded Poland on September 1, 1939 — and Britain and France declared war two days later.",
                    ],
                    "bullets": [
                        "Versailles resentment + Great Depression = fascism's opening",
                        "Axis: Germany, Italy, Japan · Allies: Britain, USSR, US, China, France and more",
                        "Appeasement: giving in to Hitler's demands to avoid war",
                        "Munich 1938: Czechoslovakia sacrificed for 'peace'",
                        "Germany invades Poland, September 1, 1939: the war begins",
                    ],
                    "example": {
                        "title": "How to remember this timeline",
                        "body": "Europe's story in five numbers: 1939 Poland falls (war begins) · 1941 Pearl Harbor (the US enters) · 1942–43 Stalingrad (the tide turns in the east) · 1944 D-Day (the western front opens) · 1945 Germany and Japan surrender. Chant it: Poland, Pearl, Stalingrad, D-Day, done.",
                    },
                },
                {
                    "h2": "Turning points: Pearl Harbor to V-J Day",
                    "paras": [
                        "December 7, 1941: Japan attacked Pearl Harbor, killing about 2,400 Americans and ending US neutrality overnight. In 1942 the tide turned twice. In the Pacific, the Battle of Midway (June 1942) destroyed Japan's carrier advantage and put it on defense. On the Eastern Front, the months-long Battle of Stalingrad (1942–43) ended with an entire German army surrendering — the war's bloodiest battle and the death of Germany's advance. Behind the lines, the Holocaust — Nazi Germany's systematic murder of six million Jewish people, plus millions of others — continued, the war's deepest crime.",
                        "Then D-Day — June 6, 1944 — landed Allied forces on the Normandy beaches, opening the western front. The liberation of Western Europe rolled east while the Soviets pushed west from Stalingrad. Germany surrendered in May 1945 (V-E Day). The Pacific war ended in August 1945 after the US dropped atomic bombs on Hiroshima and Nagasaki; Japan formally surrendered September 2 (V-J Day).",
                    ],
                    "bullets": [
                        "Pearl Harbor: December 7, 1941 — the US enters the war",
                        "Midway, June 1942: the Pacific turning point",
                        "Stalingrad, 1942–43: the Eastern Front turning point",
                        "D-Day, June 6, 1944: the Allied landings in Normandy",
                        "V-E Day May 1945 · atomic bombs August 1945 · V-J Day September 1945",
                    ],
                },
                {
                    "h2": "Aftermath: a remade world",
                    "paras": [
                        "The war killed roughly 70–85 million people, soldiers and civilians alike, and ended with the first — and so far only — wartime use of nuclear weapons. The Nuremberg trials held Nazi leaders accountable for newly defined 'crimes against humanity,' and the full horror of the Holocaust pushed human rights into international law, starting with the Universal Declaration of Human Rights.",
                        "Two superpowers stood above the rubble — the United States and the Soviet Union — and their rivalry became the Cold War. The United Nations (founded 1945) replaced the failed League of Nations, this time with the US in it. US Marshall Plan money rebuilt Western Europe while the USSR sealed off its half behind the Iron Curtain, and weakened European powers began losing their colonies. WWI remade maps; WWII remade the whole world order.",
                    ],
                    "bullets": [
                        "United Nations founded, 1945 — with the US in it this time",
                        "Nuremberg trials: leaders held accountable for war crimes",
                        "Marshall Plan: US aid rebuilt Western Europe",
                        "US and USSR emerge as rival superpowers → the Cold War",
                        "Decolonization: empires crumble over the next 30 years",
                    ],
                },
            ],
            "key_concepts": [
                ("Fascism", "A dictatorial ideology glorifying the nation and military power, crushing democracy and blaming scapegoats."),
                ("Appeasement", "Giving in to an aggressor's demands to avoid war — symbolized by the 1938 Munich agreement."),
                ("Axis and Allies", "Axis: Germany, Italy, Japan. Allies: Britain, the USSR, the US, China, France and others."),
                ("Blitzkrieg", "'Lightning war' — fast, coordinated tank-and-air assault; how Germany overran Poland and France."),
                ("Holocaust", "Nazi Germany's systematic genocide of six million Jewish people and millions of others."),
                ("D-Day", "June 6, 1944: the Allied invasion of Normandy that opened the western front in France."),
                ("V-E Day and V-J Day", "Victory in Europe (May 8, 1945) and Victory over Japan (September 2, 1945)."),
                ("Marshall Plan", "US economic aid that rebuilt Western Europe after the war — and built Cold War alliances."),
            ],
            "study_tips": [
                "Chain the causes out loud: Versailles → depression → Hitler → appeasement → Poland. Tests love the chain.",
                "Memorize the five-number spine: 1939, 1941, 1942–43, 1944, 1945.",
                "Separate the two war stories — Europe vs. Pacific — then connect them at Pearl Harbor and V-J Day.",
                "Flashcard the battles with their 'why it mattered' line, not just the date.",
                "Practice one-sentence answers for 'how did WWII start?' and 'how did it end?' — those two questions carry most exams.",
            ],
            "practice": [
                {
                    "q": "World War II in Europe began when Germany:",
                    "choices": ["Invaded Poland in September 1939", "Bombed Pearl Harbor", "Built the Berlin Wall", "Signed the Treaty of Versailles"],
                    "answer": 0,
                    "explain": "Germany invaded Poland on September 1, 1939; Britain and France declared war two days later. Pearl Harbor (1941) came later and brought in the US.",
                },
                {
                    "q": "The US entered WWII after:",
                    "choices": ["D-Day", "The attack on Pearl Harbor, December 7, 1941", "The Battle of Britain", "The Munich agreement"],
                    "answer": 1,
                    "explain": "Japan's surprise attack on Pearl Harbor killed about 2,400 Americans and ended US neutrality overnight — Congress declared war the next day.",
                },
                {
                    "q": "D-Day, June 6, 1944, was:",
                    "choices": ["Japan's final surrender", "The bombing of Berlin", "The Allied invasion of Normandy, France", "The start of US neutrality"],
                    "answer": 2,
                    "explain": "D-Day was history's largest seaborne invasion: Allied forces landed on five Normandy beaches, opening the western front that liberated France and Western Europe.",
                },
                {
                    "q": "After the war, the Allies created the ___ to keep the peace.",
                    "choices": ["League of Nations", "United Nations", "Warsaw Pact", "Marshall Plan"],
                    "answer": 1,
                    "explain": "The United Nations (1945) replaced the failed League of Nations — and this time the US joined, giving it real strength.",
                },
            ],
            "flashcards": [
                ("WWII dates", "1939–1945."),
                ("The war begins when", "Germany invades Poland, September 1, 1939; Britain and France declare war."),
                ("Appeasement means", "Giving in to an aggressor's demands to avoid war — e.g., Munich, 1938."),
                ("Pearl Harbor", "December 7, 1941 — Japan's surprise attack that brought the US into the war."),
                ("Eastern Front turning point", "Stalingrad, 1942–43 — Germany's advance dies and an entire army surrenders."),
                ("Pacific turning point", "Midway, June 1942 — Japan loses its carrier superiority."),
                ("D-Day", "June 6, 1944 — the Allied landings at Normandy, opening the western front."),
                ("V-E Day", "May 8, 1945 — Germany surrenders."),
                ("V-J Day", "September 2, 1945 — Japan surrenders after atomic bombs on Hiroshima and Nagasaki."),
                ("The postwar peace organization", "The United Nations, founded 1945."),
            ],
            "faqs": [
                ("How was WWII different from WWI?",
                 "WWI was a static trench stalemate between great powers; WWII was a war of movement spanning the globe — blitzkrieg, air power, island-hopping — with clear turning points, city bombing, the Holocaust and nuclear weapons. WWII's death toll was several times higher."),
                ("Why did Japan attack Pearl Harbor?",
                 "The US had embargoed the oil and steel Japan needed for its empire, so Japan's leaders chose a preemptive strike to knock out the US Pacific Fleet. It backfired: the attack united Americans overnight and brought overwhelming US power into the war."),
                ("Why is Stalingrad considered the turning point?",
                 "It was among the largest and bloodiest battles in history and ended with a catastrophic German surrender — a whole army lost. After Stalingrad, Germany retreated on the Eastern Front until the war ended; it never regained the initiative."),
                ("What came out of WWII besides peace?",
                 "The United Nations, the Nuremberg precedent for war-crimes trials, the nuclear age, the Cold War rivalry, the decolonization wave and the modern human-rights framework — today's world order is WWII's aftermath."),
            ],
            "paa": [
                ("What caused World War II?", "Versailles humiliation, the Great Depression, fascist expansion, and appeasement that failed to stop it — triggered by Germany's invasion of Poland in 1939."),
                ("What was D-Day?", "The June 6, 1944 Allied amphibious invasion of Normandy — history's largest seaborne assault, opening the front that liberated Western Europe."),
                ("How did World War II end?", "Germany surrendered May 8, 1945, as Allied armies closed from east and west; Japan surrendered September 2, 1945, after the atomic bombings of Hiroshima and Nagasaki."),
                ("What was the Holocaust?", "Nazi Germany's systematic genocide of six million Jewish people, alongside millions of Roma, disabled people, political prisoners and others — the war's central moral crime."),
            ],
        },
        {
            "slug": "cold-war",
            "title": "Cold War",
            "h1": "The Cold War: Containment, Crises & the Fall of the Berlin Wall",
            "meta_title": "The Cold War Explained Simply | StudyBonk",
            "meta_description": "Learn the Cold War free: containment, the Berlin Airlift, Cuban Missile Crisis, space race and the fall of the Berlin Wall — flashcards, quiz, no sign-up.",
            "summary": "Containment, Berlin, Cuba and the wall coming down — the 45-year standoff explained simply.",
            "keywords": [
                "cold war explained",
                "containment policy",
                "berlin wall fall 1989",
                "cuban missile crisis",
                "cold war timeline",
                "us history study guide",
            ],
            "longtail": [
                "what was the cold war in simple terms",
                "why was it called the cold war",
                "what was the policy of containment",
                "what was the truman doctrine and marshall plan",
                "what happened during the berlin airlift",
                "what was the cuban missile crisis about",
                "why was the berlin wall built",
                "how did the cold war end",
                "what was the space race",
                "difference between nato and the warsaw pact",
                "what does iron curtain mean",
            ],
            "sections": [
                {
                    "h2": "What the Cold War was — and containment",
                    "paras": [
                        "After 1945, the US and USSR — allies against Hitler — became rivals for global leadership: capitalism and democracy on one side, communism and one-party rule on the other. It was 'cold' because the superpowers never fought each other directly; nuclear weapons made direct war unthinkable. Instead they raced, spied, funded and armed everyone else — with flashpoints that repeatedly brought the world to the edge.",
                        "America's strategy was containment: block communism's spread wherever it appeared. The Truman Doctrine (1947) promised aid to nations resisting communism; the Marshall Plan (1948) rebuilt Western Europe so poverty couldn't breed communism; NATO organized the western allies militarily, and the Warsaw Pact answered for the communist side. Churchill named the divide the 'Iron Curtain' — the sealed border splitting Europe in two.",
                    ],
                    "bullets": [
                        "US vs. USSR: capitalism/democracy vs. communism/one-party rule",
                        "'Cold' because they never fought directly — nuclear war was unthinkable",
                        "Containment: stop communism from spreading",
                        "Truman Doctrine (aid) + Marshall Plan (rebuilding) = containment in action",
                        "NATO vs. Warsaw Pact: the two alliance blocs",
                    ],
                },
                {
                    "h2": "Flashpoints: Berlin, Korea, Cuba and space",
                    "paras": [
                        "Berlin was the crisis capital. In 1948–49, when the USSR blockaded West Berlin to starve out the western allies, Britain and the US flew in supplies for almost a year — the Berlin Airlift — until the blockade folded. In 1961 the communists built the Berlin Wall to stop East Germans fleeing west; it became the Cold War's most visible scar.",
                        "Korea (1950–53) and Vietnam (US combat from 1965) were 'hot' proxy wars where the superpowers backed opposite sides — containment's theory meeting its costs. The scariest moment came in October 1962: US spy planes found Soviet nuclear missiles being installed in Cuba, 90 miles from Florida. Thirteen tense days of blockade and back-channel deals ended with the missiles withdrawn — and both sides installing a hotline so it never got that close again. The space race (Sputnik 1957 → Moon landing 1969) was the Cold War's most inspiring battlefield.",
                    ],
                    "bullets": [
                        "Berlin Airlift 1948–49: supplies flown past the Soviet blockade",
                        "Korean War 1950–53: the first hot proxy war, ending in stalemate",
                        "Cuban Missile Crisis, October 1962: 13 days on the nuclear brink",
                        "Vietnam: the longest and most divisive US proxy war",
                        "Space race: Sputnik (1957) to the Apollo 11 Moon landing (1969)",
                    ],
                },
                {
                    "h2": "How it ended: the wall comes down",
                    "paras": [
                        "By the 1980s the Soviet system was exhausted: a planned economy that couldn't deliver goods, a war in Afghanistan it couldn't win, and arms spending it couldn't afford. New leader Mikhail Gorbachev tried reform — glasnost (openness) and perestroika (restructuring) — but loosened forces he couldn't control. When he made clear the USSR would no longer prop up Eastern Europe's communist governments, the dam broke.",
                        "In 1989, one by one, the communist regimes of Eastern Europe fell — and on November 9, 1989, the Berlin Wall was opened and crowds tore it down with hammers and hands. Germany reunified in 1990, the Warsaw Pact dissolved, and in December 1991 the Soviet Union itself broke into 15 independent countries. The Cold War ended not with a bang but with a vote: the USSR simply dissolved itself out of existence.",
                    ],
                    "bullets": [
                        "Gorbachev's reforms: glasnost (openness) and perestroika (restructuring)",
                        "November 9, 1989: the Berlin Wall falls",
                        "Germany reunified, 1990",
                        "December 1991: the USSR dissolves into 15 countries",
                        "Aftermath: NATO expansion — and tensions that never fully disappeared",
                    ],
                    "example": {
                        "title": "How to remember this timeline",
                        "body": "Use Berlin as the bookends: the crisis starts with a blockade (1948), hardens into a wall (1961), and ends with that wall falling (1989). Between the bookends, drop in Cuba's 13 days (1962) and the Moon (1969). If you can date the Berlin trio, you can navigate almost any Cold War question.",
                    },
                },
            ],
            "key_concepts": [
                ("Cold War", "The 1947–1991 rivalry between the US and USSR — fought by every means except direct war."),
                ("Containment", "US policy of stopping the spread of communism, by aid, alliances and proxy wars."),
                ("Iron Curtain", "Churchill's term for the divide sealing off Soviet-controlled Eastern Europe from the West."),
                ("Truman Doctrine", "The 1947 pledge of American aid to countries resisting communist takeover."),
                ("Marshall Plan", "The US program that rebuilt Western Europe's economies to inoculate them against communism."),
                ("Proxy war", "A conflict where superpowers arm and support opposite sides instead of fighting each other — Korea, Vietnam."),
                ("Berlin Wall", "The 1961–1989 barrier sealing East Berlin off from West Berlin; the Cold War's most famous symbol."),
                ("Glasnost and perestroika", "Gorbachev's policies of openness and economic restructuring — reform that unintentionally unraveled the USSR."),
            ],
            "study_tips": [
                "Memorize the Berlin trio as your timeline spine: blockade 1948, wall 1961, wall falls 1989.",
                "For every crisis, name the two sides AND the outcome — flashcards in that format.",
                "Keep the ideologies straight by pairing: Truman Doctrine ↔ Marshall Plan, NATO ↔ Warsaw Pact.",
                "Practice explaining 'why cold?' in one sentence — the nuclear logic is the whole concept.",
                "Link the ending: Soviet exhaustion → Gorbachev's reforms → 1989 → 1991. Chain questions are common.",
            ],
            "practice": [
                {
                    "q": "Containment was the US policy of:",
                    "choices": ["Stopping the spread of communism", "Fighting the USSR directly", "Rebuilding Japan", "Ending World War II"],
                    "answer": 0,
                    "explain": "Containment meant blocking communism's expansion anywhere it appeared — through aid (Truman Doctrine, Marshall Plan), alliances (NATO) and proxy wars (Korea, Vietnam), never direct war with the USSR.",
                },
                {
                    "q": "During the Berlin Airlift, the US and Britain:",
                    "choices": ["Attacked East Germany", "Flew supplies into West Berlin past the Soviet blockade", "Built the Berlin Wall", "Invaded Cuba"],
                    "answer": 1,
                    "explain": "When the USSR blockaded West Berlin in 1948–49, western planes flew in food, fuel and medicine for almost a year until the blockade ended — the first major Cold War standoff, won without a shot.",
                },
                {
                    "q": "The Cuban Missile Crisis happened in:",
                    "choices": ["1948", "1953", "1961", "1962"],
                    "answer": 3,
                    "explain": "In October 1962, US spy planes found Soviet nuclear missiles being built in Cuba. Thirteen days of brinkmanship ended with the missiles withdrawn — the closest the world has come to nuclear war.",
                },
                {
                    "q": "The Soviet Union dissolved in:",
                    "choices": ["1989", "1985", "1991", "1975"],
                    "answer": 2,
                    "explain": "The Berlin Wall fell in 1989, Germany reunified in 1990, and in December 1991 the USSR itself broke apart into 15 independent countries — the Cold War's endpoint.",
                },
            ],
            "flashcards": [
                ("Cold War dates", "About 1947–1991."),
                ("Why 'cold' war", "The superpowers never fought each other directly — nuclear weapons made direct war unthinkable."),
                ("Containment means", "US policy to stop communism spreading anywhere — by aid, alliances and proxy wars."),
                ("Truman Doctrine, 1947", "US pledge to aid nations resisting communist takeover."),
                ("Marshall Plan", "US money rebuilding Western Europe so communism couldn't take root in poverty."),
                ("Berlin Airlift, 1948–49", "Western allies flew supplies into blockaded West Berlin until the USSR backed down."),
                ("Why the Berlin Wall was built, 1961", "To stop East Germans from fleeing to the West."),
                ("Cuban Missile Crisis, 1962", "A 13-day standoff over Soviet missiles in Cuba — the closest the world came to nuclear war."),
                ("Berlin Wall falls", "November 9, 1989."),
                ("USSR dissolves", "December 1991 — the Soviet Union splits into 15 independent countries."),
            ],
            "faqs": [
                ("Why was it called a 'cold' war?",
                 "Because the US and USSR never fought each other directly. Both had nuclear weapons, so direct war risked mutual destruction. Instead they competed through proxy wars, arms and space races, spying and propaganda — everything short of shooting at each other."),
                ("What was containment?",
                 "The grand US strategy: prevent communism from spreading further. It drove the Truman Doctrine, the Marshall Plan, NATO, Korea and Vietnam — containment by wallet, alliance and, when it came to it, war."),
                ("How close did the Cuban Missile Crisis come to nuclear war?",
                 "Closer than any moment before or since: Soviet missiles in Cuba, a US naval blockade, and thirteen days of brinkmanship. It ended with a negotiated withdrawal — and both sides installing a hotline so it never got that close again."),
                ("Why did the Soviet Union collapse?",
                 "Economic exhaustion, the costly Afghanistan war, unsustainable arms spending — and Gorbachev's reforms (glasnost and perestroika) loosening control at the same time. Once Eastern Europe was let go in 1989, the USSR's own republics followed by 1991."),
            ],
            "paa": [
                ("What was the Cold War in simple terms?", "A roughly 45-year rivalry between the US and USSR — two superpowers with opposite systems — fought through proxies, races and standoffs instead of direct war."),
                ("Who won the Cold War?", "The United States and the West, by outlasting the Soviet system — which collapsed from economic exhaustion between 1989 and 1991."),
                ("What ended the Cold War?", "The fall of the Berlin Wall in November 1989, the liberation of Eastern Europe, and the USSR's dissolution in December 1991."),
                ("What was the Iron Curtain?", "Winston Churchill's metaphor for the border sealing communist Eastern Europe off from the West — 'from Stettin in the Baltic to Trieste in the Adriatic.'"),
            ],
        },
        {
            "slug": "civil-rights-movement",
            "title": "Civil Rights Movement",
            "h1": "The Civil Rights Movement: Key Events, Figures & Laws",
            "meta_title": "Civil Rights Movement Explained Simply | StudyBonk",
            "meta_description": "Learn the civil rights movement free: Brown v. Board, Montgomery, the March on Washington and the laws of 1964-65 — flashcards, quiz, no sign-up.",
            "summary": "From Brown v. Board to the Voting Rights Act — the events, leaders and laws, plus a dates trick.",
            "keywords": [
                "civil rights movement",
                "martin luther king jr",
                "brown v board",
                "civil rights act 1964",
                "voting rights act 1965",
                "us history study guide",
            ],
            "longtail": [
                "civil rights movement timeline for students",
                "what started the civil rights movement",
                "what was brown v board of education about",
                "why did rosa parks refuse to give up her seat",
                "what was the montgomery bus boycott",
                "what happened at the march on washington",
                "what did the civil rights act of 1964 do",
                "difference between the 1964 and 1965 civil rights acts",
                "what were the selma marches",
                "who was martin luther king jr in simple terms",
                "what were jim crow laws",
            ],
            "sections": [
                {
                    "h2": "The movement begins: Brown and the bus",
                    "paras": [
                        "After Reconstruction, the South built Jim Crow: laws enforcing racial segregation in schools, transport, restaurants — nearly everything — under the lie of 'separate but equal.' Black Americans fought the system through courts, boycotts and brave daily acts. In May 1954, the Supreme Court's Brown v. Board of Education ruling struck down school segregation, declaring separate schools 'inherently unequal' and reversing nearly 60 years of legal doctrine.",
                        "In December 1955, Rosa Parks was arrested in Montgomery, Alabama, for refusing to give up her bus seat to a white passenger. The Black community responded with a 381-day bus boycott, organized in part by a 26-year-old pastor named Martin Luther King Jr. The boycott starved the bus system until the Supreme Court ordered desegregated buses — proving that organized nonviolent protest could win.",
                    ],
                    "bullets": [
                        "Jim Crow: state laws enforcing segregation, 'separate but equal'",
                        "Brown v. Board, May 1954: school segregation ruled unconstitutional",
                        "Rosa Parks, December 1955: arrest sparks the Montgomery Bus Boycott",
                        "381 days of walking won desegregated buses",
                        "MLK emerges as the movement's leading voice",
                    ],
                },
                {
                    "h2": "Nonviolence on the march: 1960 to 1963",
                    "paras": [
                        "The movement's playbook was nonviolent direct action — sit-ins, freedom rides, marches — designed to expose injustice by meeting violence with discipline. In 1960, college students launched sit-ins at segregated lunch counters (starting in Greensboro, North Carolina); in 1961, Freedom Riders rode integrated buses through the South and were beaten for it. In 1963, King's campaign in Birmingham, Alabama — where police turned dogs and fire hoses on children — shocked a nation watching on TV.",
                        "That August, about 250,000 people marched on Washington for jobs and freedom, where King delivered his 'I Have a Dream' speech at the Lincoln Memorial. The images were irresistible: the movement's discipline against segregation's brutality. President Kennedy had proposed a civil rights bill; after his assassination, President Lyndon Johnson pushed it through as the Civil Rights Act of 1964, banning segregation in public places and employment discrimination.",
                    ],
                    "bullets": [
                        "Sit-ins (1960) and Freedom Rides (1961): students lead",
                        "Birmingham 1963: dogs and fire hoses on TV changed opinions",
                        "March on Washington, August 1963: 'I Have a Dream'",
                        "Civil Rights Act of 1964: bans segregation in public places and job discrimination",
                        "Nonviolence as strategy: expose injustice, win the nation",
                    ],
                },
                {
                    "h2": "Votes and legacy: Selma to 1968",
                    "paras": [
                        "Segregation's other pillar was voting denial: literacy tests, poll taxes and violence kept Black Southerners from the polls. In March 1965, marchers setting out from Selma, Alabama, were beaten by police on the Edmund Pettus Bridge — 'Bloody Sunday,' broadcast nationwide. A protected second march reached Montgomery, and that August the Voting Rights Act of 1965 banned the discriminatory tests and sent federal registrars South.",
                        "The movement won its central legal battles but at a cost: King was assassinated in Memphis on April 4, 1968, at age 39, and the Fair Housing Act passed days later as a memorial. The movement's methods — nonviolent mass protest, legal challenges, boycotts — became the template for nearly every justice movement since, and its unfinished business still shapes American life today.",
                    ],
                    "bullets": [
                        "Selma marches, March 1965: 'Bloody Sunday' shocks the nation",
                        "Voting Rights Act, August 1965: bans literacy tests and poll taxes",
                        "MLK assassinated April 4, 1968, in Memphis",
                        "Fair Housing Act, 1968: the era's final major law",
                        "Legacy: the template for modern rights movements",
                    ],
                    "example": {
                        "title": "How to remember this timeline",
                        "body": "Drill five numbers: '54 school (Brown), '55 bus (Montgomery), '63 speech (March on Washington), '64 public places (Civil Rights Act), '65 votes (Voting Rights Act). School, bus, speech, places, votes — each year one step toward full citizenship.",
                    },
                },
            ],
            "key_concepts": [
                ("Segregation / Jim Crow", "Laws enforcing racial separation in public life under the fiction of 'separate but equal.'"),
                ("Brown v. Board of Education", "The 1954 Supreme Court ruling that school segregation is unconstitutional — separate is inherently unequal."),
                ("Boycott", "Refusing to use or buy from a business to force change; the Montgomery boycott lasted 381 days."),
                ("Nonviolent resistance", "Protest without violence, meeting brutality with discipline — the movement's core strategy."),
                ("Sit-in", "Protesters occupying segregated seats and refusing to leave until served or arrested."),
                ("March on Washington", "The August 1963 mass protest where MLK delivered 'I Have a Dream.'"),
                ("Civil Rights Act of 1964", "Federal law banning segregation in public accommodations and employment discrimination."),
                ("Voting Rights Act of 1965", "Federal law banning literacy tests and protecting Black voting rights."),
            ],
            "study_tips": [
                "Drill the five-number spine: '54, '55, '63, '64, '65 — school, bus, speech, places, votes.",
                "For every event, learn the cause AND the result; essay questions live on those pairs.",
                "Flashcard the two acts separately — 1964 (public places and jobs) vs. 1965 (voting).",
                "Know why nonviolence worked as strategy: TV made brutality visible to the whole nation.",
                "Practice connecting figures to moments: Parks–Montgomery, King–Washington, Johnson–the acts.",
            ],
            "practice": [
                {
                    "q": "Brown v. Board of Education (1954) ruled that:",
                    "choices": ["Voting tests must end", "Buses must desegregate", "School segregation is unconstitutional", "Segregated lunch counters are illegal"],
                    "answer": 2,
                    "explain": "Brown struck down school segregation, declaring separate schools 'inherently unequal' — overturning 'separate but equal' in education. The other battles came later.",
                },
                {
                    "q": "Rosa Parks sparked the Montgomery Bus Boycott by:",
                    "choices": ["Refusing to give up her bus seat", "Leading a lunch-counter sit-in", "Founding the NAACP", "Suing a school district"],
                    "answer": 0,
                    "explain": "Her December 1955 arrest for refusing to give up her seat triggered a 381-day boycott that ended with desegregated buses — and launched MLK into national leadership.",
                },
                {
                    "q": "The Civil Rights Act of 1964:",
                    "choices": ["Ended slavery", "Banned segregation in public places and employment discrimination", "Lowered the voting age", "Created the Marshall Plan"],
                    "answer": 1,
                    "explain": "The 1964 act attacked segregation: public accommodations and job discrimination were banned nationwide. Slavery had ended in 1865, and voting rights were the 1965 act's job.",
                },
                {
                    "q": "The Voting Rights Act was passed in:",
                    "choices": ["1963", "1964", "1965", "1968"],
                    "answer": 2,
                    "explain": "After 'Bloody Sunday' at Selma in March 1965, the Voting Rights Act passed that August — banning literacy tests and poll taxes and protecting Black voting rights.",
                },
            ],
            "flashcards": [
                ("Brown v. Board, 1954", "Supreme Court ruling that school segregation is unconstitutional."),
                ("Rosa Parks, December 1955", "Arrested for refusing to give up her bus seat — sparked the Montgomery Bus Boycott."),
                ("Montgomery Bus Boycott length", "381 days; it ended with desegregated buses."),
                ("MLK's famous speech, August 1963", "'I Have a Dream,' at the March on Washington."),
                ("Civil Rights Act of 1964", "Banned segregation in public places and employment discrimination."),
                ("Voting Rights Act of 1965", "Banned literacy tests and poll taxes; protected Black voting rights."),
                ("Bloody Sunday, 1965", "Selma marchers beaten on the Edmund Pettus Bridge — pushed voting rights forward."),
                ("MLK's death", "Assassinated April 4, 1968, in Memphis, Tennessee."),
                ("Jim Crow laws", "State laws enforcing racial segregation under 'separate but equal.'"),
                ("The movement's core strategy", "Nonviolent direct action — boycotts, sit-ins, marches."),
            ],
            "faqs": [
                ("What started the civil rights movement?",
                 "Decades of organizing against Jim Crow burst into mass movement in the 1950s: the Supreme Court's Brown ruling (1954) gave the legal opening, and the Montgomery Bus Boycott (1955–56) gave the mass-protest template and its leader, MLK."),
                ("Why were the Selma marches important?",
                 "Bloody Sunday — police beating peaceful marchers on camera — horrified the country and directly built support for the Voting Rights Act, signed five months later. Selma turned voting rights from demand into law."),
                ("What's the difference between the 1964 and 1965 acts?",
                 "The 1964 act attacked segregation: public places and employment discrimination. The 1965 act attacked voting denial: literacy tests, poll taxes, federal protection of Black voters. One opened doors; the other opened ballot boxes."),
                ("Was the movement only in the South?",
                 "No. Segregation and discrimination were national — Northern cities faced housing and school battles too. The South's Jim Crow system was the movement's main target, but its victories reshaped the whole country."),
            ],
            "paa": [
                ("What was the civil rights movement?", "The 1950s–60s struggle to end legal segregation and secure equal rights for Black Americans — through courts, boycotts, marches and landmark federal laws."),
                ("Who were the key figures of the civil rights movement?", "Martin Luther King Jr., Rosa Parks, Thurgood Marshall (Brown's lead lawyer, later the first Black Supreme Court justice), John Lewis, Fannie Lou Hamer — with Presidents Kennedy and Johnson at the legislative end."),
                ("What did Martin Luther King Jr. do?", "Organized the Montgomery boycott, co-led the SCLC, led Birmingham and the March on Washington, won the 1964 Nobel Peace Prize — and was assassinated in 1968 at 39."),
                ("What ended legal segregation?", "The combination of court rulings (Brown), mass protest (boycotts, sit-ins, marches) and federal law (the Civil Rights Act of 1964 and the Voting Rights Act of 1965)."),
            ],
        },
    ],
}
