"""Physics pillar: 1 pillar page + 6 cluster pages.

Schema (must match exactly — see docs/CONTENT.md and content/topic_math.py):
PILLAR = {slug, title, emoji, meta_title<=62, meta_description<=160, h1,
tagline, summary, keywords[10], longtail[12+], intro[2 paras], bullets[6],
faqs[(q,a)x5], paa[(q,a)x5], clusters[{slug, title, h1, meta_title<=62,
meta_description<=160, summary, keywords[6], longtail[10+],
sections[3-4]{h2, paras[], bullets[], example?{title, body}},
key_concepts[(term,def)x8], study_tips[x5], practice[{q, choices[4],
answer(idx), explain}]x4, flashcards[(front,back)]x10, faqs[(q,a)x4],
paa[(q,a)x4]}]}
"""

PILLAR = {
    "slug": "physics",
    "title": "Physics",
    "emoji": "⚛️",
    "meta_title": "Free Physics Study Hub — Learn Physics Fast | StudyBonk",
    "meta_description": "Free physics study guides, flashcards and quizzes: motion, energy, waves, electricity and light. No sign-up, gamified, 100% private. Start bonking physics.",
    "h1": "Free Physics Study Hub: Learn Physics Fast, One Bonk at a Time",
    "tagline": "From Newton's laws to light waves — free guides, decks and quizzes that make physics finally click.",
    "summary": "Free physics guides, flashcard decks and practice quizzes for motion, energy, waves, electricity, magnetism and light.",
    "keywords": [
        "physics help",
        "learn physics online free",
        "physics flashcards",
        "physics practice questions",
        "newton's laws explained",
        "kinetic and potential energy",
        "ohm's law practice",
        "waves and sound basics",
        "free study app",
        "study tool",
    ],
    "longtail": [
        "how to study physics effectively for exams",
        "best free website to learn physics step by step",
        "why is physics so hard for me",
        "how to memorize physics formulas fast",
        "difference between speed and velocity in simple terms",
        "newton's three laws explained with everyday examples",
        "kinetic vs potential energy with real examples",
        "ohm's law practice problems with answers",
        "how does the doppler effect work in simple terms",
        "how do electric motors work simply explained",
        "concave vs convex lens difference",
        "physics study plan for high school students",
        "how to catch up in physics when you're behind",
    ],
    "intro": [
        "Physics explains why a curveball curves, why the sky is blue and why you slide forward when the bus brakes. The problem is that most physics resources either bury you in equations or skip the 'why' entirely. StudyBonk splits the difference: short, plain-English lessons, flashcard decks that drill the formulas, and quizzes that explain every answer.",
        "Every page below is 100% free, works without an account, and saves your progress right in your browser. Earn XP, keep your streak alive, and turn the subject that confuses everyone into the one that finally makes sense.",
    ],
    "bullets": [
        "Describe motion with speed, velocity and acceleration",
        "Apply Newton's three laws to real situations",
        "Calculate kinetic and potential energy — and watch energy conserve",
        "Break down waves: wavelength, frequency and pitch",
        "Master Ohm's law and series vs parallel circuits",
        "Explain reflection, refraction, lenses and color",
    ],
    "faqs": [
        ("Is StudyBonk good for learning physics?",
         "Yes. StudyBonk gives you short lessons, spaced-repetition flashcard decks and practice quizzes with explanations for core physics topics from motion through light and optics. It's free, requires no account, and works offline after the first load."),
        ("Do I need to be good at math for physics?",
         "You need basic algebra — plugging into formulas and rearranging them — not advanced math. If you can solve 2x + 6 = 14, you can handle F = ma. StudyBonk's math pillar covers anything you need to brush up on."),
        ("How much should I study physics per day?",
         "Most students see real progress with 20–30 focused minutes a day. Physics rewards daily problem-solving over marathon reading: each solved problem is a rep that makes the next one easier."),
        ("What's the best way to memorize physics formulas?",
         "Don't memorize naked formulas — memorize what each symbol means and when the formula applies. Then drill with flashcards until recall is instant. A formula you can explain is a formula you can use."),
        ("Is StudyBonk really free with no account?",
         "Really free, really no account. No ads, no paywalls, no email capture, no tracking. Everything saves in your browser's local storage, and the code is open-source on GitHub so you can verify it yourself."),
    ],
    "paa": [
        ("What is the fastest way to learn physics?",
         "Short daily practice with active recall: read one concept, then immediately self-test with flashcards and problems instead of re-reading. StudyBonk automates that loop for you."),
        ("Why is physics so hard for me?",
         "Usually because the symbols arrive before the ideas. Learn what each quantity means in plain English first — force as a push, voltage as a push on charge — then add the equations. The math is rarely the hard part."),
        ("What are the main topics in intro physics?",
         "Motion and forces, energy, waves and sound, electricity, magnetism, and light. Each builds on the last, and StudyBonk covers all six."),
        ("Can I learn physics on my own?",
         "Yes, especially the fundamentals. Short lessons plus instant self-testing with feedback will carry you most of the way; teachers, tutors and AI tutors are for the two or three sticking points."),
        ("Is physics harder than math?",
         "Physics is math wearing a story: every equation describes something you can picture. Students who visualize the situation before computing usually find physics easier than pure math."),
    ],
    "clusters": [
        {
            "slug": "motion-and-forces",
            "title": "Motion and Forces",
            "h1": "Motion and Forces Explained: Speed, Acceleration & Newton's Laws",
            "meta_title": "Motion and Forces Made Easy — Free Guide | StudyBonk",
            "meta_description": "Learn motion and forces free: speed vs velocity, acceleration, Newton's three laws and gravity — with worked problems, flashcards and a quiz. No sign-up.",
            "summary": "Speed, velocity, acceleration and Newton's three laws — explained with skateboarders, not jargon.",
            "keywords": [
                "motion and forces",
                "newton's laws explained",
                "speed vs velocity",
                "acceleration formula",
                "physics motion help",
                "free physics practice",
            ],
            "longtail": [
                "difference between speed and velocity in simple terms",
                "how to calculate average speed step by step",
                "what does acceleration mean in physics for beginners",
                "newton's first law of motion explained with examples",
                "newton's second law practice problems with answers",
                "what is the difference between mass and weight",
                "how does friction affect motion in simple terms",
                "why do objects fall at the same rate in a vacuum",
                "balanced vs unbalanced forces explained",
                "how to solve motion problems in physics",
                "what is net force and how do you find it",
            ],
            "sections": [
                {
                    "h2": "Describing motion: speed, velocity and acceleration",
                    "paras": [
                        "Physics starts with describing how things move. Speed is how fast you go — distance divided by time. Velocity is speed plus a direction: 30 m/s north is a velocity, while 30 m/s is just a speed. On tests, that one word 'direction' is the whole difference between the two.",
                        "Acceleration is any change in velocity over time — speeding up, slowing down, or turning. Yes, slowing down counts: it's acceleration pointing opposite your motion. A car rounding a bend at a steady 30 m/s is still accelerating, because its direction is changing.",
                    ],
                    "bullets": [
                        "Speed = distance ÷ time, measured in m/s",
                        "Velocity = speed with a direction (30 m/s east)",
                        "Acceleration = change in velocity ÷ time, measured in m/s²",
                        "Slowing down and turning both count as acceleration",
                        "Distance vs displacement: the path you took vs the straight-line change in position",
                    ],
                    "example": {
                        "title": "Worked example: average speed",
                        "body": "A skateboarder covers 60 meters in 12 seconds. Speed = distance ÷ time = 60 ÷ 12 = 5 m/s. If she rides the same 60 m back, her distance is 120 m but her displacement is 0 — she's back where she started.",
                    },
                },
                {
                    "h2": "Newton's three laws, minus the headache",
                    "paras": [
                        "First law (inertia): an object keeps doing what it's doing — resting or moving in a straight line at constant speed — unless a net force acts on it. That's why you lurch forward when a bus brakes: your body was moving, and it wants to keep moving.",
                        "Second law: net force equals mass times acceleration, F = ma. Bigger force, bigger acceleration; bigger mass, smaller acceleration for the same push. Third law: forces come in pairs — for every action force there's an equal and opposite reaction force, which is why rockets fly by pushing gas down.",
                    ],
                    "bullets": [
                        "1st law: no net force → no change in motion (inertia)",
                        "2nd law: F = ma — force (N) = mass (kg) × acceleration (m/s²)",
                        "3rd law: every push is paired with an equal push back",
                        "Mass measures 'how much stuff'; weight is the force of gravity on it",
                    ],
                    "example": {
                        "title": "Worked example: F = ma",
                        "body": "A 1,500 kg car accelerates at 2 m/s². F = ma = 1,500 × 2 = 3,000 N of net force. Notice the units: kilograms times meters per second squared gives newtons.",
                    },
                },
                {
                    "h2": "Net force, friction and falling",
                    "paras": [
                        "Forces are pushes and pulls, and they add. Net force is the total after combining them: equal pushes in opposite directions cancel to zero (balanced forces → constant velocity or stillness), while any leftover force (unbalanced) causes acceleration. Friction is the force that opposes sliding between surfaces — it's why a rolling ball eventually stops.",
                        "Gravity pulls every object toward Earth at about 9.8 m/s², written g. Your weight is W = mg: a 50 kg student weighs about 490 N on Earth but only about 80 N on the Moon. In a vacuum a hammer and a feather fall together, because gravity accelerates everything the same — air resistance, not mass, is what makes real falls look different.",
                    ],
                    "bullets": [
                        "Balanced forces → no change in motion; unbalanced → acceleration",
                        "Friction opposes sliding between surfaces",
                        "Gravity accelerates falling objects at g ≈ 9.8 m/s²",
                        "Weight = mg (a force, in newtons); mass never changes with location",
                        "Air resistance slows real falls; in a vacuum all objects fall together",
                    ],
                },
            ],
            "key_concepts": [
                ("Speed", "Distance traveled divided by time — how fast, with no direction attached."),
                ("Velocity", "Speed in a stated direction; 20 m/s south is a velocity."),
                ("Acceleration", "Any change in velocity over time: speeding up, slowing down, or turning."),
                ("Force", "A push or pull, measured in newtons (N)."),
                ("Net force", "The combined total of all forces on an object; only an unbalanced net force changes motion."),
                ("Inertia", "An object's resistance to changes in its motion; more mass means more inertia."),
                ("Friction", "A force opposing sliding between two surfaces, converting motion into heat."),
                ("Weight", "The force of gravity on an object's mass: W = mg."),
            ],
            "study_tips": [
                "Say formulas in words every time — 'speed is distance over time' — until the symbols feel like nicknames.",
                "Draw every problem: a sketch with arrows for forces makes net force visible.",
                "Check units at the end; if the units are wrong, the answer is wrong.",
                "Drill F = ma with three different unknowns (F, m, a) so rearranging becomes automatic.",
                "Redo missed problems 24 hours later — physics skill is built from reps, not reading.",
            ],
            "practice": [
                {
                    "q": "A cyclist rides 120 meters in 20 seconds. Average speed?",
                    "choices": ["6 m/s", "100 m/s", "2,400 m/s", "0.17 m/s"],
                    "answer": 0,
                    "explain": "Speed = distance ÷ time = 120 ÷ 20 = 6 m/s. The huge and tiny choices are unit traps from multiplying or inverting.",
                },
                {
                    "q": "Net force on a 3 kg cart accelerating at 4 m/s²?",
                    "choices": ["7 N", "0.75 N", "12 N", "1.33 N"],
                    "answer": 2,
                    "explain": "F = ma = 3 × 4 = 12 N. The other answers come from adding (7) or dividing (0.75) instead of multiplying.",
                },
                {
                    "q": "You push a heavy box but it doesn't move. The forces on it are:",
                    "choices": ["Unbalanced, so it accelerates", "Balanced — your push is matched by friction", "Zero — no forces act", "Reversed by gravity"],
                    "answer": 1,
                    "explain": "No motion means no change in motion, so the net force is zero: friction pushes back exactly as hard as you push. That's Newton's first law in action.",
                },
                {
                    "q": "A rocket pushes exhaust gas downward; the gas pushes the rocket upward. Which law?",
                    "choices": ["First law", "Second law", "Third law", "Law of gravity"],
                    "answer": 2,
                    "explain": "Equal-and-opposite force pairs are Newton's third law. The rocket rises because it pushes gas down and the gas pushes back up.",
                },
            ],
            "flashcards": [
                ("Speed formula", "v = d/t — distance divided by time (m/s)."),
                ("Speed vs velocity", "Velocity is speed plus a direction; 25 m/s east is a velocity."),
                ("Acceleration formula", "a = (final velocity − starting velocity) ÷ time."),
                ("Units of acceleration", "m/s² — meters per second, per second."),
                ("Newton's 1st law", "An object at rest stays at rest and an object in motion keeps moving unless a net force acts (inertia)."),
                ("Newton's 2nd law", "F = ma — force equals mass times acceleration."),
                ("Newton's 3rd law", "Every action force has an equal and opposite reaction force."),
                ("Unit of force", "The newton (N) = 1 kg · m/s²."),
                ("Weight formula", "W = mg, with g ≈ 9.8 m/s² on Earth."),
                ("Mass vs weight", "Mass is the amount of matter (kg); weight is gravity's force on it (N) and changes with location."),
            ],
            "faqs": [
                ("What's the difference between speed and velocity?",
                 "Speed is just how fast (a number); velocity is how fast AND which way. A car driving in a circle at a steady 30 m/s has constant speed but changing velocity, because its direction keeps changing."),
                ("Is slowing down negative acceleration?",
                 "It's acceleration pointing opposite the motion — often written with a minus sign if forward is positive. 'Deceleration' is the everyday word; in physics it's still acceleration, just backward relative to the motion."),
                ("Do heavier objects fall faster?",
                 "Without air, no — gravity gives every object the same 9.8 m/s². A feather loses only because air resistance hits it hard relative to its weight. On the Moon (no air), Apollo astronauts dropped a hammer and a feather and they landed together."),
                ("How do I know when to use F = ma?",
                 "Whenever a net force and motion are connected: know force and mass, find acceleration; know mass and acceleration, find the force. Rearrange the same triangle — F = ma, m = F/a, a = F/m — like any formula."),
            ],
            "paa": [
                ("What are Newton's three laws in simple words?", "1) Things keep doing what they're doing unless a force acts. 2) Force = mass × acceleration. 3) Every push is paired with an equal push back the other way."),
                ("What is net force?", "All the forces on an object added together, accounting for direction. Zero net force means no change in motion; any leftover force accelerates the object."),
                ("Why do you fall forward when a bus stops?", "Inertia: your body was moving with the bus and keeps moving until your seatbelt or grip applies a backward force to slow you."),
                ("What units does physics use for motion?", "Speed in m/s, acceleration in m/s², force in newtons (N), mass in kilograms. Keeping units straight catches most errors before they happen."),
            ],
        },
        {
            "slug": "energy-work-power",
            "title": "Energy, Work and Power",
            "h1": "Energy, Work and Power: Kinetic, Potential & Conservation",
            "meta_title": "Energy, Work and Power Explained Simply | StudyBonk",
            "meta_description": "Master energy, work and power free: kinetic and potential energy, conservation of energy, W = Fd and P = W/t — with worked examples, flashcards and a quiz.",
            "summary": "Kinetic, potential, work and power — the ideas plus the four formulas that run them all.",
            "keywords": [
                "kinetic and potential energy",
                "conservation of energy",
                "work and power physics",
                "energy transformations",
                "physics energy formulas",
                "free physics practice",
            ],
            "longtail": [
                "kinetic vs potential energy explained with examples",
                "how to calculate kinetic energy step by step",
                "what does the law of conservation of energy mean",
                "how does a roller coaster use potential and kinetic energy",
                "physics work formula explained for beginners",
                "difference between work and power in physics",
                "how to calculate gravitational potential energy",
                "what happens to energy when friction slows something down",
                "real life examples of energy transformations",
                "what is a joule and what does it measure",
                "how is power calculated in physics",
            ],
            "sections": [
                {
                    "h2": "Kinetic and potential energy: motion and position",
                    "paras": [
                        "Energy is the ability to do stuff — lift, heat, move, glow. Physicists sort it into two big bins. Kinetic energy (KE) is energy of motion: anything moving has it. Potential energy (PE) is stored energy of position or condition: a stretched rubber band, a book on a high shelf, a sandwich (chemical PE).",
                        "The formulas: KE = ½mv² (mass times speed squared, halved) and gravitational PE = mgh (mass times g times height). Notice that speed is squared in KE — double your speed and your energy quadruples, which is why highway crashes are so much worse than parking-lot ones.",
                    ],
                    "bullets": [
                        "KE = ½mv² — energy of motion, in joules",
                        "PE = mgh — stored energy from height above the ground",
                        "Speed is squared in KE: 2× speed = 4× energy",
                        "Types of PE: gravitational (height), elastic (stretch), chemical (food, fuel)",
                        "Energy unit: the joule (J)",
                    ],
                },
                {
                    "h2": "Conservation of energy: the universe's budget",
                    "paras": [
                        "The law of conservation of energy says energy is never created or destroyed — only transformed. A falling book trades PE for KE: at the top it has maximum PE and zero KE; mid-fall it has some of each; just before impact, nearly all PE has become KE. The total stays constant the whole way down.",
                        "A roller coaster is conservation in action: the first hill charges the car with PE, and every later hill, loop and valley is that energy switching between PE and KE. Friction and air resistance skim off a little as heat and sound — which is why the second hill is always shorter than the first.",
                    ],
                    "bullets": [
                        "Energy transforms; it never disappears",
                        "Falling: PE → KE · being thrown upward: KE → PE",
                        "Friction converts mechanical energy into heat",
                        "Total energy before = total energy after (counting heat)",
                    ],
                    "example": {
                        "title": "Worked example: energy of a falling ball",
                        "body": "Drop a 1 kg ball from 20 m (use g ≈ 9.8 m/s²). PE at the top = mgh = 1 × 9.8 × 20 = 196 J. Just before impact all of that is KE, so 196 = ½(1)v² → v² = 392 → v ≈ 19.8 m/s. You found the speed without touching the motion equations.",
                    },
                },
                {
                    "h2": "Work and power: getting things done",
                    "paras": [
                        "In physics, work is force applied over a distance: W = Fd. Push a box with 50 N across 3 m and you do 150 J of work. Two rules keep it honest: the object has to actually move, and pushing at right angles to the motion does zero work. Holding a heavy box perfectly still is exhausting, but it does no physics work — no distance, no work.",
                        "Power is how fast you do work: P = W/t, measured in watts (1 watt = 1 joule per second). Sprinting up the stairs takes more power than strolling, even though the work is identical — same energy, less time.",
                    ],
                    "bullets": [
                        "Work = force × distance (W = Fd), in joules",
                        "No movement → no work, no matter how tired you feel",
                        "Power = work ÷ time (P = W/t), in watts",
                        "1 watt = 1 joule per second",
                        "Same job done faster = more power",
                    ],
                    "example": {
                        "title": "Worked example: lifting a box",
                        "body": "You lift a 50 N box 2 m in 4 seconds. Work = Fd = 50 × 2 = 100 J. Power = W/t = 100 ÷ 4 = 25 W. Lift it in 2 seconds instead and the work is still 100 J, but the power doubles to 50 W.",
                    },
                },
            ],
            "key_concepts": [
                ("Kinetic energy (KE)", "Energy of motion: KE = ½mv²."),
                ("Potential energy (PE)", "Stored energy of position or condition: gravitational PE = mgh."),
                ("Law of conservation of energy", "Energy cannot be created or destroyed, only transformed from one form to another."),
                ("Joule (J)", "The unit of energy and work; 1 J lifts an apple about 1 meter."),
                ("Work", "Force applied over a distance in the direction of the force: W = Fd."),
                ("Power", "The rate of doing work: P = W/t, measured in watts."),
                ("Watt (W)", "One joule of work per second."),
                ("Energy transformation", "A change of energy from one form to another, like PE → KE as a ball drops."),
            ],
            "study_tips": [
                "Memorize the four formulas as a family: KE = ½mv², PE = mgh, W = Fd, P = W/t.",
                "For conservation problems, write 'energy at start = energy at end' before plugging in anything.",
                "Trace one full energy story out loud (toaster: electrical → heat; s'mores optional).",
                "Keep g as a letter until the last step — it makes canceling visible.",
                "Do one numeric problem per formula per day for a week and the whole chapter stops being scary.",
            ],
            "practice": [
                {
                    "q": "Kinetic energy of a 4 kg ball moving at 3 m/s?",
                    "choices": ["18 J", "12 J", "36 J", "6 J"],
                    "answer": 0,
                    "explain": "KE = ½mv² = ½ × 4 × 3² = ½ × 4 × 9 = 18 J. Forgetting the ½ (36 J) or squaring wrongly (12 J) are the classic slips.",
                },
                {
                    "q": "Potential energy of a 2 kg book on a 3 m shelf? (Use g ≈ 10 m/s².)",
                    "choices": ["6 J", "20 J", "60 J", "15 J"],
                    "answer": 2,
                    "explain": "PE = mgh = 2 × 10 × 3 = 60 J. Multiplying only two of the three quantities gives the trap answers.",
                },
                {
                    "q": "A ball rolls off a table. As it falls, potential energy turns into:",
                    "choices": ["Kinetic energy", "More potential energy", "Nothing — it's lost", "Chemical energy"],
                    "answer": 0,
                    "explain": "Height drops, speed rises: PE converts to KE. Energy isn't lost — it's transformed, per conservation of energy.",
                },
                {
                    "q": "You do 600 J of work in 12 s. Your power output is:",
                    "choices": ["5 W", "50 W", "72 W", "7,200 W"],
                    "answer": 1,
                    "explain": "P = W/t = 600 ÷ 12 = 50 W. Multiplying instead of dividing gives 7,200 W — check units to catch it.",
                },
            ],
            "flashcards": [
                ("Kinetic energy formula", "KE = ½mv² — half of mass times speed squared."),
                ("Potential energy formula (gravity)", "PE = mgh — mass times g times height."),
                ("Unit of energy", "The joule (J)."),
                ("Law of conservation of energy", "Energy is never created or destroyed — only transformed."),
                ("Roller coaster energy story", "First hill = maximum PE; PE trades to KE on the way down; friction leaks some to heat and sound."),
                ("Work formula", "W = Fd — force times distance moved in the force's direction."),
                ("Power formula", "P = W/t — work divided by time."),
                ("Unit of power", "The watt (W); 1 watt = 1 joule per second."),
                ("Why highway crashes are worse", "KE squares the speed — double speed means four times the energy."),
                ("What friction does to energy", "Converts mechanical energy into heat — energy isn't lost, just spread out."),
            ],
            "faqs": [
                ("What is the difference between kinetic and potential energy?",
                 "Kinetic is energy of motion — a moving car, a flying ball. Potential is stored energy waiting to act — the ball at the top of its throw, a stretched spring, gasoline. Drop something and PE smoothly becomes KE."),
                ("Can energy ever be destroyed?",
                 "No — that's the law of conservation of energy. It only changes form. When a ball stops bouncing, the 'lost' energy became heat and sound. Energy accounting always balances."),
                ("Why is holding a heavy box not 'work' in physics?",
                 "Physics work requires the object to move through a distance: W = Fd. Holding still means d = 0, so work = 0 — even though your muscles burn energy tensing. Physics words don't always match everyday words."),
                ("What's the difference between energy and power?",
                 "Energy is the total work done; power is how fast it's done. Same stairs, same energy — sprinting them takes more power. Your electric bill charges for energy (kWh); appliances are rated in power (watts)."),
            ],
            "paa": [
                ("What does conservation of energy mean?", "Total energy stays constant: it changes form (PE ↔ KE ↔ heat) but the grand total never changes."),
                ("How do you calculate kinetic energy?", "KE = ½mv². Mass in kilograms, speed in m/s, answer in joules. The squared speed is the part people forget."),
                ("What are examples of potential energy?", "A book on a shelf (gravitational), a stretched rubber band (elastic), food and fuel (chemical), a charged battery (electrical potential)."),
                ("Is power the same as work?", "No — work is energy transferred (joules); power is the pace of transfer (joules per second, i.e. watts)."),
            ],
        },
        {
            "slug": "waves-and-sound",
            "title": "Waves and Sound",
            "h1": "Waves and Sound Explained: Wave Anatomy, Frequency & Doppler",
            "meta_title": "Waves and Sound Made Easy — Free Guide | StudyBonk",
            "meta_description": "Learn waves and sound free: wave anatomy, frequency and pitch, the wave equation v = f × λ and the Doppler effect — with examples, flashcards and a quiz.",
            "summary": "Crests, wavelengths, frequency and the Doppler effect — waves finally drawn to make sense.",
            "keywords": [
                "waves and sound",
                "wave anatomy",
                "frequency and pitch",
                "doppler effect explained",
                "wave speed formula",
                "physics sound help",
            ],
            "longtail": [
                "parts of a wave labeled and explained",
                "difference between transverse and longitudinal waves",
                "what is frequency in simple terms",
                "how does frequency affect pitch",
                "how to use the wave equation v = f times wavelength",
                "what does amplitude have to do with loudness",
                "why can't sound travel through space",
                "how does the doppler effect work in simple terms",
                "what is the difference between pitch and volume",
                "how do echoes and sonar work",
                "what is the period of a wave",
            ],
            "sections": [
                {
                    "h2": "Anatomy of a wave",
                    "paras": [
                        "A wave is a traveling disturbance that carries energy without carrying stuff along with it. Ocean buoys rise and fall but never cross the sea — the wave's energy does. Two families cover everything: transverse waves wiggle perpendicular to the direction of travel (light, stadium waves), while longitudinal waves wiggle parallel to travel, squeezing and stretching the medium (sound).",
                        "Learn the parts on a transverse wave sketch: crests (tops), troughs (bottoms), wavelength λ (crest-to-crest distance), amplitude (height from the resting position to a crest) and frequency f (how many waves pass a point each second, in hertz). Amplitude is energy's volume knob; wavelength and frequency are its identity.",
                    ],
                    "bullets": [
                        "Crest = top · Trough = bottom",
                        "Wavelength (λ): distance from crest to crest (or trough to trough)",
                        "Amplitude: height away from the rest position — bigger = more energy",
                        "Frequency (f): waves per second, in hertz (Hz)",
                        "Transverse wiggles sideways (light); longitudinal squeezes forward (sound)",
                    ],
                },
                {
                    "h2": "Frequency, pitch and the wave equation",
                    "paras": [
                        "For sound, frequency is pitch: high f = squeaky, low f = rumble. Humans hear roughly 20 Hz to 20,000 Hz, and dogs comfortably beat the top of that range. Amplitude is loudness — a stronger swing carries more energy to your eardrum.",
                        "All waves obey one equation: v = f × λ — wave speed equals frequency times wavelength. For sound in room-temperature air, v ≈ 343 m/s no matter what's playing, so a higher frequency automatically comes with a shorter wavelength. Frequency is set by the source; speed is set by the medium.",
                    ],
                    "bullets": [
                        "v = fλ: speed (m/s) = frequency (Hz) × wavelength (m)",
                        "High frequency = high pitch; amplitude = loudness",
                        "Sound in air travels about 343 m/s",
                        "Period T = 1/f — seconds per wave",
                    ],
                    "example": {
                        "title": "Worked example: wavelength of a concert A",
                        "body": "A violin plays A above middle C at 440 Hz. In air, v = fλ → 343 = 440 × λ, so λ = 343 ÷ 440 ≈ 0.78 m. Doubling the frequency to 880 Hz halves the wavelength to about 0.39 m — frequency and wavelength always trade off like this in the same medium.",
                    },
                },
                {
                    "h2": "The Doppler effect, echoes and silent space",
                    "paras": [
                        "The Doppler effect: when a wave source moves toward you, each wave crest starts slightly closer than the last, so they arrive more often — higher frequency, higher pitch. Moving away stretches the waves — lower pitch. The ambulance siren's slide as it passes is the classic demo, and race cars and redshifted galaxies play the same trick.",
                        "Sound needs a medium — something to squeeze — which is why space battles are silent no matter what movies say. Echoes are reflections: sonar and bats time the echo's round trip and divide, using distance = (speed of sound × time) ÷ 2.",
                    ],
                    "bullets": [
                        "Source moving toward you → waves bunch → higher pitch",
                        "Source moving away → waves stretch → lower pitch",
                        "Sound needs a medium: no air, no sound",
                        "Echo ranging: distance = (speed of sound × time) ÷ 2",
                        "Light does it too: galaxies moving away look redder (redshift)",
                    ],
                },
            ],
            "key_concepts": [
                ("Crest and trough", "The highest and lowest points of a transverse wave."),
                ("Wavelength (λ)", "The distance between two matching points on adjacent waves, like crest to crest."),
                ("Amplitude", "The wave's height from the rest position; a measure of the wave's energy (loudness for sound)."),
                ("Frequency (f)", "The number of waves passing a point per second, measured in hertz (Hz)."),
                ("Hertz (Hz)", "The unit of frequency: 1 Hz = 1 wave per second."),
                ("Period (T)", "The time for one full wave: T = 1/f."),
                ("Medium", "The material a wave travels through — air, water, steel. Sound requires one; light doesn't."),
                ("Doppler effect", "The apparent shift in frequency when the source or listener is moving — the passing-siren pitch slide."),
            ],
            "study_tips": [
                "Sketch and label one wave per study session until crest, trough, λ and amplitude are automatic.",
                "Chant 'v equals f lambda' and practice the three rearrangements (f = v/λ, λ = v/f).",
                "Link each term to a sense: frequency = pitch, amplitude = loudness.",
                "Explain the Doppler effect to someone using a toy car and a hum — teaching it proves you know it.",
                "Use the flashcards for unit checks: Hz, m, m/s — units catch most wave-equation errors.",
            ],
            "practice": [
                {
                    "q": "A wave has frequency 10 Hz and wavelength 2 m. Its speed is:",
                    "choices": ["20 m/s", "5 m/s", "12 m/s", "0.2 m/s"],
                    "answer": 0,
                    "explain": "v = fλ = 10 × 2 = 20 m/s. Dividing instead of multiplying gives 5 m/s — the most common slip.",
                },
                {
                    "q": "The distance from one crest to the next crest is the wave's:",
                    "choices": ["Amplitude", "Wavelength", "Frequency", "Period"],
                    "answer": 1,
                    "explain": "Crest-to-crest distance is wavelength (λ). Amplitude is measured from the rest position to a crest, not crest to crest.",
                },
                {
                    "q": "An ambulance passes you and the siren's pitch drops. This is:",
                    "choices": ["Reflection", "Refraction", "The Doppler effect", "Resonance"],
                    "answer": 2,
                    "explain": "As the siren moves away, each sound wave starts farther from you, so waves arrive less often — lower frequency, lower pitch. That's the Doppler effect.",
                },
                {
                    "q": "Sound cannot travel through space because:",
                    "choices": ["Space is too cold", "Sound is too fast", "Light waves block it", "Sound needs a medium, and space is nearly empty"],
                    "answer": 3,
                    "explain": "Sound is a vibration of matter. With almost no air or anything else to vibrate, there's nothing to carry it — movie explosions are artistic license.",
                },
            ],
            "flashcards": [
                ("Wave speed equation", "v = f × λ (speed = frequency × wavelength)."),
                ("Crest and trough", "Crest = highest point; trough = lowest point of a wave."),
                ("Wavelength symbol and meaning", "λ — the distance between matching points, like crest to crest."),
                ("Amplitude means", "Height from the rest position — bigger amplitude, more energy, louder sound."),
                ("Frequency means", "Waves per second, in hertz (Hz)."),
                ("Frequency's effect on pitch", "Higher frequency = higher pitch; lower frequency = lower pitch."),
                ("Period formula", "T = 1/f — seconds per wave."),
                ("Speed of sound in air", "About 343 m/s at room temperature."),
                ("Doppler effect in one line", "Moving toward = bunched waves = higher pitch; moving away = stretched = lower pitch."),
                ("Why space is silent", "Sound is a vibration of a medium — with no air, there's nothing to vibrate."),
            ],
            "faqs": [
                ("Do all waves need a medium?",
                 "Mechanical waves do — sound, water waves, earthquakes. Light and other electromagnetic waves don't; that's how sunlight crosses empty space while sound can't."),
                ("What's the difference between pitch and loudness?",
                 "Pitch is frequency (how many waves per second hit your ear); loudness is amplitude (how hard they hit). A whistle is high pitch; a shout is high amplitude."),
                ("What exactly is the Doppler effect?",
                 "A frequency shift caused by motion. Source approaching = waves arrive more often = higher pitch; receding = stretched waves = lower pitch. Radar guns and weather radar use the same physics."),
                ("How do bats 'see' with sound?",
                 "Echolocation: they send out high-frequency squeaks and time the echoes. Distance = speed of sound × time ÷ 2 — the ÷2 because the sound makes a round trip. Sonar and ultrasound imaging use the same math."),
            ],
            "paa": [
                ("What are the parts of a wave?", "Crest (top), trough (bottom), wavelength (crest-to-crest distance), amplitude (height from rest), and frequency (waves per second)."),
                ("How are frequency and wavelength related?", "Through the wave equation v = fλ. In a given medium speed is fixed, so frequency up means wavelength down — they trade off."),
                ("Why does an ambulance siren change pitch as it passes?", "The Doppler effect: approaching bunches the sound waves (higher pitch), receding stretches them (lower pitch)."),
                ("Can you hear sound in space?", "No. Sound needs a material to vibrate, and space is nearly empty. Explosions in space movies are artistic license."),
            ],
        },
        {
            "slug": "electricity-basics",
            "title": "Electricity Basics",
            "h1": "Electricity Basics: Charge, Current, Voltage & Ohm's Law",
            "meta_title": "Electricity Basics: Current, Voltage, Ohm's Law | StudyBonk",
            "meta_description": "Learn electricity free: charge, current, voltage, resistance, Ohm's law, and series vs parallel circuits — with worked examples, flashcards and a quiz.",
            "summary": "Charge, current, voltage, resistance and Ohm's law — the water-park analogy that makes it click.",
            "keywords": [
                "electricity basics",
                "ohm's law practice",
                "current voltage resistance",
                "series vs parallel circuits",
                "physics electricity help",
                "free physics practice",
            ],
            "longtail": [
                "difference between current and voltage in simple terms",
                "what is ohm's law and how do you use it",
                "how to calculate current voltage or resistance",
                "what does a resistor do in a circuit",
                "series vs parallel circuits explained simply",
                "why do bulbs get dimmer in a series circuit",
                "what is electrical charge in simple terms",
                "how does a battery work basics for students",
                "conductor vs insulator examples",
                "what units measure current voltage and resistance",
                "how to remember v = ir",
            ],
            "sections": [
                {
                    "h2": "Charge, current and voltage: the water park analogy",
                    "paras": [
                        "Electricity starts with charge, a property of tiny particles: protons (+) and electrons (−). Opposite charges pull together; like charges push apart. Current is charge in motion — the flow of electrons through a wire — measured in amperes (A).",
                        "Voltage is the push that drives that flow, measured in volts (V) — think of it as electrical pressure. A battery is a pump: it pushes charge out of one end, around the circuit, and back to the other. Resistance (ohms, Ω) is anything that throttles the flow — a thin wire, a resistor, a corroded connection.",
                    ],
                    "bullets": [
                        "Charge comes in two signs: + (protons) and − (electrons)",
                        "Current = flow of charge, measured in amperes (A)",
                        "Voltage = electrical push or pressure, measured in volts (V)",
                        "Resistance = flow throttling, measured in ohms (Ω)",
                        "Water park: current = flow rate, voltage = pump pressure, resistance = pipe narrowness",
                    ],
                },
                {
                    "h2": "Ohm's law: the one equation that runs your phone",
                    "paras": [
                        "Ohm's law links all three: V = IR — voltage equals current times resistance. Bump the voltage with the same resistance and more current flows; add resistance at the same voltage and current shrinks. Rearrange the same equation for any missing piece: I = V/R and R = V/I.",
                        "The standard mistake is plugging in mixed units or grabbing the wrong quantity. Convert to volts, amps and ohms first, write the formula, then substitute. That three-second ritual catches nearly every Ohm's law error.",
                    ],
                    "bullets": [
                        "V = IR · I = V/R · R = V/I",
                        "More voltage (same R) → more current",
                        "More resistance (same V) → less current",
                        "Keep units consistent: V, A, Ω",
                    ],
                    "example": {
                        "title": "Worked example: Ohm's law",
                        "body": "A 9 V battery drives current through a 3 Ω resistor. I = V/R = 9 ÷ 3 = 3 A. Swap in a 6 Ω resistor and current drops to 1.5 A — double the resistance, half the current, exactly as Ohm's law predicts.",
                    },
                },
                {
                    "h2": "Series and parallel circuits",
                    "paras": [
                        "In a series circuit, one path connects everything: the same current squeezes through each device in turn. More bulbs in series means more total resistance and dimmer bulbs — and one burned-out bulb opens the only path, killing the whole string. That's why old Christmas lights died together.",
                        "In a parallel circuit, each device gets its own branch across the same voltage. Every bulb glows at full brightness, one failure doesn't kill the rest, and total resistance drops as you add branches — which is why your house is wired in parallel. Overloaded outlets happen because more parallel branches pull more total current.",
                    ],
                    "bullets": [
                        "Series: one path, same current through everything",
                        "Series: more bulbs → more resistance → dimmer",
                        "Parallel: branches share the same voltage",
                        "Parallel: one dead bulb doesn't kill the others",
                        "Houses are wired in parallel — every outlet gets full voltage",
                    ],
                },
            ],
            "key_concepts": [
                ("Electric charge", "A basic property of matter; protons carry +, electrons carry −. Opposite charges attract."),
                ("Current (I)", "The rate of charge flow past a point, measured in amperes (A)."),
                ("Voltage (V)", "The electrical 'push' or potential difference driving charge, measured in volts."),
                ("Resistance (R)", "How much a material opposes current, measured in ohms (Ω)."),
                ("Ohm's law", "V = IR: voltage equals current times resistance."),
                ("Series circuit", "One loop; identical current everywhere; resistances add."),
                ("Parallel circuit", "Branched paths; each branch gets the full source voltage."),
                ("Conductor vs insulator", "Conductors (copper, most metals) let charge flow; insulators (rubber, plastic, glass) block it."),
            ],
            "study_tips": [
                "Anchor V, I and R to the water analogy first — pressure, flow, narrowness — then attach the symbols.",
                "Drill the Ohm's law triangle: cover the quantity you want; the layout of the other two shows the formula.",
                "Redraw every circuit as a clean rectangle diagram before solving.",
                "Practice unit conversion (milliamps to amps) — mixed units cause most wrong answers.",
                "Predict before you compute ('more resistance should mean less current'), then check; physics gets satisfying when predictions land.",
            ],
            "practice": [
                {
                    "q": "A 9 V battery is connected across a 3 Ω resistor. The current is:",
                    "choices": ["27 A", "3 A", "6 A", "0.33 A"],
                    "answer": 1,
                    "explain": "I = V/R = 9 ÷ 3 = 3 A. Multiplying instead of dividing gives 27 A — a units check catches it (volts ÷ ohms = amps).",
                },
                {
                    "q": "Current is measured in:",
                    "choices": ["Volts", "Ohms", "Amperes", "Joules"],
                    "answer": 2,
                    "explain": "Current — the flow of charge — is measured in amperes (A). Volts push, ohms resist, joules measure energy.",
                },
                {
                    "q": "One bulb burns out in a series circuit. The other bulbs:",
                    "choices": ["Stay lit", "Go dark — the only path is broken", "Get brighter", "Flash on and off"],
                    "answer": 1,
                    "explain": "A series circuit has a single path. One gap stops the current everywhere — that's why one dead bulb killed the whole old-style Christmas light string.",
                },
                {
                    "q": "Which change increases the current in a circuit?",
                    "choices": ["Adding more resistance", "Using a longer, thinner wire", "Removing the battery", "Increasing the voltage"],
                    "answer": 3,
                    "explain": "By V = IR, current rises with voltage and falls with resistance. Thinner, longer wires add resistance, and removing the battery removes the push entirely.",
                },
            ],
            "flashcards": [
                ("Ohm's law", "V = IR — voltage (V) = current (A) × resistance (Ω)."),
                ("Current is measured in", "Amperes (A) — the flow rate of charge."),
                ("Voltage is measured in", "Volts (V) — the electrical push."),
                ("Resistance is measured in", "Ohms (symbol Ω)."),
                ("What carries current in wires?", "Moving electrons (negative charge)."),
                ("Water analogy: voltage", "Pump pressure — how hard the water is pushed."),
                ("Water analogy: current", "Flow rate — how much water passes per second."),
                ("Series circuit rule", "One path, same current everywhere; resistances add; one break kills all."),
                ("Parallel circuit rule", "Branches each get full voltage; one break leaves others working; total resistance drops."),
                ("How to find current from V and R", "I = V ÷ R (Ohm's law rearranged)."),
            ],
            "faqs": [
                ("What's the difference between current and voltage?",
                 "Current is the flow of charge (amperes); voltage is the push driving that flow (volts). River analogy: current is how much water passes per second; voltage is how steep the drop driving it."),
                ("What does a resistor actually do?",
                 "It converts electrical energy into heat while throttling current. That's a feature in a toaster coil and the reason electronics get warm — and why chargers have vents."),
                ("Why are houses wired in parallel?",
                 "So every device gets the full voltage, works independently, and one failure doesn't black out the house. The trade-off: every plugged-in device adds another current-hungry branch, which is how circuits overload."),
                ("Does electricity get 'used up' in a circuit?",
                 "No — charge isn't consumed; energy is. The current leaving a bulb equals the current entering it; the bulb just converts electrical energy into light and heat."),
            ],
            "paa": [
                ("What is Ohm's law in simple words?", "V = IR: the push (volts) equals the flow (amps) times the squeeze-back (ohms). Know any two, find the third."),
                ("Which is dangerous, voltage or current?",
                 "Current through your body is what harms you — but voltage is what pushes that current. Even modest voltages can drive dangerous current through low-resistance paths like wet skin."),
                ("Why are parallel circuits brighter than series?", "Each parallel bulb receives the full source voltage across its own branch. Series bulbs share the voltage, so each gets less and glows dimmer."),
                ("What are conductors and insulators?", "Conductors (copper, aluminum, salt water) let charge flow easily; insulators (rubber, plastic, glass) block it. Wires are copper wrapped in plastic for exactly this reason."),
            ],
        },
        {
            "slug": "magnetism",
            "title": "Magnetism",
            "h1": "Magnetism Explained: Magnetic Fields, Electromagnets & Motors",
            "meta_title": "Magnetism Explained: Fields, Magnets & Motors | StudyBonk",
            "meta_description": "Learn magnetism free: magnetic poles and fields, electromagnets and how motors work — with examples, flashcards and a practice quiz. No sign-up needed.",
            "summary": "Poles, fields, electromagnets and motors — magnetism from fridge magnets to fans.",
            "keywords": [
                "magnetism basics",
                "magnetic fields explained",
                "how electromagnets work",
                "electric motor explained",
                "physics magnetism help",
                "free physics practice",
            ],
            "longtail": [
                "why do magnets attract and repel",
                "what is a magnetic field in simple terms",
                "how to make an electromagnet for a school project",
                "what three things make an electromagnet stronger",
                "how does a compass work explained",
                "difference between permanent magnets and electromagnets",
                "how does an electric motor work step by step",
                "what materials are magnetic and why",
                "why does the earth have a magnetic field",
                "how are electricity and magnetism related",
                "what is a commutator in a motor",
            ],
            "sections": [
                {
                    "h2": "Magnetic poles and fields",
                    "paras": [
                        "Every magnet has two poles: north and south. Like poles repel; opposite poles attract — you've felt magnets shove each other away. Break a magnet in half and you don't get a lone north: you get two smaller complete magnets. Poles always come in pairs.",
                        "A magnetic field is the invisible region of influence around a magnet, drawn as field lines leaving the north pole and curving around to the south. Iron filings sprinkled on paper over a bar magnet trace these lines — one of the best five-minute physics demos there is. The field is strongest where the lines crowd together: at the poles.",
                    ],
                    "bullets": [
                        "North–south attract; north–north and south–south repel",
                        "Breaking a magnet gives two smaller magnets, never a lone pole",
                        "Field lines run out of north and into south, outside the magnet",
                        "Where lines crowd close, the field is strongest (the poles)",
                        "Iron, nickel and cobalt (ferromagnetic) are the magnetic materials",
                    ],
                },
                {
                    "h2": "Electromagnets: magnetism from electricity",
                    "paras": [
                        "In 1820, Hans Oersted noticed a compass needle twitch beside a current-carrying wire — electricity and magnetism are two faces of one thing. Wrap a wire into a coil and send current through it, and you get a magnetic field like a bar magnet's. Add an iron core and the field concentrates: that's an electromagnet.",
                        "Electromagnets beat permanent magnets because you can switch them on and off, reverse them, and tune their strength. Strength grows with more turns of wire, more current and a better core. Junkyard cranes, speakers, doorbells, MRI machines and maglev trains all run on that controllability.",
                    ],
                    "bullets": [
                        "Electric current always creates a magnetic field around it",
                        "Electromagnet = coil of wire + current, usually with an iron core",
                        "More turns, more current, better core = stronger",
                        "On/off and reversible — the superpower permanent magnets lack",
                    ],
                    "example": {
                        "title": "Worked example: doubling the coils",
                        "body": "For a science project, an electromagnet with 50 coils picks up 12 paper clips. You double the turns to 100, and it picks up about 24 — strength scales roughly with the number of turns, so coil count is the cheapest upgrade. Then bump the current with a second battery and watch the count climb again (and the wire warm up).",
                    },
                },
                {
                    "h2": "How motors work",
                    "paras": [
                        "A motor is the loop-the-loop child of electricity and magnetism. Put a current-carrying wire inside a magnetic field, and the field pushes the wire sideways — that's the motor effect. Bend the wire into a loop and the push twists one side up and the other down, spinning the loop.",
                        "The trick that keeps it spinning: just as the loop lines up with the field and would stop, the commutator — a split-ring contact — flips the current direction, which flips the push, and the loop keeps rotating. Add more loops and you get smoother, stronger rotation. Every fan, drill, EV wheel and fridge compressor is this idea industrialized.",
                    ],
                    "bullets": [
                        "Current + magnetic field = sideways force on the wire",
                        "Loop of current in a field = torque = rotation",
                        "Commutator flips the current every half-turn to keep the spin going",
                        "More loops = smoother, stronger rotation",
                        "Same physics in fans, drills, hard drives and electric cars",
                    ],
                },
            ],
            "key_concepts": [
                ("Magnetic pole", "One of the two ends of a magnet, north or south; poles always come in pairs."),
                ("Magnetic field", "The region of magnetic influence around a magnet, mapped by field lines."),
                ("Ferromagnetic", "Materials like iron, nickel and cobalt that are strongly attracted to magnets."),
                ("Magnetic domain", "Tiny regions in a material where atomic magnetism aligns; aligned domains = magnetized."),
                ("Electromagnet", "A coil of wire whose current produces a magnetic field, usually boosted by an iron core."),
                ("Commutator", "The split-ring switch that reverses current direction each half-turn in a motor."),
                ("Motor effect", "The sideways force on a current-carrying wire inside a magnetic field."),
                ("Compass", "A small magnet that aligns with Earth's magnetic field, pointing roughly north."),
            ],
            "study_tips": [
                "Draw field lines from north to south on every magnet sketch — direction is half the credit.",
                "Remember the strength trio for electromagnets: turns, current, core.",
                "Trace the motor story out loud: push, spin, flip, repeat — until the commutator's job is obvious.",
                "Build the classic nail-and-wire electromagnet once; hands beat diagrams for retention.",
                "Pair this cluster with electricity-basics — Ohm's law plus the motor effect explains most everyday tech.",
            ],
            "practice": [
                {
                    "q": "Which pair of magnetic poles attracts each other?",
                    "choices": ["North and north", "South and south", "North and south", "North and plastic"],
                    "answer": 2,
                    "explain": "Opposite poles attract; like poles repel. Plastic isn't magnetic at all, so nothing happens there.",
                },
                {
                    "q": "Best way to make an electromagnet stronger?",
                    "choices": ["More coils and more current", "Fewer coils", "A plastic core", "Less current"],
                    "answer": 0,
                    "explain": "Strength scales with turns of wire, current and core quality. More coils and more current push all the levers the right way.",
                },
                {
                    "q": "A compass needle points north because:",
                    "choices": ["The needle is painted red", "Earth has a magnetic field", "Wind pushes the needle", "The needle follows the sun"],
                    "answer": 1,
                    "explain": "The needle is a tiny magnet, and Earth's churning molten iron core generates a planet-scale magnetic field that the needle aligns with.",
                },
                {
                    "q": "In a motor, what flips the current direction every half-turn?",
                    "choices": ["The battery", "The magnet", "The coil of wire", "The commutator"],
                    "answer": 3,
                    "explain": "The commutator is a split-ring contact that reverses the current just as the loop would otherwise stall — that's what keeps the rotation going in one direction.",
                },
            ],
            "flashcards": [
                ("Rule of poles", "Opposites attract; likes repel."),
                ("Can a magnet have a single pole?", "No — break a magnet and you get two complete smaller magnets."),
                ("What do field lines show?", "The direction and strength of a magnetic field; closer lines = stronger field."),
                ("Three ferromagnetic elements", "Iron, nickel, cobalt."),
                ("What is an electromagnet?", "A coil of wire with current flowing through it (plus an iron core) — a switchable magnet."),
                ("Three ways to strengthen an electromagnet", "More turns of wire, more current, a better (iron) core."),
                ("Oersted's discovery", "An electric current deflects a compass needle — electricity creates magnetism."),
                ("Motor effect", "A current-carrying wire in a magnetic field gets pushed sideways."),
                ("Job of the commutator", "Reverses the current every half-turn so the motor keeps spinning in one direction."),
                ("Why Earth acts like a magnet", "Its molten iron outer core churns, generating a planet-scale magnetic field."),
            ],
            "faqs": [
                ("Are electricity and magnetism related?",
                 "Deeply — they're two sides of one force called electromagnetism. Moving charge creates a magnetic field, and changing magnetic fields can push charge. Electromagnets, motors and generators all live on this connection."),
                ("Why does a compass point north?",
                 "Earth behaves like a giant magnet thanks to its churning molten iron outer core. The compass needle — itself a tiny magnet — lines up with Earth's field. It points to magnetic north, slightly off from true geographic north."),
                ("Can you turn an electromagnet off?",
                 "Yes — cut the current and the field collapses. That on/off control (plus reversal and strength tuning) is exactly why cranes can drop scrap metal and doorbells can ding."),
                ("How does a motor keep spinning instead of stopping?",
                 "The loop would stop once it aligned with the field — but the commutator flips the current direction at that moment, flipping the force and keeping the rotation going. It's a perfectly timed electrical U-turn."),
            ],
            "paa": [
                ("What makes something magnetic?", "Its atoms' tiny magnetic domains line up instead of canceling out. In iron, nickel and cobalt this happens easily — hence fridge magnets stick to steel, not plastic or aluminum."),
                ("How do you make an electromagnet at home?", "Wrap insulated wire many times around a large iron nail and connect the ends to a battery. More wraps and more current = stronger pickup. Disconnect to switch it off."),
                ("How does an electric motor work in simple terms?", "A current-carrying loop sits in a magnetic field, gets pushed, spins; a commutator flips the current each half-turn so the push never reverses the spin. Repeat thousands of times a minute and you have a drill."),
                ("What's the difference between a permanent magnet and an electromagnet?", "Permanent magnets (fridge magnets) are always on. Electromagnets are on only while current flows — controllable, reversible, scalable, which is why industry runs on them."),
            ],
        },
        {
            "slug": "light-and-optics",
            "title": "Light and Optics",
            "h1": "Light and Optics Explained: Reflection, Refraction, Lenses & Color",
            "meta_title": "Light and Optics Made Simple — Free Guide | StudyBonk",
            "meta_description": "Master light and optics free: reflection, refraction, lenses and color — with worked examples, flashcards and a practice quiz. No sign-up, private.",
            "summary": "Reflection, refraction, lenses and color — light behavior from mirrors to rainbows.",
            "keywords": [
                "light and optics",
                "reflection and refraction",
                "lenses explained",
                "law of reflection",
                "how we see color",
                "free physics practice",
            ],
            "longtail": [
                "law of reflection explained with examples",
                "why does a straw look bent in water",
                "what is refraction in simple terms",
                "concave vs convex lenses and mirrors",
                "how does a magnifying glass work",
                "why do we see different colors",
                "why is the sky blue for kids",
                "what happens when white light passes through a prism",
                "difference between transparent translucent and opaque",
                "how do glasses correct vision basics",
                "what is the focal point of a lens",
            ],
            "sections": [
                {
                    "h2": "Reflection: light bounces",
                    "paras": [
                        "When light hits a surface and bounces back, that's reflection — and it obeys one tidy rule: the angle of incidence equals the angle of reflection, both measured from the normal (an imaginary line perpendicular to the surface). Smooth surfaces like mirrors reflect in an organized way and form images; rough surfaces like paper scatter light in all directions, which is why you can read a page from any angle.",
                        "Plane (flat) mirrors produce images that look real enough but are actually virtual: they appear to be behind the mirror, upright, the same size, and flipped left-right. That flip is why text on your shirt reads backward in the mirror.",
                    ],
                    "bullets": [
                        "Angle of incidence = angle of reflection (measured from the normal)",
                        "Normal = perpendicular line to the surface at the point of impact",
                        "Smooth = organized reflection (images); rough = scattered reflection",
                        "Plane mirror image: virtual, upright, same size, left-right flipped",
                    ],
                    "example": {
                        "title": "Worked example: mirror bounce",
                        "body": "A laser hits a flat mirror at 35° from the normal. By the law of reflection it bounces off at 35° from the normal, on the other side of the normal. Total turn between incoming and outgoing beams: 180 − 35 − 35 = 110°.",
                    },
                },
                {
                    "h2": "Refraction: light bends",
                    "paras": [
                        "When light crosses from one medium to another — air to water, air to glass — its speed changes and its path bends. That's refraction. The rule of thumb: entering a slower medium (like water), light bends toward the normal; exiting into a faster one, it bends away. This bend is why a straw in a glass looks snapped at the waterline and why pools look shallower than they are.",
                        "Refraction is also why prisms and raindrops split white light into a rainbow. Different colors travel at slightly different speeds in glass, so each bends by a slightly different amount — violet most, red least — fanning the beam into the spectrum: red, orange, yellow, green, blue, indigo, violet.",
                    ],
                    "bullets": [
                        "Refraction = bending when light changes speed between media",
                        "Into a slower medium → bends toward the normal",
                        "Into a faster medium → bends away from the normal",
                        "Dispersion: each color bends differently → rainbows (ROYGBIV)",
                        "Lenses are refraction on purpose — curved glass bending rays to a plan",
                    ],
                },
                {
                    "h2": "Lenses and color",
                    "paras": [
                        "A lens uses refraction to focus or spread light. Convex lenses (thicker in the middle) converge rays to a focal point — magnifying glasses, camera lenses and your eye's lens all work this way. Concave lenses (thinner in the middle) spread rays apart and correct nearsightedness in glasses.",
                        "Color: white light is all colors mixed. An object's color is the light it reflects — a red apple absorbs most colors and bounces red back to your eye. The sky is blue because air molecules scatter shorter blue wavelengths across the sky; at sunset, light travels a longer path, the blue scatters away entirely, and reds and oranges are what's left.",
                    ],
                    "bullets": [
                        "Convex lens: converges light — magnifying glass, eye, camera",
                        "Concave lens: diverges light — nearsighted glasses",
                        "Focal point: where parallel rays cross after a convex lens",
                        "Object color = the light it reflects; the rest is absorbed",
                        "Blue sky = scattered blue light; red sunset = long path, blue filtered out",
                    ],
                    "example": {
                        "title": "Worked example: magnification",
                        "body": "A magnifying glass forms an image three times the size of a 5 mm ant. Magnification = image size ÷ object size = 15 ÷ 5 = 3×. If the same ant's image measured 20 mm, magnification would be 4× — same object, stronger effective lens.",
                    },
                },
            ],
            "key_concepts": [
                ("Law of reflection", "The angle of incidence equals the angle of reflection, measured from the normal."),
                ("Normal", "The imaginary line perpendicular to a surface where light hits — the reference for all angle measuring."),
                ("Refraction", "The bending of light as it changes speed moving between media."),
                ("Dispersion", "The splitting of white light into its colors because each color refracts slightly differently."),
                ("Convex lens", "Thicker in the middle; converges light to a focal point (magnifying glass)."),
                ("Concave lens", "Thinner in the middle; diverges light (nearsightedness correction)."),
                ("Focal point", "Where rays parallel to a lens's axis converge after passing through it."),
                ("Virtual image", "An image that appears where light seems to come from, like your reflection 'behind' a mirror."),
            ],
            "study_tips": [
                "Always draw the normal before any angle — most errors come from measuring from the surface instead.",
                "Remember 'slow toward, fast away': entering a slower medium bends light toward the normal.",
                "Connect lenses to your own eyes — glasses are just corrective refraction you wear.",
                "Quiz yourself with household items: spoon reflections, a straw in water, a garden hose mist rainbow.",
                "Drill the ROYGBIV order and which color bends most (violet) and least (red).",
            ],
            "practice": [
                {
                    "q": "Light hits a flat mirror at 35° from the normal. The reflected ray leaves at:",
                    "choices": ["35° from the normal", "55° from the normal", "70° from the surface", "45° from the normal"],
                    "answer": 0,
                    "explain": "Law of reflection: the angle of incidence equals the angle of reflection. Measure both from the normal, not the surface, and 35° in means 35° out.",
                },
                {
                    "q": "Light passes from air into water. It bends:",
                    "choices": ["Away from the normal", "Toward the normal", "Not at all", "Straight back into the air"],
                    "answer": 1,
                    "explain": "Water is a slower medium for light, so the light bends toward the normal — that's why a straw looks kinked at the surface.",
                },
                {
                    "q": "A magnifying glass is a:",
                    "choices": ["Concave lens", "Plane mirror", "Convex lens", "Prism"],
                    "answer": 2,
                    "explain": "A magnifying glass is thicker in the middle — a convex lens — which converges light so objects inside the focal length look enlarged.",
                },
                {
                    "q": "A banana looks yellow because it:",
                    "choices": ["Creates yellow light", "Reflects yellow light and absorbs the rest", "Absorbs yellow light", "Refracts yellow light"],
                    "answer": 1,
                    "explain": "Object color = reflected light. The banana's surface reflects yellow wavelengths to your eye and absorbs most of the others.",
                },
            ],
            "flashcards": [
                ("Law of reflection", "Angle of incidence = angle of reflection, measured from the normal."),
                ("What is the normal?", "The perpendicular line to the surface at the point where light hits."),
                ("Refraction is", "The bending of light when it changes speed crossing into a new medium."),
                ("Bending rule for refraction", "Into a slower medium → toward the normal; into a faster one → away."),
                ("Why a straw looks bent in water", "Refraction: light from the underwater part changes speed at the surface and bends."),
                ("Convex lens does what", "Converges (focuses) light to a focal point — magnifying glass, eye, camera."),
                ("Concave lens does what", "Diverges (spreads) light — used in glasses for nearsightedness."),
                ("Why prisms make rainbows", "Dispersion: each color bends a different amount — violet most, red least."),
                ("Why an apple looks red", "It reflects red light to your eye and absorbs the other colors."),
                ("Why the sky is blue", "Air molecules scatter short-wavelength blue light across the sky."),
            ],
            "faqs": [
                ("Why does a straw look bent in a glass of water?",
                 "Refraction. Light leaving the water slows down and bends at the surface, so the underwater part of the straw appears shifted. Your brain assumes light travels straight — and is fooled."),
                ("What's the difference between reflection and refraction?",
                 "Reflection bounces light off a surface (mirror). Refraction bends light as it passes into a new medium (water, glass). Both can happen at once — that's why you see both your reflection and the pool floor."),
                ("Which lens magnifies: convex or concave?",
                 "Convex. Its thicker middle converges rays, letting objects sit inside the focal length and appear enlarged — a magnifying glass at work. Concave lenses shrink the view and correct nearsightedness."),
                ("Is white light really a color?",
                 "It's all of them. Pass sunlight through a prism and it separates into red through violet. White objects reflect every color; black objects absorb them all — which is why black asphalt cooks in summer."),
            ],
            "paa": [
                ("What is the law of reflection?", "The incoming and outgoing angles are equal, measured from the normal — a 30° hit bounces at 30°."),
                ("Why does light bend in water?", "It slows down entering the water, and the change in speed swings its path toward the normal — that's refraction."),
                ("How do lenses form images?", "Curved glass refracts rays so they converge (convex) or spread (concave), rearranging light into an image — real on a screen, or virtual like a magnifier's."),
                ("Why is the sky blue but sunsets red?", "Air scatters blue light easily, painting the whole sky blue. At sunset the light crosses more air; the blue is scattered away before reaching you, leaving reds and oranges."),
            ],
        },
    ],
}
